### ISSUE TITLE
Use of tcnative UNREFERENCED macros

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#102]
We should investigate what the purpose/value of the `UNREFERENCED` and `UNREFERENCED_STDARGS` macros are. We should clarify with comments what their purpose are if they are necessary. We should also consistently use them w.r.t to function pre-condition checks. For example some times we call `UNREFERENCED` before a precondition check and return, and sometime we only call it if the preconditions are satisfied.

**Comment by Scottmitch** [comment]
@normanmaurer @nmittler - FYI

**Comment by normanmaurer** [comment]
These are basically only there to silent compiler warnings about unused parameters. I guess we can just remove all of them.
