### ISSUE TITLE
Update build and usage instructions

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#112]
Given recent refactoring into multi-modules and added support for linking statically to OpenSSL libraries, we need to update the [docs on the wiki for building netty-tcnative](https://github.com/netty/netty/wiki/Forked-Tomcat-Native).

Some things that should be made clear (from #115):

- The versions of Java are supported?
- Which JDKs are supported? All? Just Oracle?
- Which OS/arch are supported?
- For the dynamically-linked versions, are specific versions of the native SSL providers required?

**Comment by nmittler** [comment]
@normanmaurer @Scottmitch
I've updated the wiki. The instructions are anticipating Fork15, so we probably don't want to publish them until the uber jar is on Maven Central.

PTAL

**Comment by nmittler** [comment]
@normanmaurer @Scottmitch gentle ping :)

**Comment by Scottmitch** [comment]
@nmittler - LGTM! Thanks for updating the docs!

**Comment by nmittler** [comment]
@normanmaurer do you want to take a look?

**Comment by nmittler** [comment]
The docs were updated a while ago, I think we can close this now.
