### ISSUE TITLE
Document system requirements

### ISSUE THREAD

**Issue by jchambers** [netty/netty-tcnative#115]
I'm really excited about the statically-linked packages that have just gone out, and also what might come out of #113. I've been trying to figure out whether I can use statically-linked tcnative across the board for a project, and am realizing that some information about system requirements is a little tricky to come by. As recently as [ca90f9e](https://github.com/netty/netty/wiki/Forked-Tomcat-Native/ca90f9e00aa92b68eaf6b80ef25c4addb0a4cfb8), it's not immediately obvious from the README which operating systems/JDKs are supported by netty-tcnative. Some questions I had that didn't have immediate answers:

- What versions of Java are supported? (I understand this to be Java 7+)
  - Which JDKs are supported? All? Just Oracle?
- Which operating systems are supported?
  - Looks like Linux (all?), OS X, and Windows.
  - What about non-Linux flavors of Unix?
  - It looks like there isn't support for ARM-based Linux; is that accurate?
- For the dynamically-linked versions, are specific versions of the native SSL providers required?

Thanks!

**Comment by nmittler** [comment]
@jchambers +1 we should definitely do this.  In fact, we really need to just rewrite the docs completely at this point (see #112).  I've copied over your list to that issue ... let's close this out and continue the discussion there.

Thanks!

**Comment by jchambers** [comment]
:metal:

Thanks!
