### ISSUE TITLE
Static Library Build Phase

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#120]
Just initializing the project files for the IDE `mvn eclipse:eclipse` seems to build all of the static libraries. Is this necessary just for setting up the IDE project files (building the static libraries can take some time).

**Comment by nmittler** [comment]
use intellij :) .... feel free to pick another appropriate phase.  So long as everything build we should be fine.

**Comment by Scottmitch** [comment]
is there any reason why `generate-sources` must be used for everything? are there any other dependencies on other phases?

Would the following structure make more sense:
`generate-sources`: ftp code
`compile`: compile the code
`package`: build static libraries

**Comment by nmittler** [comment]
We just need to ensure that APR and SSL are built before the tcnative code.

**Comment by Scottmitch** [comment]
> We just need to ensure that APR and SSL are built before the tcnative code.

Can you explain why? Seems like as long as we have the header files for the libraries tcnative depends upon then tcnative should be able to build. Why can't we delay the build of the 3rd party libraries until we are trying to package/link stuff together?

**Comment by nmittler** [comment]
Sure you can do that ... just not sure what it buys you.  To be honest, I don't think the problem is which phase we do it in, it's that we don't want to re-do what we've already done. If APR and SSL are already there, then skip download/build.

**Comment by Scottmitch** [comment]
> To be honest, I don't think the problem is which phase we do it in, it's that we don't want to re-do what we've already done.

I think these are 2 separate problems :) The second part should be covered by https://github.com/netty/netty-tcnative/issues/121

**Comment by Scottmitch** [comment]
> Sure you can do that ... just not sure what it buys you.

The current approach does not follow standard maven conventions. This means that plugins and tools may not function as expected or additional work may be necessary at unexpected times (e.g. why do I have to build openssl, boringssl, libressl, apr, etc... just to setup my IDE)?

**Comment by nmittler** [comment]
Ok, if you have ideas for what needs to change, throw together a PR and we'll take a look
