### ISSUE TITLE
Static Library Cleaning and Rebuilding

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#121]
Are the builds for the static libraries "cleaned" every time? It seems the following commands will run through 2 complete builds of the static libraries:

```
mvn clean install
mvn install
```

Is it possible to avoid "cleaning" everything and "rebuilding" every time?

**Comment by nmittler** [comment]
possibly ...  I'm not sure what LOE this would involve.

**Comment by Scottmitch** [comment]
are we just blowing away the build artifacts when we FTP new code (or however we get new code)?

**Comment by nmittler** [comment]
> are we just blowing away the build artifacts when we FTP new code (or however we get new code)?

If using ftp, probably ... if using the scm plugin (e.g boringssl), not sure. 

> can the build artifacts follow the typical build phases (mvn clean destroys build artifacts, and otherwise they persist)?

That would be ideal :) ... but sorting this out for each submodule (for both APR and SSL) will require some work.

**Comment by Scottmitch** [comment]
I think we should restructure the project so the build artifacts are separated from the directories that get FTPed. The configure scripts should support specifying a `prefix` or build directory right?

**Comment by nmittler** [comment]
Which build artifacts are you referring to? APR and SSL? In some cases, we're already creating an install directory (using `--prefix` when using automake). For ninja-based builds, we'd have to manually copy artifacts, but it's still doable.

**Comment by Scottmitch** [comment]
> Which build artifacts are you referring to?

things that are generated during the build (`.o`, `.a`, `.class`, etc...) that can be inspected by build tools (make, maven, etc..) to avoid re-building if not necessary.

**Comment by nmittler** [comment]
so APR and SSL?

**Comment by Scottmitch** [comment]
> APR and SSL

This statement was a bit vague and not clear what you were referring to. As long as you are implying the difference between source files obtained via the "get sources step" and the artifacts generated during the build (`.o`, `.a`, `.class`) then yes plus the tcnative artifacts.

```bash
$ ls -al ./boringssl-static/target/native-build/src/.libs/ssl.o
... Feb 24 10:25 ./boringssl-static/target/native-build/src/.libs/ssl.o
$ mvn install
...
$ ls -al ./boringssl-static/target/native-build/src/.libs/ssl.o
... Feb 24 10:36 ./boringssl-static/target/native-build/src/.libs/ssl.o
```

**Comment by normanmaurer** [comment]
This was fixes by https://github.com/netty/netty-tcnative/pull/390
