### ISSUE TITLE
EpollChannelOption.TCP_QUICKACK is set as an Integer

### ISSUE THREAD

**Issue by fondemen** [netty/netty-tcnative#128]
Hello,

Why EpollChannelOption.TCP_QUICKACK is an Integer option ?
In the code, it seems to me that it should be a Boolean, as can be seen in EpollSocketChannelConfig#getOption(ChannelOption), L.105.

Cheers,

Frédéric.

**Comment by normanmaurer** [comment]
@fondemen you are right... let me fix it or you want to do a PR ?

**Comment by normanmaurer** [comment]
@fondemen actually this is a netty issue and not a netty-tcnative. Did open an issue here:
https://github.com/netty/netty/issues/5029
