### ISSUE TITLE
Linux .so for boring isn't stripped

### ISSUE THREAD

**Issue by ejona86** [netty/netty-tcnative#129]
This is effectively a repeat of #45, but for boring and MB involved instead of KB. OS X's native library is 1.9 MB uncompressed, whereas Linux's is 7.1 MB. Running strip on the Linux .so reduces its size to 1.9 MB. I think that will change the compressed size from 2.5 MB to ~900 KB.

**Comment by normanmaurer** [comment]
@nmittler any idea how to do this with ninja build ?

**Comment by normanmaurer** [comment]
Actually I think I know howto fix this... let me take care

**Comment by normanmaurer** [comment]
@davidben Could this be because `-ggdb` is used in boringssl here: https://boringssl.googlesource.com/boringssl/+/chromium-stable/CMakeLists.txt#30 ? (@nmittler told me to ping you ;))

**Comment by davidben** [comment]
I could believe it. That's probably why there's so much to strip away. Having debug symbols available is generally useful and the standalone build, on our end, is used for development, so I'd want that to stay the default.

That said, it seems `CMAKE_BUILD_TYPE` distinguishes between "Release" and "RelWithDebInfo". I need to read up on how that knob is supposed to work, but I wouldn't be opposed to making only "RelWithDebInfo" and "Debug" generate debug symbols while plain "Release" does not.
https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html

Could you confirm that taking that bit out does the trick for you?

**Comment by normanmaurer** [comment]
@davidben confirmed here...

Before change the CMakeLists.txt:

```
# cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_ASM_FLAGS=-Wa,--noexecstack -GNinja ..
# ninja
# du -h ssl/libssl.a
2,8M	ssl/libssl.a
```

After the change:

```
# cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_ASM_FLAGS=-Wa,--noexecstack -GNinja ..
# ninja
# du -h ssl/libssl.a                                                                                                    
472K	ssl/libssl.a
```

**Comment by normanmaurer** [comment]
Also @nmittler @ejona86 :)

**Comment by davidben** [comment]
Alright. Filed https://crbug.com/boringssl/56.

**Comment by davidben** [comment]
Although I would suggest regardless that you strip your binaries yourselves if you care about this sort of thing. That seems much more robust.

**Comment by normanmaurer** [comment]
Fixe by https://github.com/netty/netty-tcnative/pull/144
