### ISSUE TITLE
CI Server links broken in wiki page

### ISSUE THREAD

**Issue by sunrenjie** [netty/netty-tcnative#130]
Hi,
I followed the link http://netty.io/wiki/forked-tomcat-native.html#wiki-h2-5 to find 64-bit windows APR DLLs, but the links are broken, due to maybe CI Server changes (jenkins => TeamCity).

Further more, I scanned https://garage.netty.io/teamcity/, but it does seem not build for Windows at all.

Am ideas?

**Comment by normanmaurer** [comment]
@sunrenjie we fixed the docs and also re-added a windows slave
