### ISSUE TITLE
netty-4.0.35.Final breaks ssl < TLSv1.2 when used w/ netty-tcnative >= 1.1.33.Fork13

### ISSUE THREAD

**Issue by gsoltis** [netty/netty-tcnative#131]
In the transition from `1.1.33.Fork12` to `1.1.33.Fork13`, the native implementation of `SSLContext.make` in `sslcontext.c` was restructured to use a `switch` statement, rather than a series of `if .. else if` statements. In the process, the default case when not finding an exact match for `protocol` changed from `SSLv23_method` to `TLSv1_2_method`. 

This is coupled with the fact that `netty-4.0.35.Final` was compiled against `netty-tcnative-1.1.33.Fork11` means that `protocol` will not be correct by default. The value in `Fork11` was `28` (`SSL_PROTOCOL_TLSV1 | SSL_PROTOCOL_TLSV1_1 | SSL_PROTOCOL_TLSV1_2`), and this is compiled into the `.class` file for `OpenSslContext` in `netty-all`. 

Unfortunately, this is not the correct value, and with the restructuring to a `switch` statement, this value doesn't match any particular case and falls through to the new default: `TLSv1_2_method`. Client versions < TLSv1.2 then stop working, because the server no longer supports them.

**Comment by Scottmitch** [comment]
@gsoltis - We are aware of the issue and plan to push out a new release this week. The investigation thus far has not found any issue with the code changes made to `sslcontext.c` but instead requires that Netty be rebuilt with the correct version of tcnative (which may not be immediately obvious). As a workaround please recompile Netty against a newer version of tcnative or wait until we push out the new release.

> This is coupled with the fact that netty-4.0.35.Final was compiled against netty-tcnative-1.1.33.Fork11

netty 4.0.35 was compiled against tcnative 1.1.33.Fork14.

**Comment by gsoltis** [comment]
Ah, you're right, not sure where I got `Fork11` from. I agree, I don't think anything is wrong w/ `sslcontext.c`, it's just that the default behavior change coupled with the wrong `protocol` value caused a problem. With the correct value for `protocol`, it's fine.

Anyways, glad to hear you're all on top of it, I'll wait for the new version.

Thanks!

**Comment by Scottmitch** [comment]
> Anyways, glad to hear you're all on top of it, I'll wait for the new version.

sgtm. Thanks for reporting and sorry for the inconvenience!
