### ISSUE TITLE
Docs give example for non-existent uber-jar

### ISSUE THREAD

**Issue by jchambers** [netty/netty-tcnative#133]
Following up on https://github.com/netty/netty/issues/5052, [the wiki](http://netty.io/wiki/forked-tomcat-native.html#how-to-download-netty-tcnative-boringssl-uber-jar) gives instructions for using an uber jar with fork15, but there won't be an uber jar until fork16.

**Comment by nmittler** [comment]
@normanmaurer how close are we to releasing fork 16?

**Comment by normanmaurer** [comment]
@nmittler as close as you want ;)

**Comment by nmittler** [comment]
@normanmaurer ok great ... should we just cut it then? We can work together to sort out the deployment of the uber jar.

**Comment by twiedow** [comment]
Do you already when you might release fork 16 with the uber jar?

**Comment by jchambers** [comment]
It looks like fork16 is out and does, indeed, work with the example app from netty/netty#5052. The only thing that seems to be left is updating the version numbers in the example on the wiki; I'd offer to do it myself, but don't have permission.

**Comment by nmittler** [comment]
@jchambers Great, glad it's working for you! I've updated the docs - thanks for pointing that out.

@normanmaurer do we have to push the site manually or is it automatic?

**Comment by normanmaurer** [comment]
@nmittler we need to push.... I will take care

**Comment by normanmaurer** [comment]
Pushed it.
