### ISSUE TITLE
Migrate BoringSSL build to MSVC 2015

### ISSUE THREAD

**Issue by davidben** [netty/netty-tcnative#134]
@nmittler asked me to file a bug here when we were ready to switch BoringSSL's MSVC version. BoringSSL tracks Chromium's MSVC version which has since switched to MSVC 2015. It should currently build with either, but I'll be switching our bots to 2015 soonish and it'll likely (accidentally or intentionally) break with 2013 when we're no longer regularly testing against it.

**Comment by nmittler** [comment]
Thanks @davidben!

@normanmaurer assuming you don't see any issue here I can take a look at migrating.

**Comment by normanmaurer** [comment]
Go :)

**Comment by davidben** [comment]
Oof, sorry about the premature warning. I forgot you all were tracking whatever's in Chrome stable rather than master and BoringSSL didn't actually build with 2015 (the standalone build is very aggressive about enabling warnings) until more recently than that. So the time to flip the switch will be a release cycle or two from now.

**Comment by davidben** [comment]
I've updated `chromium-stable` to match the newly released Chrome 51. In theory this should build now with 2013 or 2015, though let me know if something doesn't work.

**Comment by normanmaurer** [comment]
@davidben I love "in theory" ;) Thanks will do :)

**Comment by nmittler** [comment]
Looks like `chromium-stable` is building with msvc 2015.  I'll roll a PR to upgrade netty-tcnative.

**Comment by normanmaurer** [comment]
Thx
