### ISSUE TITLE
Plan to move to 1.2?

### ISSUE THREAD

**Issue by testn** [netty/netty-tcnative#137]
tomcat already released 1.2.6 of tomcat-native. Is there any plan to move to 1.2 branch soon?

**Comment by Scottmitch** [comment]
IIUC 1.2.x branch of tomcat's tcnative is re-forked from netty-tcnative ... @normanmaurer ? We have also stripped out most of the stuff we don't need from tcnative so I'm not sure if we can easily pull back changes.

**Comment by normanmaurer** [comment]
@testn @Scottmitch actually the idea is to port relevant changes.
