### ISSUE TITLE
Can openssl-static be built with the openssl and APR that are already installed?

### ISSUE THREAD

**Issue by mwkirk** [netty/netty-tcnative#138]
The openssl, apr, tcnative dance is always a process, but this has been a hair-puller. I've read your wiki numerous times, but either I'm not getting it (totally possible) or there are some bits that are incomplete.

I need to build openssl-static tcnative for two platforms (Mac 10.10.5 and Ubuntu 14.04 LTS), and I would prefer to use the OpenSSL and APR that are already installed (and other things are linked against). Is there a way to do that? When I build with maven, it _always_ downloads APR and OpenSSL and tries to use that (it also fails when trying to untar openssl, but that's another issue).

Is there a maven incantation (or another way to build) that will let me use my existing/installed openssl and APR?

Thanks!

**Comment by normanmaurer** [comment]
@mwkirk no it can`t easily, sorry.

**Comment by mwkirk** [comment]
Thanks. I suggest adding that to that wiki page so that other folks don't suffer my fate.
