### ISSUE TITLE
Allow loading on Java 1.8

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty-tcnative#146]
When loading from statically built native deps, the JNI_OnLoad symbols from multiple JNI libraries can collide. Java 1.8 has a work around for this, by renaming the load and unload methods to JNI_OnLoad_foo as described in the second paragraph [here](http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#JNJI_OnLoad).  

In order for this to work, there should be an additional Onload method [here](https://github.com/netty/netty-tcnative/blob/1.1.33/openssl-dynamic/src/main/c/jnilib.c#L49), which can probably be called JNI_OnLoad_netty_tcnative  (and corresponding unload).  Additionally, the   JNI_VERSION_* values should be settable as a compiler define, so that they can be set to JNI_VERSION_1_8  when running on JDK8.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Can you clarify how we would retain backwards compatibility? Would we need to produce different artifacts for different java versions? Is it enough to just put `JNI_OnLoad` and `JNI_OnLoad_L` in different source files and who ever compiles can choose the appropriate one for their JDK versions (assuming they are building their own static library)?

**Comment by carl-mastrangelo** [comment]
Maybe just have both methods? JNI_OnLoad  and JNI_OnLoad_netty_tcnative  ?  Then just have one call the other?  The thing is that when the binaries are linked together it seems that having duplicate methods is not the problem; one of them wins.  Having the other method name makes it possible to fix from the java side.

**Comment by Scottmitch** [comment]
assuming the presences of multiple `JNI_OnLoad`'s symbols can be combined into the same static library and linked by java 1.8+ then that sgtm.

**Comment by carl-mastrangelo** [comment]
At least in Google's infra they can.  What the rest of the outside world does is frightening and confusing to  me, which is why I haven't jumped to make these changes.  

I can roll together a PR, and submit it, and if anyone complains we can roll it back.

**Comment by Scottmitch** [comment]
PR sgtm!

**Comment by normanmaurer** [comment]
+1
