### ISSUE TITLE
Compiling netty-tcnative on Raspberry Pi 3 errors

### ISSUE THREAD

**Issue by jakkra** [netty/netty-tcnative#148]
`Failed to execute goal on project MagicMirrorPI: Could not resolve dependencies for project se.jakobkrantz.magicmirrorr:MagicMirrorPI:jar:1.0: Could not find artifact io.netty:netty-tcnative-boringssl-static:jar:linux-arm_32:1.1.33.Fork17 in oss-snapshots-repo (https://oss.sonatype.org/content/groups/public)`

Since there is no 32 bit versions on Maven, I also tried to compile according to instructions here: 

```
http://netty.io/wiki/forked-tomcat-native.html
git clone https://github.com/netty/netty-tcnative.git
cd netty-tcnative
To build a specific version: (e.g. netty-tcnative-1.1.33.Fork16)
git checkout netty-tcnative-[version]
To build a snapshot: (e.g. 1.1.33)
git checkout [branch]
mvn clean install
```

This doesn't work either, the build fails with this:

main:
     [exec] CMake Error at CMakeLists.txt:141 (message):
     [exec]   Unknown processor:armv7l
     [exec] 
     [exec] 
     [exec] -- Configuring incomplete, errors occurred!
     [exec] See also "/home/pi/Documents/netty/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build/CMakeFiles/CMakeOutput.log".
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:45 min
[INFO] Finished at: 2016-05-29T22:06:26+02:00
[INFO] Final Memory: 11M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-boringssl) on project netty-tcnative-boringssl-static: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec resolveexecutable="true" failonerror="true" dir="/home/pi/Documents/netty/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build" executable="cmake">... @ 19:178 in /home/pi/Documents/netty/netty-tcnative/boringssl-static/target/antrun/build-main.xml

Any idea how I can get it to compile on my Raspberry Pi 3?

**Comment by nmittler** [comment]
You might want to try just building openssl-static instead

**Comment by normanmaurer** [comment]
So did it work?

**Comment by jakkra** [comment]
Sorry, been away. Yes it seems to work, but can't confirm, because I ran into other problems. Not any relevant to this project tho.
