### ISSUE TITLE
jnilib vs dylib os extension for lib

### ISSUE THREAD

**Issue by siyengar** [netty/netty-tcnative#150]
I'm running netty with tcnative on macosx. While depending on tc-native's1.1.33.Fork17 with boringssl with the os classifer, I was unable to load the library. I investigated this further, and the NativeLibraryLoader in netty tries to map the lib name to a system name here: https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L175

In jdk 8 I observed that this returns **tc-native.dylib**, however looking at the deployed jar it looks like it has a binary with the extension **tc-native.jnilib**. Could we deploy both instead to deal with different jdk versions. Thanks.

**Comment by nmittler** [comment]
It looks like we should be checking for [both jnilib and dylib]( https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L180).

Does it not enter this conditional?

**Comment by siyengar** [comment]
@nmittler ya you're right. It looks like it's working now. I must have hit an unrelated error and thought that this was the problem.
