### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no provided in java.library.path using spring boot/tomcat embedded

### ISSUE THREAD

**Issue by WeirdBob** [netty/netty-tcnative#151]
I'm using netty 4.1.0CR7 & netty-tcnative-boringssl-static 1.1.33.Fork17 in a spring boot project (tomcat-embed-core-8.0.33). There seem to be an incompatibility in the org.apache.tomcat.jni.Library class (provided by both projects): 
io.netty.handler.ssl.OpenSsl l81 : Library.initialize("provided"); fails when the tomcat provided Library class is loaded first since it tries to load a provided.dll library that doesn't exist. 
I think it's the same issue as #136 (but reversed, tomcat lib being loaded before netty lib in my case)
Hope my jiberish makes sense...

**Comment by pires** [comment]
Same here.

**Comment by Scottmitch** [comment]
@normanmaurer - perhaps addressing https://github.com/netty/netty-tcnative/issues/104, removing APR dependency, and move the remaining classes remaining to `io.netty.native.ssl` package may help with these conflicts ... wdyt?

**Comment by normanmaurer** [comment]
Yep .... At some point I started with this. Let me pick it up next week again

**Comment by nmittler** [comment]
@Scottmitch @normanmaurer maybe it's time to seriously start looking at conscrypt?

**Comment by nmittler** [comment]
FYI, we already have an issue open for taking a look at conscyrpt: #114

**Comment by rohit321** [comment]
Ran into this issue. We use spring-boot and grpc which requires netty-tcnative boring ssl. Is there any work around for this issue, as we are blocked on this

**Comment by pires** [comment]
@rohit don't use Tomcat. Worked for me.

**Comment by rohit321** [comment]
Thanks @pires , Getting rid of tomcat did the trick!!

**Comment by WeirdBob** [comment]
Hi, 
is there an update for this?
I switched from tomcat to jetty in order to be able to work but I should deploy with tomcat in production (corporate rules) so this one could become troublesome.

**Comment by hzariv** [comment]
I filed #5948 on netty and it was closed as dup of this one. I am also using Spring Boot and Google gRPC and I am currently blocked as I need to use tomcat and gRPC together (I don't have the option of getting ride of Tomcat :-()

**Comment by normanmaurer** [comment]
Fixed in master branch and will be part of 2.0
