### ISSUE TITLE
BoringSSL: Allow option to enable renegotiation

### ISSUE THREAD

**Issue by tomfitzhenry** [netty/netty-tcnative#156]
BoringSSL disables renegotiation by default:

> OpenSSL enables TLS renegotiation by default and accepts renegotiation requests from the peer transparently. Renegotiation is an extremely problematic protocol feature, so BoringSSL rejects peer renegotiations by default.
> To enable renegotiation, call SSL_set_reject_peer_renegotiations and set it to off. Renegotiation is only supported as a client in SSL3/TLS and the HelloRequest must be received at a quiet point in the application protocol. This is sufficient to support the common use of requesting a new client certificate between an HTTP request and response in (unpipelined) HTTP/1.1.

It would be useful to have an option to enable this, for users with the "common use of requesting a new client certificate between an HTTP request and response in (unpipelined) HTTP/1.1" (such as myself!).

**Comment by normanmaurer** [comment]
Will have a look... @tomfitzhenry do you use netty-tcnative with netty or not ?

**Comment by tomfitzhenry** [comment]
I use netty-tcnative indirectly via https://github.com/AsyncHttpClient/async-http-client .

**Comment by tomfitzhenry** [comment]
(Incidentally, I tried this with tcnative's OpenSSL bindings on OSX, and it seemed to hang after receiving CertificateRequest. I will raise an issue, once I've confirmed I'm not doing something stupid, and have steps to reproduce.)

**Comment by Scottmitch** [comment]
>  and it seemed to hang after receiving CertificateRequest

@tomfitzhenry - What version of Netty are you using? Did you see the CVE mentioned in http://netty.io/news/2016/06/07/4-1-1-Final.html ?

**Comment by bbc-tomfitzhenry** [comment]
I'm using 4.0.37.Final, as that's the version used by async-http-client. async-http-client's upgrade to netty 4.1 is tracked in https://github.com/AsyncHttpClient/async-http-client/issues/1161 .

I hadn't seen the CVE. At the moment I don't have tc-native on my classpath, but that is worrying.

**Comment by normanmaurer** [comment]
Actually I think we should not do this at all anymore and we even not support it anymore in netty with netty-tcnative
