### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by mohamedhafez** [netty/netty-tcnative#165]
I saw that 1.1.33.Fork18 just came out, it would be really helpful if basic release notes were included at https://github.com/netty/netty-tcnative/releases just so we know if its an urgent security release, or if we can take our time upgrading as needed

**Comment by normanmaurer** [comment]
@mohamedhafez it is not out yet... Im still in the release process. If a release contains security fixes we mention it explicitly. 1.1.33.Fork18 will only be a bug-fix / feature release.

**Comment by mohamedhafez** [comment]
Ah perfect, where exactly would that info be mentioned, at https://github.com/netty/netty-tcnative/releases?
