### ISSUE TITLE
netty-tcnative fails to build for libressl

### ISSUE THREAD

**Issue by blucas** [netty/netty-tcnative#166]
Hi all,

With the latest set of changes (in Fork18), netty-tcnative fails to build for LibreSSL.

More specifically, I believe the issues I am having relate to change: https://github.com/netty/netty-tcnative/commit/444598bd5851fe92668953cd113396e72871a27f

As far as I can tell, LibreSSL does not have a function called `OPENSSL_malloc_init();` nor does it have a `define` for `TLS_ST_SR_CLNT_HELLO`. Similarly I don't believe it has a function called `X509_REVOKED_get0_serialNumber(revoked)` either.

@normanmaurer - FYI

**Comment by normanmaurer** [comment]
@blucas let me check... what libressl version you are using ?

**Comment by blucas** [comment]
@normanmaurer - I tried with 2.1.9 and 2.3.4.  One thing I've found is LibreSSL reports the OPENSSL_VERSION_NUMBER as 2.x+ so it kinda defeats the purpose of the version check.

**Comment by normanmaurer** [comment]
@blucas yep... fixing it atm.. In the meantime you can compile against 2.4.x .
