### ISSUE TITLE
Proposal: re-home wiki page to git README

### ISSUE THREAD

**Issue by cconroy** [netty/netty-tcnative#180]
I propose that we move the netty-tcnative wiki page (hosted in the Netty project) into the netty-tcnative project as the top level README.md.

I recently added 3rd party dependency verification instructions for users doing local builds, and also I hope that the official maintainers can follow these steps as well to ensure the integrity of our builds. However, anyone can edit the wiki page and could insert malicious build instructions. By moving to a version controlled README.md we get an audit trail and proper gatekeeping.

**Comment by cconroy** [comment]
Though, my edits still haven't gone live on http://netty.io/wiki/forked-tomcat-native.html?

**Comment by normanmaurer** [comment]
@cconroy I need to publish the site by hand for this. Will do later today.

**Comment by normanmaurer** [comment]
I think we can close this one
