### ISSUE TITLE
Duplicate certificates returned Using Fork 21

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty-tcnative#184]
Running the gRPC SSL tests with fork 21 of netty TC native (and 4.1.5 netty)  results in duplicate certs being returned by `SSLSession.getPeerCertificates()` 

These are not present (due to a different error) with Fork 20.

**Comment by normanmaurer** [comment]
Will check

**Comment by normanmaurer** [comment]
@carl-mastrangelo see https://github.com/netty/netty-tcnative/pull/185
