### ISSUE TITLE
Any reason why tags have now different name?

### ISSUE THREAD

**Issue by pires** [netty/netty-tcnative#186]
It went from `netty-tcnative-1.1.33.Fork20` to `netty-tcnative-parent-1.1.33.Fork21`.

Since I have automated some stuff to use the first, I'm trying to figure out the reasoning behind this, if any to make sure I don't miss a thing when upgrading my stuff.

**Comment by normanmaurer** [comment]
@pires no real reason beside that this is what the maven release plugin suggests when releasing.

**Comment by pires** [comment]
Well, you said it, _suggests_. Thanks.

**Comment by normanmaurer** [comment]
@pires yeah... seems like I should have payed more attention :(
