### ISSUE TITLE
Need netty-tcnative for s390x platform on maven repository

### ISSUE THREAD

**Issue by Nayana-ibm** [netty/netty-tcnative#195]
We are building grpc-java master on s390x platform, however we were facing issue with netty-tcnative jar. This jar is not availble for s390x on maven repository. Hence build was failing. 

We have built netty-tcnative on s390x by adding few changes in boringssl-static code. 
Could you please publish the jar for s390x platform on maven central repository? 

Kindly let us know if you need more information.

**Comment by normanmaurer** [comment]
@Nayana-ibm we (netty core developers) have no s390x platform so I think this is not possible atm. That said if you want you can open a PR with the changes for boringssl-static and we can pull it in so you can more easily build it by yourself

**Comment by normanmaurer** [comment]
@Nayana-ibm ping... can you please let us know which changes you need for tcnative ? Best would be a PR.... That said we have currently no access to such a platform so we can not include it in the release cycle.

**Comment by Scottmitch** [comment]
even if a PR was submitted ... since we don't support this platform (we don't have access to one) there are no compatibility guarantees in the future.

**Comment by normanmaurer** [comment]
+1... it's just an best effort thingy

**Comment by Scottmitch** [comment]
> they have asked us to maintain a local patch.

I feel the same way. We don't have access to this platform so we won't be able to effectively support it. The diff you submitted above for Netty doesn't look sufficiently generic either.

**Comment by normanmaurer** [comment]
closing as we do not have the infrastructure to support this
