### ISSUE TITLE
Lzma Dependency No Longer Supported

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#203]
Our LZMA dependency is no longer maintained [1] and has outstanding issues. Should we fork it, or find another project?

```
<dependency>
  <groupId>com.github.jponge</groupId>
  <artifactId>lzma-java</artifactId>
  <version>1.3</version>
</dependency>
```

[1] https://github.com/jponge/lzma-java/issues/14#issuecomment-260933387

**Comment by normanmaurer** [comment]
Let us move this to Netty issue tracker

**Comment by Scottmitch** [comment]
whoops 😓 

https://github.com/netty/netty/issues/6031
