### ISSUE TITLE
Build depends on non-existent src.zip

### ISSUE THREAD

**Issue by timboudreau** [netty/netty-tcnative#21]
My [build of netty-tcnative fails](http://timboudreau.com/builds/job/netty-tcnative/9/console) because it tries to download 
https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-tcnative/1.1.32.Fork1-SNAPSHOT/netty-tcnative-1.1.32.Fork1-SNAPSHOT-native-src.zip

which is a 404 (I guess you have it cached or it is in some other repo?).

(I do not know if it would succeed on Solaris, but I can't even find out...)

This in turn causes [netty issue 2668](https://github.com/netty/netty/issues/2668) and my netty build fails.

And _that_ in turn causes my [build of Scamper to fail](http://timboudreau.com/builds/job/scamper/11/console) because Jenkins local repo contains a mix of downloaded and locally built JARs.

I think if netty-tcnative gets fixed, the rest of the problems will solve themselves.  Anything we can do here?

**Comment by timboudreau** [comment]
Right about automake not being installed, so that gets us a [little further](http://timboudreau.com/builds/job/netty-tcnative/14/console)

```
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -g -O2 -I/opt/local/include/apr-1 -I/opt/java/include -I/opt/java/include/solaris -c src/ssl.c  -fPIC -DPIC -o src/.libs/ssl.o
[INFO] src/ssl.c:1724:2: error: #error OpenSSL is required!
[INFO] src/ssl.c: In function 'Java_org_apache_tomcat_jni_SSL_getErrorString':
[INFO] src/ssl.c:2021:3: error: 'ssl' undeclared (first use in this function)
[INFO] src/ssl.c:2021:3: note: each undeclared identifier is reported only once for each function it appears in
[INFO] make: *** [src/ssl.lo] Error 1
[INFO] Makefile:54
```

OpenSSL 1.0.1j **is** installed:

```
root@builds2 / $ find . -name ssl.h
./opt/local/include/openssl/ssl.h
```

so I'm mystified as to why it thinks it's seeing something else.  No idea if it's confused about something on the system, or if it's something genuinely broken in the build.

At least it's getting a little further :-/

**Comment by timboudreau** [comment]
Also checking on [smartos-discuss](http://www.listbox.com/member/archive/184463/2015/03/sort/time_rev/page/1/entry/0:47/20150307162040:CBC93822-C50F-11E4-B800-D08C795DB985/) to see if anyone knows of a common problem building against OpenSSL on [SmartOS](http://smartos.org).

**Comment by timboudreau** [comment]
Okay, got it down to:
```
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -g -O2 -I/opt/local/include/apr-1 -I/opt/java/include -I/opt/java/include/solaris -c src/sslcontext.c  -fPIC -DPIC -o src/.libs/sslcontext.o
[INFO] src/sslcontext.c:1526:1: error: redefinition of 'Java_org_apache_tomcat_jni_SSLContext_sessionHits'
[INFO] src/sslcontext.c:1491:1: note: previous definition of 'Java_org_apache_tomcat_jni_SSLContext_sessionHits' was here
[INFO] make: *** [src/sslcontext.lo] Error 1
```

Looks like something is being included twice?

**Comment by normanmaurer** [comment]
Interesting... Will check

**Comment by normanmaurer** [comment]
@timboudreau ok this is a bug.. I will fix it. But this will only be triggered if "HAVE_OPENSSL" is not set. Which means it was not able to find and link against openssl. Could you please paste the full mvn clean package output ?

**Comment by timboudreau** [comment]
Log file [here](http://timboudreau.com/files/tcnative.log), tarball of target directory [here](http://timboudreau.com/files/tcnative-target.tar.bz2)

Also wondering if it is misdetect 32 vs 64 bit - it's a 64 bit VM;  SmartOS and Solaris are multilib systems - noticed - `os.detected.classifier: sunos-x86_32` - but that could be a red herring.

**Comment by timboudreau** [comment]
SmartOS, being an OpenSolaris fork, comes with SunSSL installed, though you can install OpenSSL alongside it in `/opt/local`.

I am wondering if it is just finding the SunSSL header files, but I don't see a way to correct it (or be sure that's what's happening) through the hawtjni plugin.  Any ideas?

```
[INFO] /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src     -O3   -I/opt/local/include/apr-1  -D_LARGEFILE64_SOURCE -I/opt/java/include -I/opt/java/include/solaris -c -o src/ssl.lo src/ssl.c
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -I/opt/local/include/apr-1 -D_LARGEFILE64_SOURCE -I/opt/java/include -I/opt/java/include/solaris -c src/ssl.c  -fPIC -DPIC -o src/.libs/ssl.o
[INFO] src/ssl.c:1825:2: error: #error OpenSSL is required!
[INFO] src/ssl.c: In function 'Java_org_apache_tomcat_jni_SSL_getErrorString':
[INFO] src/ssl.c:2128:3: error: 'ssl' undeclared (first use in this function)
[INFO] src/ssl.c:2128:3: note: each undeclared identifier is reported only once for each function it appears in
[INFO] make: *** [src/ssl.lo] Error 1
[INFO] Makefile:548: recipe for target 'src/ssl.lo' failed
```

**Comment by normanmaurer** [comment]
@timboudreau maybe you can just set LDFLAGS and CPPFLAGS. 

For example on OSX this is how to make it work:

```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```

**Comment by timboudreau** [comment]
Sigh.  Nope.
```
CPPFLAGS=-I/opt/local/include/openssl/
LDFLAGS=-L/opt/local/lib/
```

does `-I/opt/local/include/openssl/` get it included as an argument to gcc, but same failure as before :-(

**Comment by normanmaurer** [comment]
I think it should now be possible to at least build the static versions. Let me close this

**Comment by timboudreau** [comment]
Well, the various components of netty-tcnative now fail in possibly fixable ways...

**Comment by timboudreau** [comment]
Some seem to be related to tools such as cmake not being found under
/opt/local, and I need to look at whether that's my $PATH on the Jenkins
server, or if the build hard-codes that stuff.  I just shelled into
Jenkins' workspace and manually built each project.

Others are unavailability of tools (something called "ninja" that I might
have to build for SmartOS).

The Jenkins container that runs everything is very old - updated packages
other than security updates stopped being published in 2014.  Right now,
I'm right in the middle of replacing this server with a much more powerful
one, and have copied all the containers onto it - the next step is
recreating the Jenkins server against a modern OS snapshot.  So some of the
problems may be resolved with newer tooling.  I'll likely have that ready
in a week or two depending how busy I am with other things.

Whenever I get this working, if you guys are interested in publishing
'sunos'-classifier packages so the native stuff can be run on
Solaris/SmartOS, I'd be happy to find a way to provide that, or hook you
guys up with a SmartOS jenkins slave you could manage or something.  I know
I'm a dinosaur for running this stuff (SmartOS now can emulate the Linux
kernel so you can just use the Linux version of things), but it's good not
to have a Linux monoculture :-)
