### ISSUE TITLE
Add the binding for SSL_CIPHER_get_version() and other related OpenSSL API

### ISSUE THREAD

**Issue by trustin** [netty/netty-tcnative#22]
https://github.com/netty/netty/commit/2056aed50de35e883a179d7b216c738eecad3251#diff-6ba8edb6d8a5a127eba9cf97911c6f14R664

Currently, there's no way to get the detailed information about a cipher suite.

**Comment by normanmaurer** [comment]
I think we can close this for now. Please reopen if you still think we need it
