### ISSUE TITLE
Linux distros phasing out OpenSSL builds with SSL support

### ISSUE THREAD

**Issue by rkapsi** [netty/netty-tcnative#223]
It seems Linux distros are phasing out OpenSSL builds with SSL support and netty-tcnative is no longer working with it. In my case its on Arch Linux. I haven't looked yet but I think we need a build option for netty-tcnative to build without SSL support (i.e. TLS only).

netty-tcnative: 1.1.33.Fork26

```
$ uname -a
Linux ardverk 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

```
/usr/lib/jvm/java-8-openjdk/bin/java: relocation error: /tmp/libnetty-tcnative8473771249230240328.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
```

**Comment by normanmaurer** [comment]
@rkapsi interesting never saw this before. Let me check over the next days.

**Comment by rkapsi** [comment]
It's possibly some other issue that manifests in a misleading (?) error. I was on Kernel 4.8 and OpenSSL 1.0.2j and there hadn't been any changes. And indeed, openssl itself didn't say anything about SSLv3 not being available.

```
openssl ciphers -v SSLv3
<many ciphers>
```

I just upgraded to Kernel 4.9 and OpenSSL 1.0.2k and the problem persisted with 1.1.33.Fork26. I then went ahead and built my own tcnative (Fork27-SNAP) and that works fine.

**Comment by Scottmitch** [comment]
@rkapsi - IIRC I have compiled my own OpenSSL (1.0.2.h) with config options only building >= TLS1 and I was able to link successfully (even to with versions of netty-tcnative). However I needed to include my own `openssl.ld` file to ensure linking went smoothly. See https://gist.github.com/Scottmitch/71a89d98b3af272aab6ae6bfed122c5a#gistcomment-1851752.

**Comment by rkapsi** [comment]
@normanmaurer OK, I think I got to the bottom of the mystery. Kind of.

This [blog post](https://johnlane.ie/openssl-and-the-rails-breaking-arch-upgrade.html) gave me the clue.

Arch Linux (my distro) is as of `openssl-1.0.2.g` (March 1, 2016) no longer building with SSLv3 support and `openssl-1.0.2.f` (January 28, 2016) is the last version that works. I can repro by switching between these two versions or using any of the newer versions.

But! I've always been on the latest version of openssl and I should have tripped over this a long time ago. So something else has changed too. Something in the way how libs get initialized and now it's crossing paths with SSLv3 that is not present. I don't know.

Building my own tcnative works too.

**Comment by normanmaurer** [comment]
@rkapsi any idea what we should do with this one ?

**Comment by normanmaurer** [comment]
I think I will just close this for now... @rkapsi if you have more infos please reopen
