### ISSUE TITLE
No openssl/libressl static build on maven central

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#226]
Is there a special reason why netty-tcnative-openssl-static and netty-tcnative-libressl-static builds are not published to maven central? (according to http://netty.io/wiki/forked-tomcat-native.html)

**Comment by normanmaurer** [comment]
@floragunncom yes, we not want to be responsible doing a new release each time a new libressl / OpenSSL version is out. At least not yet

**Comment by floragunncom** [comment]
But why you have one for boringssl?

**Comment by normanmaurer** [comment]
Because we have people of google working on netty-tcnative and they signed up for it

**Comment by floragunncom** [comment]
thx
