### ISSUE TITLE
Detect correct JNI library at runtime instead of build time

### ISSUE THREAD

**Issue by cconroy** [netty/netty-tcnative#24]
Rather than try to detect the OS at build time to determine which JNI library to place in META-INF/native, it would be better to package all of them and then let the NativeResourceLoader detect the OS/arch at runtime in order to load the appropriate library.

Detecting at build time is problematic because the build machine may not share the same OS/arch as the production environment. Also, this allows one artifact to be shared across multiple architectures.

What do you think?

**Comment by normanmaurer** [comment]
@cconroy so just to be sure I understand it right... you propose to build all of them, package them together in the jar (and so just produce one jar). Right ?

**Comment by cconroy** [comment]
@normanmaurer exactly. If that sounds good to you, I can try to spin a patch.

**Comment by normanmaurer** [comment]
@cconroy I think this sounds great! I'm just not sure how we could package this stuff correctly while mvn release:perform. As we would need to compile on different platforms before we could build the jar. Any idea?

**Comment by cconroy** [comment]
I figure trying to wrangle cross compilation is not worth the effort / wouldn't work for all platforms.

We could make a separate artifact for each native library. The build machines for those artifacts would need to match their target. 

Then, netty-tcnative would depend on all of those native artifacts to package them all up.

**Comment by normanmaurer** [comment]
@cconroy so you mean we would have some kind of an "uber-jar" that depends on all of the different jars (for different platforms etc) and so pull everything in ?

**Comment by cconroy** [comment]
@normanmaurer yep!

my plan is: the io.netty:netty-tcnative artifact will depend on the arch-specific artifacts. We can drop all native libs into META-INF/native and then update the native resource loader to examine the platform at runtime and pull in the right library.

**Comment by trustin** [comment]
Even if you have built your application on a different platform than your production platform, your application built on a non-production platform should run without a problem on a production platform.

You can just use the netty-tcnative JAR file with the proper classifier as the production dependency, and your problem is gone.

If I understood how your application is deployed, I could have understood your proposal better. Could you elaborate so we learn why it is worth changing how we distribute our native libraries?

**Comment by cconroy** [comment]
@trustin the use case here is that I'd like to share the same artifact across multiple platforms. we have a mix of architectures that might build an artifact and it then might run on yet a different mix of platforms. For example, a developer might want to build an artifact locally to debug (e.g. on OSX), but then also deploy the same artifact to a staging machine in a datacenter (linux).

without such a change I would need to either 
- bundle all of them in a custom/forked way
- disable the openssl codepaths in my application (especially problematic since the java implementation does not have feature parity)


The only downside I see is a slightly larger jar, but this means I can run the same java artifact on osx, linux, etc..

**Comment by trustin** [comment]
Thanks, @cconroy. Now I see your point. It seems like you want to build the final image for heterogeneous production environments, and you want Netty to decide which .so/.dll/.dynlib to use in runtime instead of letting your launch script choose the right dependency. (i.e. runtime vs launchtime)

Here's my idea:

- Move the location of the native library file from `META-INF/native` to `META-INF/native/${os.classifier}`, so that `NativeLibraryLoader` can discover the right native library even if a user added multiple `netty-tcnative` JARs with different classifiers to the class path.
- For backward compatibility, `NativeLibraryLoader` looks into `META-INF/native` directory when `META-INF/native/${os.classifier}` does not contain the right native library.
- We retain the use of artifact classifiers. A user can choose to:
   - put the only one netty-tcnative JAR with the correct OS classifier into the class path, or
   - put multiple netty-tcnative JARs with various OS classifiers into the class path.

WDYT?

**Comment by cconroy** [comment]
@trustin yeah that should satisfy my use case. 

I don't think we want multiple netty-tcnative JARs as-is though: that will end up with all the class files being duplicated.

**Comment by trustin** [comment]
@cconroy Sorry for coming back late.  Yeah, there will be duplicate class files, but I think it doesn't matter really and will be even useful in some situations.  Would you be interested in sending a pull request for this?

**Comment by cconroy** [comment]
@trustin I'm curious how would duplicate class files be useful? The classloader will only load the first one in the classpath. 

I tried to split up the jars yesterday but hit some trouble with how the native source is currently being attached. I'll see if I can make it work, but ultimately I may just end up having duplicate classes for expediency...

**Comment by trustin** [comment]
@cconroy A user can choose to depend only on a JAR that's specific to a certain platform. i.e. more choices to users.

**Comment by Scottmitch** [comment]
Here is some additional reference from @slandelle 

> Here's an example of [how it's being done in lz4-java](https://github.com/jpountz/lz4-java/blob/master/src/java/net/jpountz/util/Native.java#L81-L99).

**Comment by slandelle** [comment]
@normanmaurer @Scottmitch Would you be fine with a PR that would introduce a System prop to tell `OpenSsl` to ask `NativeLibraryLoader` to load from a subdirectory instead of directly in `META-INF/native/`?

**Comment by slandelle** [comment]
ping

**Comment by normanmaurer** [comment]
@Scottmitch sure... what would be the benefit ? (and sorry for the delay)

**Comment by slandelle** [comment]
Hi @normanmaurer 

Some of my users won't be able to properly set up maven/gradle/sbt/whatever so they pick the proper classifier, assuming they even know what a classifier is... So I'm being realistic and would really like to be able to provide an all-in-one jar with all the native libs with the ability to automatically pick the proper one at runtime, depending on the OS characteristics.

Regarding such all-in-one jar, correct me if I'm wrong, but the Java code/bytecode is always the same, right? It's just a matter of some maven-archiver plugin stuff.

The tricky thing is on the calling side.

1. `NativeLibraryLoader` that only tries to locate the native libs directly in `META-INF/native`. We could make it search a subfolder instead, based on the OS characteristics.
  * Pros:
    * Consistent behavior when using an all-in-one jar and when using an OS specific one.
    * No change required on the `NativeLibraryLoader` callers, it takes cares of everything.
  * Cons:
    * You have to adapt all the OS specific jars so they ship the native libs in different subdirectories.
2. Make `NativeLibraryLoader` take a parameter to tell it where the native jars are, probably an overloaded `load` method.
  * Pros:
    * No impact on existing tcnative and native-transport-epoll jars
  * Cons:
    * Responsibility of selecting the proper location is pushed on the callers, such as `OpenSsl`, which is static, so the only way to configure it is with System props.
3. Make `NativeLibraryLoader` an API, and let users pass a different implementation than the default: System prop with the class name to be loaded by reflection, or a registry like `InternalLoggerFactory` or `ResourceLeakDetector`:
  * Pros:
    * Don't limit users
  * Cons:
    * Users will fork to build their own all-in-one jars

WDYT?

**Comment by cconroy** [comment]
@slandelle see also https://github.com/netty/netty/pull/3502 which is a companion PR to this change so that NativeLibraryLoader can load the correct library based on the OS. It was recently closed without comment but my understanding was that Trustin and Norman were on board with these changes and we had just been waiting on some internal tools in various places to be updated...

**Comment by slandelle** [comment]
@cconroy Yeah, I know. But I was concerned because it got closed. :)

**Comment by normanmaurer** [comment]
I think we can close this now as we have the "uberjar".
