### ISSUE TITLE
investigate enabling enable-ec_nistp_64_gcc_128 for our static builds

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#243]
https://wiki.openssl.org/index.php/Compilation_and_Installation

>enable-ec_nistp_64_gcc_128
Use on little endian platforms when GCC supports __uint128_t. ECDH is about 2 to 4 times faster. Not enabled by default because Configure can't determine it. Enable it if your compiler defines __SIZEOF_INT128__, the CPU is little endian and it tolerates unaligned data access.

**Comment by injust** [comment]
`enable-ec_nistp_64_gcc_128` is no longer useful, as the optimization has been replaced by faster assembly code (on x86-64 and armv8).

**Comment by normanmaurer** [comment]
Cool do you have a link to the commit by any chance ?

**Comment by injust** [comment]
@normanmaurer The assembly optimizations are in [openssl/crypto/ec/asm](https://github.com/openssl/openssl/tree/master/crypto/ec/asm).
Initial commit was back in 2014, see https://github.com/openssl/openssl/commit/4d3fa06fce52682bfbc503c7ded2d0289e3f8cde.

**Comment by normanmaurer** [comment]
@injust thanks a lot

**Comment by witaly-iwanow** [comment]
> `enable-ec_nistp_64_gcc_128` is no longer useful, as the optimization has been replaced by faster assembly code.

This is not true, there's a big difference when you run EC performance tests with/without enable-ec
