### ISSUE TITLE
Update to openssl 1.1.1 with TLS 1.3

### ISSUE THREAD

**Issue by snazy** [netty/netty-tcnative#256]
OpenSSL 1.1.1 is about to add support for TLS 1.3 according to this [blog post](https://www.openssl.org/blog/blog/2016/10/24/f2f-roadmap/).
Would be great to have TLS 1.3 in Netty via OpenSSL!

**Comment by nename0** [comment]
Related to #249 , as 1.1.1 will be have equal api as 1.1.0:

> The only thing missing was being able to commit to a delivery date, so that downstream consumers (such as Akamai) could dependably plan their own TLS 1.3 rollouts.  Because of our sponsorship, OpenSSL will deliver TLS 1.3 on April 5, in a version compatible with 1.1.0.  Akamai will begin incorporating this update into its systems soon thereafter.
**If you have  applications that use OpenSSL, start migrating to OpenSSL 1.1.0 now. Then, when the version supporting TLS 1.3 is available, you can just "drop it in."**  If you don't have applications to migrate, then follow along on the GitHub repository; same basic interop is already working.  Let the countdown to global TLS 1.3 enablement begin!

 [Source](https://blogs.akamai.com/2017/01/tls-13-ftw.html)

**Comment by floragunncom** [comment]
Now it seems the final openssl 1.1.1 is imminent (after 2 pre-releases) and i think it would be great if we get TLS 1.3 support with netty any time soon.

**Comment by normanmaurer** [comment]
Related to https://github.com/netty/netty-tcnative/issues/345

**Comment by hc-codersatlas** [comment]
Is it as simple as just updating OpenSSL or changes need to be made to support TLS 1.3?

**Comment by normanmaurer** [comment]
@hc-codersatlas sadly not ... But its on my to do list

**Comment by floragunncom** [comment]
OpenSSL 1.1.1 is now finally released

**Comment by normanmaurer** [comment]
Will look into it.

**Comment by normanmaurer** [comment]
@snazy @hc-codersatlas @floragunncom @nename0 just for the record I have everything working here locally and just need to do some more cleanup etc but will provide some PRs within the next 1-2 weeks.
