### ISSUE TITLE
2.0.1.Final built with TCN_OCSP_NOT_SUPPORTED ?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty-tcnative#265]
When I try to use the netty-tcnative 2.0.1.Final artifact from maven central I'm getting this Exception when trying to enable OCSP on the context. As if it was built with `TCN_OCSP_NOT_SUPPORTED`.

```java
java.lang.Exception: OCSP stapling is not supported
	at io.netty.internal.tcnative.SSLContext.enableOcsp(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:360)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:219)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:775)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446)
```

https://github.com/netty/netty-tcnative/blob/master/openssl-dynamic/src/main/c/sslcontext.c#L1615

https://github.com/netty/netty-tcnative/blob/master/openssl-dynamic/src/main/c/ssl_private.h#L166

**Comment by normanmaurer** [comment]
Which OS and which artifact?

**Comment by rkapsi** [comment]
```
$ uname -a
Linux ardverk 4.10.9-1-ARCH #1 SMP PREEMPT Sat Apr 8 12:39:59 CEST 2017 x86_64 GNU/Linux
```

```
compile "io.netty:netty-tcnative:2.0.1.Final:linux-x86_64@jar"
```

**Comment by Scottmitch** [comment]
@normanmaurer - IIRC you build with OpenSSL 1.0.1 when you release? We have discussed building with 1.0.2 and using weak linking techniques to accommodate older versions at link time. 

https://github.com/netty/netty-tcnative/blob/master/openssl-dynamic/src/main/c/ssl_private.h#L166
```
// OCSP stapling should be present in OpenSSL as of version 1.0.0 but we've
// only tested 1.0.2 are therefore limiting us to that version or newer.
#if OPENSSL_VERSION_NUMBER < 0x10002000L
#define TCN_OCSP_NOT_SUPPORTED
#endif
```

So we can either:
1. update how we release (may require code changes and testing)
2. relax this version check for OCSP (requires small code change and testing)

**Comment by rkapsi** [comment]
@Scottmitch nice, I didn't realize the dynamic lib is linked against 1.0.1 and thought they all target the same version what's configured in the POM.

I think No. 2 makes sense in this context unless you want to make a statement and shoot down 1.0.1 for the greater good (which is cool too).

**Comment by normanmaurer** [comment]
@rkapsi @Scottmitch 2) makes sense. 

@rkapsi want to do a pr ?

**Comment by rkapsi** [comment]
on it

**Comment by Scottmitch** [comment]
> thought they all target the same version what's configured in the POM.

For the static libraries the version should match, but for the libraries which require dynamic linking they are compiled against whatever is on the host machine. IIRC we currently only release a statically built BoringSSL. So you should be able to use this artifact as a temporary work around (if you are OK with using BoringSSL).
