### ISSUE TITLE
2.0.0.Final openssl dynamic build with 1.0.1

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#269]
Looks like 2.0.0.Final openssl dynamic (non-fedora) was build somehow against 1.0.1 openssl because i get the following error though i have 1.0.2 installed (reported by `OpenSsl.version()`)

<pre>
java.lang.Exception: hostname verification requires OpenSSL 1.0.2+
	at io.netty.internal.tcnative.SSL.setHostNameValidation(Native Method)
	at io.netty.internal.tcnative.HostnameVerifierTest.testVerifierAvailable(HostnameVerifierTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       ...
</pre>

Maybe it would help to guard this by a Unittest like (if its not intentional)

<pre>
public class HostnameVerifierTest extends AbstractNativeTest {

    @Test
    public void testVerifierAvailable() throws Exception {
        long sslCtx = 0;
        long ssl = 0;

        try {
            //System.out.println(Integer.toHexString(SSL.version()));
            //System.out.println(SSL.versionString());
            sslCtx = SSLContext.make(SSL.SSL_PROTOCOL_ALL, SSL.SSL_MODE_SERVER);
            SSLContext.setCipherSuite(sslCtx, "ALL");
            ssl = SSL.newSSL(sslCtx, true);
            SSL.setHostNameValidation(ssl, 0, "netty.org");
        } catch (Throwable t) {
            t.printStackTrace();
            Assert.fail(t.getMessage());
        } finally {
            SSL.freeSSL(ssl);
            SSLContext.free(sslCtx);
        }
    }
}
</pre>

**Comment by Scottmitch** [comment]
Yes the release process currently compiles against 1.0.1 and this is an issue. See https://github.com/netty/netty-tcnative/issues/265#issuecomment-297593386. Temporary work around is to re-build tcnative with the desired version of OpenSSL, or use the static BoringSSL library in maven central.

**Comment by Scottmitch** [comment]
Related: https://github.com/netty/netty-tcnative/issues/273

**Comment by bm3780** [comment]
Any idea when this "weak linking" option might happen?  I'm unable to use dynamically linked version with Openssl 1.0.2.  [This line](https://github.com/reactor/reactor-netty/blob/519b2b33e8bec8fcf917917158d864f8f04a98ea/src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java#L96) in Reactor gives me a `hostname verification requires OpenSSL 1.0.2+` error, so I'm reverting to JDK provider for now.  Will also look into BoringSSL as alternative.

```java
  SSLParameters sslParameters = sslEngine.getSSLParameters();
  sslParameters.setEndpointIdentificationAlgorithm("HTTPS");
  sslEngine.setSSLParameters(sslParameters);  //results in error
```

**Comment by normanmaurer** [comment]
@floragunncom @bm3780 could any of you verify this PR: https://github.com/netty/netty-tcnative/pull/365 ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-tcnative/pull/365
