### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#271]
Ist there a matrix (or other kind of documentation) where i can see which tcnative version is compatible with which netty version?

**Comment by Scottmitch** [comment]
Duplicate of https://github.com/netty/netty/issues/4808. Currently there is nothing but lets continue the discussion there. We have considered moving the netty-tcnative project into the netty project which would alleviate version mismatch ambiguities, but have not fully investigated the feasibility of this approach yet.
