### ISSUE TITLE
Use weak linking to enable 1.0.2 features for dynamically linked released artifacts

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#273]
Currently we compile the dynamically linked artifacts against OpenSSL 1.0.1, and we have compile time flags which limit the available feature set. We should consider building against OpenSSL 1.0.2 and/or using weak linking so that folks that link with a newer version of OpenSSL at runtime can use these features supported by the newer version.

**Comment by Scottmitch** [comment]
Related:
https://github.com/netty/netty-tcnative/issues/265#issuecomment-297593386
https://github.com/netty/netty-tcnative/issues/269

**Comment by sebtomba** [comment]
Will you include this in release `2.0.9`?

**Comment by normanmaurer** [comment]
No idea yet if I have time for this ... contributions welcome

**Comment by normanmaurer** [comment]
https://github.com/netty/netty-tcnative/pull/368 should be last bit needed to close this 🎉
