### ISSUE TITLE
Build issue on 32-bit Linux

### ISSUE THREAD

**Issue by trustin** [netty/netty-tcnative#29]
From @junjiemars:

> @trustin I resolved the issue: io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 can not be found on 32-bit Linux,
1) git clone [netty-tcnative.git](git@github.com:netty/netty-tcnative.git)
2) run ```mvn -X compile```, it will be failed on 32-bit Linux
3) found the Makefile under the ./target/native-build, insert ```-DLARGEFILE64_SOURCE``` into ```CFLAGS``` section nearly 262 line
4) comment 2 ```<forceAutogen .../>``` and ```<forceConfigure .../>``` sections in pom.xml
5) run ```mvn -X install``` to install io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 into local repository
6) now, io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 can be found by maven, done.

Seems like the user experienced a build problem when building on 32-bit Linux

**Comment by normanmaurer** [comment]
@trustin will check.. Thanks

**Comment by normanmaurer** [comment]
working on it...

**Comment by junjiemars** [comment]
it's great

**Comment by normanmaurer** [comment]
Fixed by 0f8bd6d, ee61f3f and de2d208
