### ISSUE TITLE
Getting `NPN_AND_ALPN` support error for netty-tcnative with openssl-static

### ISSUE THREAD

**Issue by dineshappavoo** [netty/netty-tcnative#303]
I built the openssl-static by following this wiki http://netty.io/wiki/forked-tomcat-native.html#building-on-mac-os-x . I am getting `NPN_AND_ALPN` protocol error when I send a http2 request for this server.

`channel: java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol`

Could someone help me with this?

**Comment by Scottmitch** [comment]
> channel: java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol

This means you are using the JDK's SslProvider ... which as indicated doesn't support this mode. I would expect OPENSSL to be used by default it you are not explicitly specifying an SslProvider and we are able to load the JNI libraries. What does `OpenSsl.unavailabilityCause()` return, and how do you configure your `SslContextBuilder`?

**Comment by dineshappavoo** [comment]
It looks like my openssl-static jar wasn't fetched properly that's the reason if falls back to JDK's SSLProvider. That was an error in our application. 

Thanks for helping on this. Resolving.
