### ISSUE TITLE
Netty OpenSsl.isAvailable() check doesn't handle lib loading issue on 32bit JVM

### ISSUE THREAD

**Issue by doom369** [netty/netty-tcnative#307]
Details are here : https://github.com/netty/netty/issues/7150#issuecomment-332542876

Brief summary:

Right now `tcnative` library has name `libnetty_tcnative.so` and this name doesn't include OS classifier that prevents netty from loading this library if system architecture doesn't match with packed version. For example, epoll native library name look like this `libnetty_transport_native_epoll_x86_64.so`.

**Comment by normanmaurer** [comment]
@doom369 PTAL https://github.com/netty/netty-tcnative/pull/315
