### ISSUE TITLE
Unable to build tcnative 2.0.6.Final against openssl 1.1.0f (static)

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#313]
Static build of tcnative 2.0.6.Final against openssl 1.1.0f fails (Ubuntu):
<pre>
...
[INFO]  /bin/bash ./config.status
[INFO] config.status: creating Makefile
[INFO] config.status: creating src/config.h
[INFO] config.status: src/config.h is unchanged
[INFO] config.status: executing libtool commands
[INFO] /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src     -O3 -Werror -fno-omit-frame-pointer -Wunused-variable -DHAVE_OPENSSL -I/output/gen/netty-tcnative/openssl-static/target/ssl/include  -I/output/gen/netty-tcnative/openssl-static/target/apr/include/apr-1  -D_LARGEFILE64_SOURCE -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -c -o src/ssl.lo src/ssl.c
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -Werror -fno-omit-frame-pointer -Wunused-variable -DHAVE_OPENSSL -I/output/gen/netty-tcnative/openssl-static/target/ssl/include -I/output/gen/netty-tcnative/openssl-static/target/apr/include/apr-1 -D_LARGEFILE64_SOURCE -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -c src/ssl.c  -fPIC -DPIC -o src/.libs/ssl.o
[INFO] src/ssl.c: In function 'netty_internal_tcnative_SSL_setState':
[INFO] src/ssl.c:1558:5: error: implicit declaration of function 'SSL_set_state' [-Werror=implicit-function-declaration]
[INFO]      SSL_set_state(ssl_, state);
[INFO]      ^
[INFO] cc1: all warnings being treated as errors
[INFO] Makefile:508: recipe for target 'src/ssl.lo' failed
[INFO] make: *** [src/ssl.lo] Error 1
[INFO] rc: 2
...
</pre>

Full log is here: https://gist.githubusercontent.com/floragunncom/0f8659863a1e7ebf6db1f3d03beb09b8/raw/4a9b95534e606129feec164c5967a2ee198900b4/build.log

**Comment by Scottmitch** [comment]
Duplicate:

https://github.com/netty/netty-tcnative/issues/263
