### ISSUE TITLE
netty-tcnative-parent-2.0.7.Final openssl-static build issue

### ISSUE THREAD

**Issue by dineshappavoo** [netty/netty-tcnative#321]
I am trying to run openssl-static with netty-tcnative-parent-2.0.7.Final release. I am getting the following error while opening `netty-tcnative/openssl-static/target/old/1.0.2/openssl-1.0.2l.tar.gz`

```

     [exec] /usr/bin/install -c -m 755 apr-config.out /Users/dinesh/Documents/docs/ssl/openssl/version-2-0-7/netty-tcnative/openssl-static/target/apr/bin/apr-1-config
[INFO] Executed tasks
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (build-openssl) @ netty-tcnative-openssl-static ---
[INFO] Executing tasks

main:
      [ftp] getting files
      [ftp] transferring old/1.0.2/openssl-1.0.2l.tar.gz to /Users/dinesh/Documents/docs/ssl/openssl/version-2-0-7/netty-tcnative/openssl-static/target/old/1.0.2/openssl-1.0.2l.tar.gz
      [ftp] 1 files retrieved
     [exec] tar: Error opening archive: Failed to open 'openssl-1.0.2l.tar.gz'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.966 s
[INFO] Finished at: 2017-11-06T15:14:24-08:00
[INFO] Final Memory: 14M/256M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-openssl) on project netty-tcnative-openssl-static: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec resolveexecutable="true" failonerror="true" dir="/Users/dinesh/Documents/docs/ssl/openssl/version-2-0-7/netty-tcnative/openssl-static/target/" executable="tar">... @ 9:171 in /Users/dinesh/Documents/docs/ssl/openssl/version-2-0-7/netty-tcnative/openssl-static/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Do I need to make any changes to fix this? I am following this [wiki](http://netty.io/wiki/forked-tomcat-native.html#building-on-mac-os-x)

Could someone help me with this?

**Comment by nhnFreespirit** [comment]
This only seems to be an issue when building from the 2.0.7 tag, not when building from latest master (which includes the bump to openssl 1.0.2m)

**Comment by normanmaurer** [comment]
We should adjust the build so we can also build old tags.

**Comment by normanmaurer** [comment]
Will be fixed by https://github.com/netty/netty-tcnative/pull/322

**Comment by normanmaurer** [comment]
Fixed in https://github.com/netty/netty-tcnative/pull/322

**Comment by meghalidhoble** [comment]
I am getting similar problem with latest source code as well. I am trying to build it for my platform on Ubuntu 16.04 with ppc64le architecture and the gradle build is failing during compilation of openssl-static. The error I see is as below: 
`
###       _[ftp] getting files
      [ftp] transferring old/1.0.2/openssl-1.0.2n.tar.gz to /home/test/netty-tcnative/openssl-static/target/old/1.0.2/openssl-1.0.2n.tar.gz
      [ftp] try #1: IO error (old/1.0.2/openssl-1.0.2n.tar.gz), number of maximum retries reached (0), giving up
[INFO] ------------------------------------------------------------------------
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [  4.244 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. SUCCESS [ 28.803 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. FAILURE [01:02 min]
[INFO] Netty/TomcatNative [BoringSSL - Static] ............ SKIPPED
[INFO] Netty/TomcatNative [LibreSSL - Static] ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
[INFO] Finished at: 2018-04-09T10:21:28+00:00
[INFO] Final Memory: 22M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-openssl) on project netty-tcnative-openssl-static: An Ant BuildException has nsfer: org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
[ERROR] around Ant part ...<ftp server="ftp.openssl.org" password="anonymous" remotedir="source" action="get" userid="anonymous" passive="yes" verbose="yes">... @ 5:133/openssl-static/target/antrun/build-main.xml
[ERROR] -> [Help 1]_ `

Am I missing any specific configurations? Any suggestions/pointers would be really appreciated.
Also I am not sure if I should open a new issue for this, or reopen this one. Please suggest. 
Thanks, 
Meghali Dhoble
