### ISSUE TITLE
netty-tcnative library file name error leads java.lang.IllegalArgumentException: Failed to load any of the given libraries

### ISSUE THREAD

**Issue by chzhong** [netty/netty-tcnative#323]
Recent builds (2.0.4, 2.0.5 and 2.0.6) leads an native library load error from maven repo.

Trace:

>  java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]
> 	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:178) ~[netty-common-4.1.11.Final.jar:4.1.11.Final]
> 	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:403) ~[netty-handler-4.1.11.Final.jar:4.1.11.Final]
> 	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:85) ~[netty-handler-4.1.11.Final.jar:4.1.11.Final]

Discovered reason:
2.0.4.Final: The native library is not packaged in the deployed jar.
2.0.5 & 2.0.6: The native library used a different name as netty-handler-4.1.x.

Accroding to codes is netty-handler-4.1.x: 

> libNames.add("netty-tcnative-" + os + '-' + arch);
> if (LINUX.equalsIgnoreCase(os)) {
>     // Fedora SSL lib so naming (libssl.so.10 vs libssl.so.1.0.0)..
>     libNames.add("netty-tcnative-" + os + '-' + arch + "-fedora");
> }

The library name should be something like **netty-tcnative-linux-x86_64** (words are connected with hyphens), but the library packaged in the netty-tcnative is: **netty_tcnative_linux_x86_64** (words are connected with underscores).

**Comment by normanmaurer** [comment]
@chzhong you need to update your netty version as well which uses `_`

**Comment by chzhong** [comment]
Thanks normanmaurer.
I've resolved this issue by upgrading netty version.
