### ISSUE TITLE
 error during FTP transfer 

### ISSUE THREAD

**Issue by nasica88** [netty/netty-tcnative#327]
I encountered error while doing 'mvn clean install'.   The error says FTP connection was reset.

I find that openssl-static/target/antrun/build-main.xml contains wrong name of the file to be downloaded.  It contains 7~8 entries of openssl-1.0.2m.tar.gz, but the actual site of ftp.openssl.org/source contains none with that name, but openssl-1.0.2n.tar.gz  (n, not m).

  <ftp server="ftp.openssl.org" password="anonymous" remotedir="source" action="get" userid="anonymous" passive="yes" verbose="yes">
    <fileset dir="/nvme/netty-tcnative/openssl-static/target">
      <include name="**/openssl-1.0.2m.tar.gz"/>   

I edited this file of openssl-static/target/antrun/build-main.xml from m to n, but when I ran mvn clean install, it resulted in the same error.  It seems this openssl-static/target/antrun/build-main.xml is downloaded or generated on the run, so my correction to it does not hold.   

Any suggestions ?   

Below is the log.

# mvn clean install
...
[INFO] Executed tasks
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (build-openssl) @ netty-tcnative-openssl-static ---
[INFO] Executing tasks

main:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [  4.220 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. SUCCESS [ 21.032 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. FAILURE [01:00 min]
[INFO] Netty/TomcatNative [BoringSSL - Static] ............ SKIPPED
[INFO] Netty/TomcatNative [LibreSSL - Static] ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:26 min
[INFO] Finished at: 2018-01-12T09:23:12+09:00
[INFO] Final Memory: 21M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-openssl) on project netty-tcnative-openssl-static: An Ant BuildException has occured: error during FTP transfer: java.net.SocketException: Connection reset
[ERROR] around Ant part ...<ftp server="ftp.openssl.org" password="anonymous" remotedir="source" action="get" userid="anonymous" passive="yes" verbose="yes">... @ 5:133 in /nvme/netty-tcnative/openssl-static/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-tcnative-openssl-static

**Comment by normanmaurer** [comment]
Which branch you try to build?

**Comment by nasica88** [comment]
@normanmaurer

I tried netty-tcnative-parent-2.0.5.Final, netty-tcnative-parent-2.0.6.Final, and netty-tcnative-parent-2.0.7.Final.  All had similar issues.

By the way, I found a work-around by editing openssl-static/pom.xml as below.

                   
                        <include name="**/openssl-1.0.2.n.tar.gz" />

**Comment by normanmaurer** [comment]
I think it is fixed when building master
