### ISSUE TITLE
Failed to load any of the given libraries: [netty-tcnative-windows-x86_64, netty-tcnative]

### ISSUE THREAD

**Issue by adprocas** [netty/netty-tcnative#328]
Hello,

I'm getting the following error when trying to use **2.0.7.Final**

> 
> **type** Exception report
> 
> **message** Internal Server Error
> 
> **description** The server encountered an internal error that prevented it from fulfilling this request.
> 
> **exception**
> javax.servlet.ServletException: Filter execution threw an exception
> 
> **root cause**
> java.lang.UnsatisfiedLinkError: failed to load the required native library
> 
> **root cause**
> java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-windows-x86_64, netty-tcnative]
> 

I'm on **Windows 7 64-bit**.

Here's my netty-tcnative dependency:

`<dependency org="io.netty" name="netty-tcnative-boringssl-static" rev="1.1.33.Fork26" conf="core->default" />`

I also have the following related dependencies (I probably need to clean a few of these up):

```
<dependency org="com.coreos" name="jetcd-core" rev="0.0.1" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-core -->
        <dependency org="io.grpc" name="grpc-core" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-netty -->
        <dependency org="io.grpc" name="grpc-netty" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-protobuf -->
        <dependency org="io.grpc" name="grpc-protobuf" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-stub -->
        <dependency org="io.grpc" name="grpc-stub" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
        <dependency org="com.google.guava" name="guava" rev="19.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305 -->
        <dependency org="com.google.code.findbugs" name="jsr305" rev="3.0.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.errorprone/error_prone_annotations -->
        <dependency org="com.google.errorprone" name="error_prone_annotations" rev="2.0.19" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.instrumentation/instrumentation-api -->
        <dependency org="com.google.instrumentation" name="instrumentation-api" rev="0.4.3" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-context -->
        <dependency org="io.grpc" name="grpc-context" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.netty/netty-handler-proxy -->
        <dependency org="io.netty" name="netty-handler-proxy" rev="4.1.12.Final" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.netty/netty-codec-http2 -->
        <dependency org="io.netty" name="netty-codec-http2" rev="4.1.12.Final" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.netty/netty-all -->
        <dependency org="io.netty" name="netty-all" rev="4.1.12.Final" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util -->
        <dependency org="com.google.protobuf" name="protobuf-java-util" rev="3.3.1" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java -->
        <dependency org="com.google.protobuf" name="protobuf-java" rev="3.3.1" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos -->
        <dependency org="com.google.api.grpc" name="proto-google-common-protos" rev="0.1.9" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-protobuf-lite -->
        <dependency org="io.grpc" name="grpc-protobuf-lite" rev="1.5.0" conf="core->default"/>
        <!-- https://mvnrepository.com/artifact/com.google.protobuf/protobuf-lite -->
        <dependency org="com.google.protobuf" name="protobuf-lite" rev="3.0.1" conf="core->default"/>
```

I'm using **Ant** and **Wicket** on Glassfish or Tomcat (locally I switch between the two, and they both throw the same error).

Any ideas?  Is this an issue with the hyphens and underscores still?  When I look in that jar I see the dll named **netty-tcnative-windows-x86_64.dll**, which is inconsistent with the error message above.

**EDIT:** At one point in time the DLL was **netty-tcnative-windows-x86-64.dll**.  This may have been when specifying to only use the Windows stuff or when I was testing an older version of the libarary.  I'll look into that, but the error is still coming up either way.

I've tried a bunch of other options when trying to build this.  I'm mainly trying to use **jetcd-core**, which uses **gRPC**

Thanks for your help!

**Comment by Scottmitch** [comment]
> I'm getting the following error when trying to use 2.0.7.Final
> <dependency org="io.netty" name="netty-tcnative-boringssl-static" rev="1.1.33.Fork26" conf="core->default" />

It looks like you are using Netty `4.1.12` which requires [netty-tcnative 2.0.3](https://github.com/netty/netty/blob/netty-4.1.12.Final/pom.xml#L191). The versions of Netty and netty-tcnative must be kept in sync as the netty-tcnative is treated as an internal package and breaking changes maybe made.

**Comment by Scottmitch** [comment]
Please re-open this issue if correcting the version doesn't resolve this issue.

**Comment by adprocas** [comment]
Thanks @Scottmitch,

I didn't think to look that way for the requirements.  I'm wondering if it might be good to write something up about what versions are required?

**Comment by Scottmitch** [comment]
@adprocas - Agreed the relationship / dependency structure is not documented very well. I would like to pull netty-tcnative into the Netty project since there is such tight coupling and the way it is treated as an internal dependency. In this case it should resolve the versioning conflicts.
