### ISSUE TITLE
Unable to build tcnative 2.0.8 statically against openssl 1.1.0h (on alpine)

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#336]
on alpine:
<pre>
[exec] make -f ./Makefile.shared -e \
     [exec] 	PERL="/usr/bin/perl" SRCDIR=. \
     [exec] 	APPNAME=apps/openssl OBJECTS="apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o" \
     [exec] 	LIBDEPS=' '" -L. -lssl -L. -lcrypto"' -ldl -pthread ' \
     [exec] 	CC='gcc' CFLAGS='-DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_NO_HEARTBEATS -DOPENSSLDIR="\"/output/gen/netty-tcnative/openssl-static/target/ssl\"" -DENGINESDIR="\"/output/gen/netty-tcnative/openssl-static/target/ssl/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -O3 -fno-omit-frame-pointer -fPIC -Wa,--noexecstack ' \
     [exec] 	LDFLAGS='' \
     [exec] 	link_app.
     [exec] make[2]: Entering directory '/output/gen/netty-tcnative/openssl-static/target/openssl-1.1.0h'
     [exec] ( :; LIBDEPS="${LIBDEPS:--L. -lssl -L. -lcrypto -ldl -pthread }"; LDCMD="${LDCMD:-gcc}"; LDFLAGS="${LDFLAGS:--DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_NO_HEARTBEATS -DOPENSSLDIR="\"/output/gen/netty-tcnative/openssl-static/target/ssl\"" -DENGINESDIR="\"/output/gen/netty-tcnative/openssl-static/target/ssl/lib/engines-1.1\"" -Wall -O3 -pthread -m64 -DL_ENDIAN  -O3 -fno-omit-frame-pointer -fPIC -Wa,--noexecstack  }"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; echo LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=apps/openssl} apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o ${LIBDEPS}; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=apps/openssl} apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o ${LIBDEPS} )
     [exec] LD_LIBRARY_PATH=.: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSL_NO_HEARTBEATS -DOPENSSLDIR="/output/gen/netty-tcnative/openssl-static/target/ssl" -DENGINESDIR="/output/gen/netty-tcnative/openssl-static/target/ssl/lib/engines-1.1" -Wall -O3 -pthread -m64 -DL_ENDIAN -O3 -fno-omit-frame-pointer -fPIC -Wa,--noexecstack -o apps/openssl apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o -L. -lssl -L. -lcrypto -ldl -pthread
     [exec] ./libcrypto.a(async_posix.o): In function `ASYNC_is_capable':
     [exec] async_posix.c:(.text+0x22): undefined reference to `getcontext'
     [exec] ./libcrypto.a(async_posix.o): In function `async_fibre_makecontext':
     [exec] async_posix.c:(.text+0x78): undefined reference to `getcontext'
     [exec] async_posix.c:(.text+0xe9): undefined reference to `makecontext'
     [exec] ./libcrypto.a(async.o): In function `async_fibre_swapcontext.constprop.2':
     [exec] async.c:(.text+0x38): undefined reference to `setcontext'
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[2]: *** [Makefile.shared:172: link_app.] Error 1
     [exec] make[1]: *** [Makefile:5801: apps/openssl] Error 2
     [exec] make: *** [Makefile:129: all] Error 2
     [exec] make[2]: Leaving directory '/output/gen/netty-tcnative/openssl-static/target/openssl-1.1.0h'
     [exec] make[1]: Leaving directory '/output/gen/netty-tcnative/openssl-static/target/openssl-1.1.0h'
</pre>

**Comment by normanmaurer** [comment]
We just updated the version of the statically compiled openssl-static module to 1.1.0h and all works here: 

https://github.com/netty/netty-tcnative/commit/e9913cb73d6942964c8bbf00ede6478d8f4050d6

I will close this for now. Please reopen if you still see issues.
