### ISSUE TITLE
Need a binary at maven-central for ppc64le

### ISSUE THREAD

**Issue by meghalidhoble** [netty/netty-tcnative#339]
Hi,
As I was building "cassandra-driver-core" package on my linux machine having ppc64le platform, I faced issues saying the jar is not available at the required location "maven-central".
I went ahead and build netty-tcnative latest-stable release version 2.0.8 on ppc64le architecture and it built fine for me. Then further I also tested placing this locally generated jar at the ~/.m2/repository location and that helped me to get my build for 'cassandra-driver-core' working. 

Hence I would like to request you, to upload the jar for ppc64le, along with other jars at the maven-central repository - https://repo.maven.apache.org/maven2/io/netty/netty-tcnative/2.0.8.Final/netty-tcnative-2.0.8.Final-linux-ppcle_64.jar
I can provide help with setting up the build if required. Please let me know your thoughts on this.

Thanks,
Meghali

**Comment by normanmaurer** [comment]
We have no infrastructure to support this, so I will close this. Sorry

**Comment by meghalidhoble** [comment]
Hi @normanmaurer,
Alternatively I can also provide you help to access the Power infrastructure (a VM Or Jenkins), so as to be able to setup CI. 
You can request access for power infra. here : http://osuosl.org/services/powerdev/request_hosting/ 
Please let me know your thoughts. 
Thanks.
