### ISSUE TITLE
Prepare to be able to link against openssl 1.1.1

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-tcnative#345]
OpenSSL 1.1.1 will be the new LTS release, so we should be able to link against it:

https://www.openssl.org/blog/blog/2018/05/18/new-lts/

**Comment by normanmaurer** [comment]
@carl-mastrangelo @ejona86 @Scottmitch @trustin FYI

**Comment by normanmaurer** [comment]
https://github.com/netty/netty-tcnative/commit/35cd01cdffddb789ca56188a8c2a08dda33d54d8 is related to this

**Comment by floragunncom** [comment]
OpenSSL 1.1.1 is now finally released

**Comment by normanmaurer** [comment]
@floragunncom will look into it the next weeks
