### ISSUE TITLE
What version of boringssl is used for tcnative 2.0.8?

### ISSUE THREAD

**Issue by sophokles73** [netty/netty-tcnative#347]
Hi,

is there any way of determining the commit ID of the upstream boringssl that is used for building the statically linked versions of netty-tcnative-boringssl-static?

Haven't found any hint ...

**Comment by normanmaurer** [comment]
We use the chromium-stable branch which sha is used can be found in the MANIFEST that is included in the jar

**Comment by sophokles73** [comment]
Thanks, found it :+1:
