### ISSUE TITLE
Don't strip libs to make debugging / profiling easier.

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-tcnative#359]
As of today we typically strip our static libs (like boringssl-static). I think this was mainly done in the past to make these smaller. I wonder if we should better not do this as this really makes it hard to debug / profile code once it ends up in a native method call. The only way how to do this atm is to have the user compile his own version and skip striping which I think is problematic as for example the performance problems will not show up directly again on redeployment.

**Comment by normanmaurer** [comment]
@Scottmitch @mosesn @bryce-anderson @ejona86 @carl-mastrangelo I would like to get you opinion here.

**Comment by Scottmitch** [comment]
Assuming there is negligible performance/memory impact this sgtm. If the additional disk consumption becomes a problem in the future:

- folks can always build their own artifact with their desired options
- we can publish both versions (with and without symbols) if demand is high enough

**Comment by mosesn** [comment]
Yeah, seems reasonable to me.  Do we know what the difference in lib size will be?

**Comment by mosesn** [comment]
3MB isn't too big :shipit:

**Comment by bryce-anderson** [comment]
sgtm. 3 MB is a drop in the bucket for the typical JVM app.

**Comment by ejona86** [comment]
I'd prefer for it to remain stripped:
* grpc does use it on clients, clients that may running on some sort of desktop machine (not a server)
* size is a proxy for the amount of code. For example, initially I was quite scared of tcnative when I noticed the large sizes, before I noticed the lack of stripping. Users who aren't aware of strip will likely think tcnative is a bit of a behemoth (3 MB is 6x the size of libssl.so!)
* if you're going to include debug information for Linux, would you include it for OS X and Windows (pdb) as well? Earlier, only Linux had debug information. The uber jar grows quite a bit if you include debug information for all platforms and I think that would discourage the use of the uber jar
* "[split debug info](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html)" is quite common. With split debug you still ship a stripped binary, but you save the debug information in a separate file that can be "installed" separately or be used by developers to symbolize a backtrace. Virtually every Linux distribution uses this method for debug information, as well as ISVs like Firefox and Chrome, and all Visual Studio builds

For the split debug, there's a couple approaches. The simplest option (but a bit incomplete) is to keep the pre-stripped binary available for download somewhere. It has the debug information available and you can run things like addr2line to make sense of things. More commonly people run strip/objcopy --only-keep-debug. See the [man page for strip](https://linux.die.net/man/1/strip). Both of those are best suited in conjunction with --add-gnu-debuglink. Another alternative is to use "build-id", which seems it may be better for our usage. That's described in the gdb documentation linked earlier.

**Comment by carl-mastrangelo** [comment]
Personal preference is for more debug info.  Performance profiling is my main use case (and it's especially useful when asking other people to provide profiling for me to diagnose).  Space and bandwidth are cheap.

**Comment by normanmaurer** [comment]
@ejona86 let me read up on the stuff you linked. At worse we could definitely ship a stripped and an non-stripped version but if possible I would like to keep it simple. I fully agree with @carl-mastrangelo here that we should make it easy to debug, have people build their own version just so they have symbols is a bit too much imho

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty-tcnative/pull/363.... The jar is only slightly larger (~100k) while provide everything that is needed.
