### ISSUE TITLE
tcnative compatibility

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#366]
* Is netty 4.1.13 compatible with tcnative 2.0.8, 2.0.10 and 2.0.11 ?
* Is netty 4.1.16 compatible with tcnative 2.0.8, 2.0.10 and 2.0.11 ?

**Comment by normanmaurer** [comment]
@floragunncom generally speaking netty is compatible with the version that is used in the pom.xml when the release is cut.

So for 4.1.13 its 2.0.5.Final and for 4.1.16 its 2.0.6.Final. That said I "believe" it should also work with 2.0.8 and 2.0.10 but we in general we do not guarantee this as we treat netty-tcnative as an internal dependency for netty. In the future we will most likely merge it into the netty project but there is still some stuff to figure out for this.

2.0.11.Final is not compatible.

**Comment by floragunncom** [comment]
thx
