### ISSUE TITLE
Issue: fail to load the required native library

### ISSUE THREAD

**Issue by NickNYU** [netty/netty-tcnative#375]
Hi,
I'm currently trying to leverage "boring-ssl-static" instead of JDK's SSL stuff, but the program keeping failing retrieving JNI libs(seems like).

I was wondering if there's an wonderful 'combo' for netty and netty-tcnative, because I'v tried three versions netty playing with 4(maybe) different versions tcnative

netty-4.0.37
netty-4.0.44
netty-4.0.46

tcnative
tcnative-boring-ssl

The last version, I'v tried is as the description below, that I believe might be a good fit

##Details

### Stack Trace

```java
[ChannelInitializer]Failed to initialize a channel. Closing: [id: 0xc0293b6a] java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:299) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:221) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:210) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:775) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446) ~[netty-all-4.0.46.Final.jar!/:4.0.46.Final]
 .........
```

### Java Version

> /usr/java/latest/bin/java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Netty Version
```xml
<dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-all</artifactId>
        <version>4.0.46.Final</version>
</dependency>

<dependency>
       <groupId>io.netty</groupId>
        <artifactId>netty-tcnative-boringssl-static</artifactId>
        <version>2.0.12.Final</version>
</dependency>
```

### OS

> uname -a
Linux ##### 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by NickNYU** [comment]
I finally somehow figure it out, to whom might be concerned about this problem:

Netty 4.1.(27|28).Final matches tcnative-boring-ssl 2.0.12.Final (got this combo from grpc project)

Netty 4.0.(36|37).Final matches tcnative-boring-ssl 1.1.33.Fork26

**Comment by normanmaurer** [comment]
@NickNYU just for the record you can easily find out which tcnative version to use with which netty version by checking the pom.xml of the release. For example:

https://github.com/netty/netty/blob/netty-4.1.28.Final/pom.xml#L224

**Comment by NickNYU** [comment]
Thank you @normanmaurer , that works

And to make it easier for others understanding the relationship between these two, would you please update the netty [wiki](http://netty.io/wiki/forked-tomcat-native.html) page?

Thanks

**Comment by rtdavies** [comment]
It would be great if that information was in release notes, on the wiki, or somewhere else slightly more searchable. Maybe it's just me (I'm new to netty) but I spent hours looking for it. Nonetheless, thanks for the great library!
