### ISSUE TITLE
openssl-static libnetty_tcnative.jnilib missing symbols

### ISSUE THREAD

**Issue by rtdavies** [netty/netty-tcnative#385]
I built libnetty-tcnative.jnilib from the openssl-static directory at release 2.0.14 and got a linking error trying to use it:

> java.lang.UnsatisfiedLinkError: Error looking up function 'EVP_md5': dlsym(0x7fd4eb49d3f0, EVP_md5): symbol not found

When I repeated my build at release 2.0.12, the error was gone. Upon investigation I found that the 2.0.14 library was missing all the openssl symbols. I was able to fix the build by remove a recently added argument to the maven-hawtjni-plugin configuration.

## Details

Build 2.0.12, and all (5168) the symbols are in the lib.

```
$ git checkout netty-tcnative-parent-2.0.12.Final
$ cd openssl-static/
$ mvn clean install
$ nm -gU ./target/native-lib-only/META-INF/native/osx64/libnetty_tcnative.jnilib
0000000000194430 T _ACCESS_DESCRIPTION_free
000000000020a950 S _ACCESS_DESCRIPTION_it
0000000000194410 T _ACCESS_DESCRIPTION_new
0000000000043050 T _AES_cbc_encrypt
0000000000042ab0 T _AES_decrypt
0000000000042520 T _AES_encrypt
0000000000042e30 T _AES_set_decrypt_key
0000000000042b70 T _AES_set_encrypt_key
0000000000044f20 T _AES_unwrap_key
0000000000044f00 T _AES_wrap_key
... thousands of lines removed
00000000001141a0 T _EVP_md5
... thousands of lines removed
000000000020b1f8 S _v3_sxnet
000000000020b378 S _v3_tls_feature
0000000000054c60 T _vpaes_cbc_encrypt
0000000000054c40 T _vpaes_decrypt
0000000000054c20 T _vpaes_encrypt
0000000000054be0 T _vpaes_set_decrypt_key
0000000000054bb0 T _vpaes_set_encrypt_key
0000000000173f40 T _whirlpool_block
000000000017eed0 T _x509_check_cert_time
000000000017c730 T _x509_set1_time
```

Build 2.0.14, and the openssl function symbols are missing. There are only 4 symbols total.
```
$ git checkout netty-tcnative-parent-2.0.14.Final
$ cd -
$ mvn clean install
$ nm -gU ./target/native-lib-only/META-INF/native/osx64/libnetty_tcnative.jnilib
0000000000004210 T _JNI_OnLoad
0000000000003e40 T _JNI_OnLoad_netty_tcnative
0000000000004220 T _JNI_OnUnload
0000000000004170 T _JNI_OnUnload_netty_tcnative
```

To fix the build I modified `netty-tcnative/openssl-static/pom.xml`
```
$ git diff
diff --git a/openssl-static/pom.xml b/openssl-static/pom.xml
index 3b25626..2aee2e7 100644
--- a/openssl-static/pom.xml
+++ b/openssl-static/pom.xml
@@ -73,7 +73,6 @@
               <configureArgs>
                 <configureArg>--with-ssl=${sslHome}</configureArg>
                 <configureArg>--with-apr=${aprHome}</configureArg>
-                <configureArg>--with-static-libs</configureArg>
               </configureArgs>
             </configuration>
           </execution>
```
The new configure argument was recently added at [this commit](https://github.com/netty/netty-tcnative/commit/def592bd6d6b57e749ca2a284b5547a7910c7c26).

**Comment by normanmaurer** [comment]
@rtdavies hmm thats very strange as in fact that is exactly what we want as we do not want to expose any openssl symbols from our static lib because it may cause strange side-effects when using multiple shaded versions of tcnative. I tested it locally here and it worked without any problems. Can you please provide the exact steps that caused the error for you ?

**Comment by rtdavies** [comment]
I suspected maybe this was intentional. I should have mentioned that to get the above linking error I'm using JNA to load the library.

```
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
...
public class MyLibClass {
    static {
        NativeLibrary instance = NativeLibrary.getInstance("netty_tcnative");
        Native.register(MyLibClass.class, instance);
   }
   ... function and data-struct definitions here ...
    public static native EVP_MD EVP_md5();
   ...
}      
```

**Comment by rtdavies** [comment]
And the stacktrace:
```
		java.lang.UnsatisfiedLinkError: Error looking up function 'EVP_md5': dlsym(0x7fd4eb49d3f0, EVP_md5): symbol not found
			at com.sun.jna.Function.<init>(Function.java:245)
			at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
			at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:542)
			at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:528)
			at com.sun.jna.Native.register(Native.java:1777)
			at com.code42.jna.MyLibClass.<clinit>(MyLibClass.java:86)
```

**Comment by normanmaurer** [comment]
@rtdavies yes that is completely by propose due the problem stated before and stated in the commit message of the change. We dont want to export any openssl functions, if the user want to use any they will need to link against their own openssl version. What we could do if its helpful would be to disable this new configure option with a flag tho.

**Comment by normanmaurer** [comment]
Also as a side note you may want to use 2.0.15.Final which fixes some problems with DH ciphers ;)

**Comment by rtdavies** [comment]
I talked to my architect and we have a preference for loading with JNA and don't know of a way to accomplish that without the symbols. Assuming that we aren't missing some technique, it would be nice to have an option to build with or without symbols, but without it, we can simply modify the pom.xml. Thanks!

**Comment by rtdavies** [comment]
I readily admit that we are probably doing something unnatural so if it doesn't make sense to maintain a build option, I'd say just go ahead and close this issue. 

Netty-tcnative, JNA and JNI are all new to me and I'm trying to maintain inherited code that, as you point out, is using using openssl functions via netty-tcnative library. I will look into improving how the code is structured and how libraries are loaded. Thanks for the advice!
