### ISSUE TITLE
Unable to build 2.0.15 statically against 1.1.1-pre9 on alpine 

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#386]
Building tcnative 2.0.15 statically against openssl 1.1.1-pre9 on alpine fails (It works well on ubuntu and fedora):

<pre>
     [exec] rm -f apps/openssl
     [exec] ${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -O3 -fno-omit-frame-pointer -fPIC -L.   \
     [exec] 	-o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
     [exec] 	 apps/libapps.a -lssl -lcrypto -ldl -pthread
     [exec] ./libcrypto.a(async_posix.o): In function `ASYNC_is_capable':
     [exec] async_posix.c:(.text+0x22): undefined reference to `getcontext'
     [exec] ./libcrypto.a(async_posix.o): In function `async_fibre_makecontext':
     [exec] async_posix.c:(.text+0x78): undefined reference to `getcontext'
     [exec] async_posix.c:(.text+0xe9): undefined reference to `makecontext'
     [exec] ./libcrypto.a(async.o): In function `async_fibre_swapcontext.constprop.3':
     [exec] async.c:(.text+0x38): undefined reference to `setcontext'
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[1]: *** [Makefile:6351: apps/openssl] Error 1
     [exec] make: *** [Makefile:171: all] Error 2
     [exec] make[1]: Leaving directory '/output/gen/netty-tcnative/openssl-static/target/openssl-1.1.1-pre9'
</pre>

**Comment by normanmaurer** [comment]
@floragunncom can you build openssl 1.1.1-pre9 by itself. This looks more like a build failure in openssl itself then in netty-tcnative.

**Comment by normanmaurer** [comment]
Closing due inactivity... please re-open if you still think there is anything we should do
