### ISSUE TITLE
 Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]

### ISSUE THREAD

**Issue by MariaSS88** [netty/netty-tcnative#393]
Windows x64 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

I am trying to call Google AutoML Vision model.
I have this dependency in my project
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <version>2.0.0.Final</version>
            <classifier>windows-x86_64</classifier>
</dependency> 

Why does the project try to find netty_tcnative_windows_x86_32 and netty_tcnative (with _ ) ?
I have netty-tcnative.dll (with - )

**Comment by Ravipatel401** [comment]
Did you find the answer? I have same Problem.

**Comment by slandelle** [comment]
netty-tcnative official binaries only ship with native binaries for 64 bits architectures. You run on a 32 bits one.
You would need to compile native binaries yourself. Or don't use tc-native and use JDK provider.

**Comment by Ravipatel401** [comment]
> netty-tcnative official binaries only ship with native binaries for 64 bits architectures. You run on a 32 bits one.
> You would need to compile native binaries yourself. Or don't use netty-tcnative and use JDK provider.

Please Elaborate that currently there are no any library name with netty-tcnative in my project my it create runtime,. Please see this **exception** 

java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:385)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:414)
	at

**Comment by slandelle** [comment]
The stacktrace is pretty explicit. Netty computes the name of the native library it needs to load for your architecture.

The `_x86_32` proves that Netty has detected that your platform is x86 **32 bits**.
As I said, Netty only provides natives binaries for x86 **64 bits** platforms.

Now, you use gRPC, so please read [its documentation](https://github.com/grpc/grpc-java/blob/master/SECURITY.md) and [reach out gRPC people](https://grpc.io/community/) if you have any further question.

**Comment by Ravipatel401** [comment]
Thanks,

Problem my solved by upgrading jdk 8 32bit to jdk 8 64bit. just installed and changed runtime.  then error gone.

**Comment by lyn1985** [comment]
for my situation ， I try to construct a Client, use this code :
ManagedChannelBuilder.forAddress(host, port)
                .usePlaintext(true)
                .build(); 
to solved the problem
