### ISSUE TITLE
Review usage of malloc

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-tcnative#40]
We should review the usage of malloc and if we check if allocation failed.

**Comment by Scottmitch** [comment]
`OPENSSL_malloc` while we are at it.

**Comment by normanmaurer** [comment]
@Scottmitch +1 :)

**Comment by johnou** [comment]
https://github.com/netty/netty-tcnative/commit/abded8736ac28d6044d1cd8439187f5af0ede0ce

**Comment by Scottmitch** [comment]
FWIW I don't think abded8736ac28d6044d1cd8439187f5af0ede0ce is necessary and may be confusing (openssl will not take ownership of these elements).
