### ISSUE TITLE
netty-tcnative jar should contains netty_tcnative library for all platforms

### ISSUE THREAD

**Issue by luengnat** [netty/netty-tcnative#403]
Is there any reason why netty-tcnative jar does not contain netty_tcnative library for all platforms. The baseline netty_tcnative does not contain any dynamic library while the os-specific version only contains the library for the target platform. This makes it a little difficult to make a single app package which will work across platforms without doing something magic with classpath as the libraries are named the same way across different platform.

**Comment by normanmaurer** [comment]
@luengnat that's unfortunately a bit tricky as centos and debian based linux distros use a different naming shaming for the included ssl installation. that said our static compiled version (against boringssl) includes all platforms.
