### ISSUE TITLE
Enable TLS v1.3 when using BoringSSL

### ISSUE THREAD

**Issue by nicktrav** [netty/netty-tcnative#405]
Currently, when using the borringssl-static variant of netty-tcnative for TLS, it is not possible to use version 1.3 of the protocol.

This is due to it being disabled at compile time:
https://github.com/netty/netty-tcnative/blob/4eac818deb1816758c329602511bfc1798099792/openssl-dynamic/src/main/c/ssl_private.h#L143-L148

so we end up with a runtime exception when starting up a server with TLS v1.3 specific ciphers:
https://github.com/netty/netty-tcnative/blob/4eac818deb1816758c329602511bfc1798099792/openssl-dynamic/src/main/c/ssl.c#L1569-L1574

(For my own benefit, `OPENSSL_IS_BORINGSSL` is defined in BoringSSL, [here](https://boringssl.googlesource.com/boringssl/+/chromium-stable/include/openssl/base.h#146).)

From what I can tell, the latest versions of chromium-stable support TLS v1.3, so I'm wondering if this compile-time restriction could be lifted now, or if not, what is blocking that from being done?

Fwiw - everything works as expected when using tcnative v2.0.17 (openssl-static) and netty/netty@0ddc62cec, and we can reap the benefits of TLS v1.3 🎉

**Comment by normanmaurer** [comment]
@nicktrav Are you sure it’s in chromium-stable yet ?

**Comment by normanmaurer** [comment]
@nicktrav just talked to @davidben and he pushed everything to the chromium-stable branch so we should be able to support it. Will have a look soon :)

**Comment by nicktrav** [comment]
Ah, apologies @normanmaurer! I was being presumptuous. I just noticed a bunch of commits on the branch we're building BoringSSL off of (we build internally), and assumed it was on chromium-stable.

Thanks for following up, and thanks @davidben for pushing 🙏

**Comment by nicktrav** [comment]
@normanmaurer I think we're all good here, so I'll close this one out 👍.

Linking to #406, which is merged now.
