### ISSUE TITLE
netty-tcnative should contain more implementations to crypto library e.g. EVP API

### ISSUE THREAD

**Issue by luengnat** [netty/netty-tcnative#411]
@normanmaurer I'm not sure whether it is the right place to ask. But openssl already has a much more efficient implementation of cipher and digest which can be useful for an application that uses Netty. Do you think it worths to expose OpenSSL's EVP API out via netty-tc-native JNI so that the application can use those apis easily instead of having to write another JNI library to do so?

**Comment by normanmaurer** [comment]
@luengnat honestly I think it a bit out of scope of what we try to do here and I think we are currently not ready to support it.

**Comment by luengnat** [comment]
fair enough.
