### ISSUE TITLE
Is tcnative 2.0.20.Final compatible with netty 4.1.30?

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#414]
Is tcnative 2.0.20.Final compatible with netty 4.1.30? 

If not, what is the latest compatible version? (I know that 2.0.15 is in the pom of 4.1.30 but i like to have at least 2.0.16 because of TLSv13 and i cannot upgrade netty to anything else than 4.1.30)

**Comment by normanmaurer** [comment]
Sorry but the latest is what is in the pom.xml. Also you will need Netty 4.1.31.Final for TLS1.3
