### ISSUE TITLE
Document how to only statically link APR

### ISSUE THREAD

**Issue by fzakaria** [netty/netty-tcnative#416]
Due to FIPS compliance, we have a weird usecase where we'd like to dynamically link against the system OpenSSL library (FIPS version) but simplify our deployment by having APR statically link.

It's not clear from the _fork documentation_, how to do so. By looking at the parent-pom, the _linkStatic_ variable seems to control both. 

Is there an opportunity to perhaps break out that property into two -- one for each library?

**Comment by normanmaurer** [comment]
@fzakaria its not supported atm... that said I guess we can easily do. I will do a pr

**Comment by fzakaria** [comment]
@normanmaurer thanks -- 
I'm pretty proficient with maven however the _hawtjni_ stuff is a bit new to me.

We are currently building the dynamic OpenSSL version against OracleLinux.

I imagine with the changes you might submit, I would just create internally a new child module "openssl-dynamic-apr-static" that sets the correct property values.

Please tag me on any PR I would appreciate to follow along.

**Comment by normanmaurer** [comment]
@fzakaria is this still something you need ?

**Comment by fzakaria** [comment]
No not really. We're making the dynamic linking work it's just more of a
pita.

**Comment by normanmaurer** [comment]
ok let me close this one then
