### ISSUE TITLE
parsePackagePrefix does not correctly unescape JNI package paths

### ISSUE THREAD

**Issue by kennknowles** [netty/netty-tcnative#419]
In JNI, the sequence `_1` stands for an underscore in a package name or class name. However, the logic in [parsePackagePrefix](https://github.com/netty/netty-tcnative/blob/master/openssl-dynamic/src/main/c/jnilib.c#L266) unconditionally converts all underscores to slashes.

This arose in the context of Apache Beam, which relocated it to `org.apache.beam.vendor.grpc.v1_13_1.netty`. Our workaround is to just not use underscores, but this should also be easy to fix.

More details at https://issues.apache.org/jira/browse/BEAM-6249

**Comment by normanmaurer** [comment]
@kennknowles PRs welcome :)

**Comment by kennknowles** [comment]
@normanmaurer of course! I was just working on it. I don't do a lot of C these days so my emacs config had rotted :-). #420.

**Comment by normanmaurer** [comment]
@kennknowles 🤣 vi FTW ;)

**Comment by kennknowles** [comment]
I tried `vim` first, but my config there is even worse and kept wanting to use tabs :-p (just to bring both of the great debates into this...)

**Comment by trustin** [comment]
Should be fixed in 2.0.52.Final.
