### ISSUE TITLE
Getting exception on AIX (IBM). SSL looking for binaries for AIX(IBM) platform. 

### ISSUE THREAD

**Issue by AnujRajSingh** [netty/netty-tcnative#424]
I am trying to use booringSSL on AIX(IBM) platform using java
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20180626_390413 (JIT enabled, AOT enabled)
and 
Maven dependency
  ```
  <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.17.Final</version>
    </dependency>
```
I am getting Exception 

INFO   | jvm 1    | 2018/12/06 13:23:26 | 	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_aix_ppc_64WrapperSimpleApp Error: 
INFO   | jvm 1    | 2018/12/06 13:23:26 | 		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:233)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2018/12/06 13:23:26 | 		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2018/12/06 13:23:26 | 		... 67 moreWrapperSimpleApp Error:

Do I need to build the binaries for  AIX? 

Thanks

**Comment by normanmaurer** [comment]
Yes... We do not ship AIX support

**Comment by arssingh1983** [comment]
Thanks !!

**Comment by AnujRajSingh** [comment]
Thanks!!

**Comment by sheetal-s** [comment]
Hi Anuj
I am facing the same issue, what did you ultimately do to address this, I need to support HP-UX as well.
Any pointers will be helpful.

**Comment by ankitshubham97** [comment]
@AnujRajSingh I am getting similar issue (https://github.com/grpc/grpc-java/issues/5369 and https://github.com/netty/netty/issues/8871). Could you tell how did you do that for AIX?

**Comment by AnujRajSingh** [comment]
You Need to build binaries on the AIX (Though this one for Linux, you need corresponding packages for AIX https://netty.io/wiki/forked-tomcat-native.html#wiki-h3-13)  Thanks Anuj

**Comment by ankitshubham97** [comment]
@AnujRajSingh Did you also make any change in the netty-tcnative code? Or its pom.xml?

**Comment by ankitshubham97** [comment]
@AnujRajSingh And which JDK did you use? If I am correct, IBM does not provide its own JDK.

**Comment by vikashbhattar** [comment]
Can someone provide the steps to compile binaries on AIX?

**Comment by slandelle** [comment]
@vikashbhattar AIX is sold by IBM and very few people have access to it. IMHO, instead of reaching out to an open source community, you should probably ask your IBM support.
