### ISSUE TITLE
failed to load netty_tcnative_linux_x86_32

### ISSUE THREAD

**Issue by ankit0706** [netty/netty-tcnative#425]
Hi all,
I am creating a gRPC client and server. My code was executed perfectly on my windows machine, but the same code is failing on linux.

My error message : 
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_32, netty_tcnative_linux_x86_32_fedora, netty_tcnative_x86_32, netty_tcnative]

My Maven dependency in pom.xml
```
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty-tcnative-boringssl-static</artifactId>
<version>2.0.20.Final</version>
<classifier>linux-x86_64</classifier>
</dependency>
```

Upon hitting the command 'lscpu' on my putty shell
I get, 
Acrhitecture: x_86_64
CPU op-mode(s): 32-bit, 64-bit
CPU(s): 32
etc. etc,

my java -version:  1.6.0_24

Why is my code looking for 32 bit libraries when in fact 32-bit libraries do not even exist for this component (I tried in maven, but there is no such lib it seems).
What should I do? What is wrong?

**Comment by normanmaurer** [comment]
@ankit0706 I think you use a 32bit JVM. What does `java -version` tell you ? Also Java 1.6 is super old I would recommend updating it.

**Comment by ankit0706** [comment]
@normanmaurer You're right. I just checked and it's 32 bit JVM. The windows machine where my code ran isusing 64 bit JVM. Actually windows is my mahcine and the linux one is where I have to deploy, so I guess I need to inform the guys maintaining the server about this factor.

**Comment by normanmaurer** [comment]
Yes...closing
