### ISSUE TITLE
netty-tcnative on s390x not working: Filebeat is throwing `tls:ServerkeyExchange Error`

### ISSUE THREAD

**Issue by AnitaNayak** [netty/netty-tcnative#431]
Built netty-tcnative 1.1.33 on s390x using OpenJDK-1.8. boringssl-static jar got built and bundled the Jar with logstash:5.5.1. But filebeat is throwing `tls:ServerkeyExchange Error`. 
There are two queries:
1. How to build boringssl-static jar in debug mode. I tried boringssl-static/pom.xml as `-DDEBUG` mode. But getting error with undefined error.
2. While building on s390x, encountered two errors as mentioned in https://github.com/linux-on-ibm-z/docs/wiki/Building-netty-tcnative (Unknown processor, and Unknown target CPU) and fixed the same way as mentioned in the same document. Could you please confirm, if that is good enough? As I see there are many files specific to different archs, such as `ppc64le`... Should we include similar files for s390x and rebuild. 

Please let us know. We are having issues connecting between logstash and filebeat. but not getting much clue.

**Comment by AnitaNayak** [comment]
Can any one give some suggestions from netty-tcnative community if the above build procedure is correct?

**Comment by AnitaNayak** [comment]
@normanmaurer , could you please respond to the above queries? Do we need to introduce any s390x platform specific code to make it work? Though netty-tcnative built on s390x as mentioned above, but still the logs are not flowing and filebeat throws `tls: ServerKeyExchange Error`.

**Comment by normanmaurer** [comment]
Sorry I have no idea ... I don't have any experience with building on S390x and also have no access to such a platform to investigate.

**Comment by AnitaNayak** [comment]
Hi @normanmaurer, could you please help us in building netty-tcnative on s390x. We have many s390x VMs. I can check with my manager on how can we give you the access to. Please let us know, if that can help. Thank  you very much for responding us.

**Comment by gennadylaventman** [comment]
@AnitaNayak Just saw you message while looking for netty-tcnative for system z. Maybe this can help:
https://github.com/linux-on-ibm-z/docs/wiki/Building-netty-tcnative

**Comment by normanmaurer** [comment]
@AnitaNayak yes please provide me a VM and I may be able to help... that said I am not sure if BoringSSL supports this platform at all. Are you sure it does ?

**Comment by normanmaurer** [comment]
@AnitaNayak ping...

**Comment by normanmaurer** [comment]
Closing as no response

**Comment by AnitaNayak** [comment]
Sorry for the late response. We can close this. Thank you.
