### ISSUE TITLE
Support Debian

### ISSUE THREAD

**Issue by ejona86** [netty/netty-tcnative#44]
For gRPC, [we're interested](https://github.com/grpc/grpc-java/issues/547) in encouraging users to use tcnative instead of jetty-apln. This would work pretty well, except that lots of our users would be Debian/Ubuntu users. Having a pre-built binary for Debian is a prerequisite for us encouraging our users to use tcnative.

We would have little problem making our own builds of tcnative, but it seems that solving the "Debian vs Red Hat" problem would help tcnative in general.

The main problem I see is what to specify as the classifier for any Debian binary. The OS detector doesn't vary based on RHEL/Debian. We could just add "-debian" to the end and force users to hard-code when they are running on Debian. Not great, but better than nothing.

If combined with #24, we could solve it more cleanly as both variants of the Linux .so could be included in the JAR.

**Comment by nmittler** [comment]
@normanmaurer @trustin @Scottmitch any thoughts on this?

**Comment by Scottmitch** [comment]
@nmittler - I would like to see Debian supported. I wonder if we could make an "intermediate" dependency which pulls in the correct one depending on linux disto?

1. Users include tc-native.
2. The tc-natvie pom file detects which architecture (maybe runs shell cods if necessary) to figure out tc-native-<architecture>
3. We build/publish artifacts for tc-native-<architecture>.

Does this sound feasible?

**Comment by normanmaurer** [comment]
@nmittler I would love to see Debian support as well but I was just too busy to think about it.. gimme some more time.

**Comment by nmittler** [comment]
@Scottmitch yeah that might work.  So maybe have an intermediate dependency called `tc-native-linux` that switches on the distro.

It would also be nice to have the [os-maven-plugin](https://github.com/trustin/os-maven-plugin) updated to provide more information.

**Comment by Scottmitch** [comment]
@nmittler - Maybe but what I was originally thinking was having 3 layers:

1. `tc-native` (users directly include this in their POMs)
2. `tc-native-arch-detector` (`tc-native` from layer 1 includes this. this does the work of picking the correct dependency from the layer 3 below).
3. Each platform would publish a jar at this level (`tc-native-linux-rhel`, `tc-native-linux-debian`, `tc-native-windows-...`, `tc-native-osx-...`, etc... does it make sense to also include 64 bit 32 bit in jar versions?).

If you wanted you could include a 4th layer which knows more details about its respective platform (layer 3 would be layer 4...and the new layer 3 would include 1 pom for windows, 1 for linux, 1 for mac, etc...)

**Comment by nmittler** [comment]
@Scottmitch So what we have now is layers 1 & 3. I think we can avoid layer 2 if we modify the `os-maven-plugin` to add an additional field (e.g. `os.detected.family`), which would only be used on linux and would contain the value of `ID_LIKE` from [/etc/os-release](http://www.freedesktop.org/software/systemd/man/os-release.html). Then we could have the plugin optionally include `${os.detected.family}` in the value it generates for `${os.detected.classifier}`, giving us something like `linux_debian_x86_64`.

**Comment by nmittler** [comment]
@normanmaurer any thoughts?

**Comment by trustin** [comment]
We could add `os.detected.family` and let it be `generic` or something similar for undetected families and the OSes without diversity.  Then we could use `${os.detected.classifier}_${os.detected.family}`?  Alternatively, we can just break the backward compatibility and let `os.detected.classifier` includes `os.detected.family`.  It's just a classpath changes, so I guess it shouldn't be a big deal.

However, I think we could solve this problem more nicely.  Please see the issues filed by @cconroy - #33 and netty/netty#3502  We could revise our release (and deployment) process so that our CI server takes care of producing the JAR with the native libraries of all platforms, then the problem gets much simpler.

**Comment by nmittler** [comment]
@trustin regarding #33 and netty/netty#3502, wouldn't we still need a separate build for debian/rhel due to the difference of soname for libssl.so and libcrypto.so?

**Comment by normanmaurer** [comment]
@nmittler yes we would. That said I would like to also release a version build against libressl ans maybe also boringssl. So let me pick this up next week and get all of it done.

**Comment by nmittler** [comment]
@normanmaurer that would be awesome! Let me know if there's anything I can help out with.

**Comment by zhangkun83** [comment]
> Alternatively, we can just break the backward compatibility and let os.detected.classifier includes os.detected.family. It's just a classpath changes, so I guess it shouldn't be a big deal.

@trustin Protobuf team and gRPC team are using os.detected.classifier in the pre-compiled protoc and codegen artifacts published on Maven Central. This would break us as we are not going to publish artifacts per family.

**Comment by nmittler** [comment]
If we make the inclusion of `${os.detected.family}` in the classifier opt-in (see https://github.com/netty/netty-tcnative/issues/44#issuecomment-117845617) then that wouldn't break us.

@normanmaurer thoughts?

**Comment by zhangkun83** [comment]
I would not change what ``os.detected.classifier`` returns. It would break everything around protoc and grpc codegen artifacts, including the publishing process, and Gradle and Maven plugins that consume them.

IMO the biggest value of os-maven-plugin is producing unified identifiers for OS, arch, etc. Providing a unified classifier is not universally useful because different projects may want to include different fields in the classifier. It would be more reasonable for different projects to compose their own classifiers from the individual fields provided by os-maven-plugin. Maybe we should eventually remove os.detected.classifier.

**Comment by trustin** [comment]
On Thu, Jul 9, 2015, at 04:15 AM, Kun Zhang wrote:
> I would not change what os.detected.classifier returns. It would break
> everything around protoc and grpc codegen artifacts, including the
> publishing process, and Gradle and Maven plugins that consume them.


> IMO the biggest value of os-maven-plugin is producing unified
> identifiers for OS, arch, etc. Providing a unified classifier is not
> universally useful because different projects may want to include
> different fields in the classifier. It would be more reasonable for
> different projects to compose their own classifiers from the
> individual fields provided by os-maven-plugin. Maybe we should
> eventually remove os.detected.classifier.


Agreed. +1 for not changing os.detected.classifier. Not sure about
deprecating it since it should still be useful for statically linked
libraries. The problem we are seeing here is basically we don't want to
link statically with glibc(xx) and openssl.

Let me try to release os-maven-plugin with my spare cycle.

**Comment by nmittler** [comment]
@trustin +1, I see no need in deprecating `os.detected.classifier`.  It's there as a utility if folks want to use it.

@normanmaurer is this still on your radar?

**Comment by normanmaurer** [comment]
@nmittler yeah kind of... just too busy and not really very high on my to do list atm :(

**Comment by nmittler** [comment]
@normanmaurer anything I could do to help out? Maybe I could take a crack at the changes to the os-maven-plugin to get the ball rolling?

**Comment by nmittler** [comment]
FYI, I just created https://github.com/trustin/os-maven-plugin/pull/10 to add detection of OS variants to the `os-maven-plugin`. It should be fairly easy to retrofit `netty-tcnative` to use a custom deployment for debian.

**Comment by nmittler** [comment]
@normanmaurer gentle ping.  Now that the `os-maven-plugin` has been released, we should be able to release netty_tcnative for debian.

**Comment by normanmaurer** [comment]
@nmittler will do tomorrow. Sorry for the slowness :-1:

**Comment by nmittler** [comment]
@normanmaurer sgtm! No worries, I know you're busy! :)

**Comment by nmittler** [comment]
@normanmaurer Just to clarify, you'll also release a "_debian" artifact built on wheezy?

**Comment by normanmaurer** [comment]
@nmittler that's the plan

**Comment by nmittler** [comment]
:+1:

**Comment by nmittler** [comment]
@normanmaurer I think we can close this now?

**Comment by Scottmitch** [comment]
http://repo1.maven.org/maven2/io/netty/netty-tcnative/1.1.33.Fork6/

**Comment by nmittler** [comment]
It brings a tear to my eye!!!  Closing!!! :)

**Comment by normanmaurer** [comment]
Boom!

**Comment by nmittler** [comment]
LOL ... what he said!

**Comment by trustin** [comment]
@nmittler High-five! :hand:
