### ISSUE TITLE
IBM 8 + BoringSSL and client certificate signature again

### ISSUE THREAD

**Issue by kwart** [netty/netty-tcnative#448]
This is a follow up for issue #404.

We experience issues when running on IBM Java (we use version 8) with BoringSSL provider on the server side and JSSE engine on the client side.
The problems started with netty version `4.1.31.Final` and are still present in `4.1.34.Final`. Nevertheless, in my opinion it's only a side effect of a problem in the `netty-tcnative-boringssl-static`.
The native `SSL.getSigAlgs(long)` call returns `null` for some reason.

With SSL debug logging enabled I see following entries in the log:
```
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
ssl: Ignoring alias key: signature does not conform to negotiated signature algorithms
```

I've built the latest netty `4.1.35.Final-SNAPSHOT` and tcnative  `2.0.23.Final-SNAPSHOT`, but the problem is still there.

When I switch from BoringSSL (`netty-tcnative-boringssl-static`) to the dynamically linked OpenSSL (`netty-tcnative`). Then the SSL handshake finishes successfully.

Issue reproducer is available in the following branch:
https://github.com/kwart/test-app/tree/netty-reproducer-boringssl-ibm8
it's based on `EchoServer` netty example.

**Comment by normanmaurer** [comment]
@kwart so you are saying it also not work when you use the exact same versions that reported it fixed in #404 ?

**Comment by kwart** [comment]
The fix for #404 mentions netty 4.0.32.Final and netty-tcnative 2.0.20.Final. This issue is present in that combination.

On the other hand, the issue #404 is reported against combination 4.1.30.Final + 2.0.18.Final. This issue is not reproducible on that one.

**Comment by normanmaurer** [comment]
@kwart ok got it... let me have look.

**Comment by normanmaurer** [comment]
@kwart ok I found the problem... working on a fix + unit test now :)

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty-tcnative/pull/449. I will add a unit test to netty itself.
