### ISSUE TITLE
Linux .so isn't stripped

### ISSUE THREAD

**Issue by ejona86** [netty/netty-tcnative#45]
netty-tcnative-1.1.33.Fork2-linux-x86_64.jar is 422.7K, whereas osx-x86_64 and windows-x86_64 are ~125K.

libnetty-tcnative.so is actually 996K in size. Stripping it reduced it to 163K and the JAR itself to 129K.

**Comment by normanmaurer** [comment]
@ejona86 you are talking about gcc -s ?

**Comment by ejona86** [comment]
I was referring to the strip command. But yes, I think gcc -s does the same thing.

Hmm... `strip -g` reduced the .so to 214K. Was it accidentally compiled with `gcc -g`?

**Comment by normanmaurer** [comment]
@ejona86 I will check what our autoconf stuff does here.

**Comment by ejona86** [comment]
I was thinking it was more likely that you had some environment variables set on the build machine. If you had a CXXFLAGS=-g or similar then it would cause that.

**Comment by normanmaurer** [comment]
@ejona86 I will check on a fresh linux install how it looks like

**Comment by normanmaurer** [comment]
@ejona86 I checked and "CFLAGS" includes "-g" in the Makefile which was generated by autoconf. Checking now how to fix this. Stay tuned.

**Comment by normanmaurer** [comment]
@ejona86 ok I think I know how I can fix this... will need to spend some time on it. That said I'm currently a bit tight on time so I guess not before next week.

**Comment by ejona86** [comment]
@normanmaurer, no rush. It isn't hurting much right now. We will want it eventually, since it is a noticeable decrease in dependency weight, but it doesn't block anything.

**Comment by normanmaurer** [comment]
@ejona86 see https://github.com/netty/netty-tcnative/pull/49

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-tcnative/pull/49
