### ISSUE TITLE
netty-tcnative-boringssl-static 2.0.25.Final artifact is not static

### ISSUE THREAD

**Issue by johnou** [netty/netty-tcnative#467]
```
2.0.25.Final]$ ldd META-INF/native/libnetty_tcnative_linux_x86_64.so
ldd: warning: you do not have execution permission for `META-INF/native/libnetty_tcnative_linux_x86_64.so'
	linux-vdso.so.1 (0x00007ffc80314000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f55f1bc2000)
	libcrypt.so.1 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f55f1ba1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f55f1b9b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f55f19d5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f55f2035000)
```

shouldn't libcrypt.so.1 be included?

**Comment by normanmaurer** [comment]
Hmm will need to have a look. Does it not work when trying to use it ?

**Comment by johnou** [comment]
Yeah fails on vanilla Fedora 30, I could probably work around it by symlinking libcrypt.so.1 to libcrypt.so.x but it shouldn't be necessary. I can take a peek later today as well but I need to finish up some gardening first.

**Comment by johnou** [comment]
When building it locally it ends up linking to libcrypt.so.2

✔ ~/Workspaces/netty-tcnative/boringssl-static/target/native-build [master|✔] 
17:20 $ ldd ./target/lib/libnetty_tcnative.so
	linux-vdso.so.1 (0x00007ffedd7bb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f2baac5b000)
	libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f2baac20000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2baabff000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2baabf9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2baaa33000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2baaebe000)

**Comment by normanmaurer** [comment]
I now remember that @ejona86 also brought this up... You need to use:

```
dnf -y install libxcrypt-compat
```

See https://github.com/grpc/grpc-java/commit/2b7269b68c610f2dbabed149ce5f866a3935a647#diff-f1a97ccd40c28e5c0945852559d3903cR349

I will update the docs.

**Comment by normanmaurer** [comment]
done ... https://github.com/netty/netty/wiki/Forked-Tomcat-Native#prerequisites-for-statically-linked-netty-tcnative--static

**Comment by johnou** [comment]
Thanks!
