### ISSUE TITLE
JVM fails with "relocation error" on dynamic openSSL library

### ISSUE THREAD

**Issue by NicoK** [netty/netty-tcnative#471]
I'm on openSUSE Tumbleweed x86_64 and I'm trying to use dynamically-linked openSSL through `netty-tcnative`. However, it seems that my system library is packaged/built a bit differently than what the official builds expect (similarly to #223). I'm getting this (in case you are wondering, we're using a shaded version for Apache Flink):
```
/usr/lib64/jvm/java-openjdk/bin/java: relocation error: /tmp/liborg_apache_flink_shaded_netty4_netty_tcnative_linux_x86_644115489043239307863.so: symbol TLSv1_2_server_method version OPENSSL_1.0.1 not defined in file libssl.so.1.0.0 with link time reference
```

Comparing the released wrapper lib with my system one indeed shows that discrepancy:
```
> readelf -Ws /usr/lib64/libssl.so.1.0.0 | grep TLSv1_2_server_method
   502: 0000000000031a30     8 FUNC    GLOBAL DEFAULT   14 TLSv1_2_server_method@@OPENSSL_1.0.0
   901: 000000000003b9a0     8 FUNC    GLOBAL DEFAULT   14 DTLSv1_2_server_method@@OPENSSL_1.0.0
```
vs.
```
> objdump -T /tmp/liborg_apache_flink_shaded_netty4_netty_tcnative_linux_x86_644115489043239307863.so | grep TLSv1_2_server_method
0000000000000000      DF *UND*  0000000000000000  OPENSSL_1.0.1 TLSv1_2_server_method
```

After building the netty-tcnative manually, I do get a different dependency matching my build:
```
> objdump -T libnetty_tcnative.so | grep TLSv1_2_server_method
0000000000000000      DF *UND*  0000000000000000  OPENSSL_1.0.0 TLSv1_2_server_method
```

However, that wouldn't solve the general case for *any* developer using a single dependency on netty-tcnative. Purely having this in the classpath with any code accessing openSSL, e.g. a simple `OpenSsl.isAvailable()`, would crash the JVM. Is there anything we can do about this (it is apparently no `Throwable` to catch though)? It would be fine to return "not available" for that scenario. Can we somehow verify that the dynamic library is not usable?

This is related to / an extension of the issue already reported as #223 

FYI: Digging a bit deeper, it is eventually failing on https://github.com/netty/netty/blob/8ce3d52c0e7eb69d28647f942eaef68f7443a2d1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L182 where the native lib is actually used for the first time.

**Comment by normanmaurer** [comment]
@NicoK thanks for all the details.. Unfortunately I have no idea how we could catch this :/

**Comment by NicoK** [comment]
I played around with adding more classifiers for suse and arch-based systems, but unfortunately, that won't be enough. Problem seems to be that (in contrast to the special fedora package), JNI wouldn't fail during loading the library (sing the `libssl.so.1.0.0` file is there) but while using the package and I haven't found a way to catch this error (I can only suspect that this is not possible).

While we can probably not solve it generically, we may be able to add more classifiers for common OSs with known incompatibilities. That way, we would at least solve it for some people. In addition to adding classifiers, we would have to change the library loading though:
Instead of having `OpenSsl#loadTcNative()` call `NativeLibraryLoader#loadFirstAvailable()` with a list of all available names, we should (similarly to the build process) try to load the library (first?) with a classifier that closely matches the runtime OS (maybe interpreting `/etc/os-release` (and similar) as the `os-maven-plugin` does, potentially re-using its [Detector.java](https://github.com/trustin/os-maven-plugin/blob/master/src/main/java/kr/motd/maven/os/Detector.java)). Therefore, if we have a special library for the current OS we would use that instead of the default one which circumvents the problem.

If you agree with these steps, I can create a PR for that change.

**Comment by normanmaurer** [comment]
@NicoK sounds good.

**Comment by normanmaurer** [comment]
So the classifier thing was committed as  34a68c8. Closing
