### ISSUE TITLE
Problem with building on ppcle_64

### ISSUE THREAD

**Issue by morvael** [netty/netty-tcnative#473]
Netty build fails with:
```
Could not resolve dependencies for project io.netty:netty-handler:jar:4.1.37.Final: Could not find artifact io.netty:netty-tcnative:jar:linux-ppcle_64:2.0.25.Final
```

so I tried to build netty-tcnative locally, but it fails with:
```
Requested download does not exist.: Could not find artifact io.netty:netty-tcnative:zip:native-src:2.0.25.Final in central
```

Am I doing something wrong?

system: CentOS Linux release 7.6.1810 (AltArch)
kernel: 3.10.0-957.1.3.el7.ppc64le
java:
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 8.0.5.37 - pxl6480sr5fp37-20190618_01(SR5 FP37))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20190617_419755 (JIT enabled, AOT enabled)
OpenJ9   - 354b31d
OMR      - 0437c69
IBM      - 4972efe)
JCL - 20190606_01 based on Oracle jdk8u211-b25
```
maven: 3.6.1

**Comment by normanmaurer** [comment]
Yes because we don not support ppcle_64.

**Comment by morvael** [comment]
Sure, but shouldn't it build from source?

Anyway, turns out the actual error was a bit earlier:
````
INFO] executing: /bin/sh -c ./autogen.sh
[INFO] auto reconf...
[INFO] ./autogen.sh: line 33: autoreconf: command not found
[INFO] rc: 127
````

My fault, required packages were not installed. It went past this hurdle now.

**Comment by morvael** [comment]
Had to switch to OpenJDK from RedHat repos, and it compiled properly, will soon check if it works. Had some issues though:
- It's not easy to supply tar.gz sources of OpenSSL manually in case FTP download is blocked (somehow corporate IT security hates FTP), because pom wants to put them into target directory (which is removed on clean install). Please allow placing the download somewhere else (for example project root directory) or switch to HTTP download.
- in boringssl ninja executable is referenced, where on my platform it was actually called ninja-build. It would be nice if build script would be able to detect that.

@normanmaurer do you think it's a good idea to open one or two issues with the above problems? That would allow building netty-tcnative out of the box on ppc64le.

**Comment by morvael** [comment]
Build finished and epoll is working.
