### ISSUE TITLE
Improve the method of downloading OpenSSL sources for static build

### ISSUE THREAD

**Issue by morvael** [netty/netty-tcnative#474]
Currently OpenSSL sources are downloaded using FTP. Somehow corporate IT security doesn't like FTP at all, and disable it completely (at least where I work and worked). It's possible to skip this step by supplying tar.gz of OpenSSL sources manually, but build script wants them placed in target directory, which means they are removed on clean install. Please alter pom.xml to either:
a) place and look for tar.gz with OpenSSL sources outside target directory
b) switch to HTTP download

pom.xml of openssl-static subproject is the file that has to be changed.

**Comment by slandelle** [comment]
> b) switch to HTTP download

Is very unlikely to solve anything for corporate IT where direct access is typically forbidden and you are force to use a proxy with some complicated auth.

**Comment by morvael** [comment]
Then, option A will be enough.

**Comment by morvael** [comment]
If going with option a) the same has to be done for boringssl-static and libressl-static subprojects, as they all download to target.

**Comment by normanmaurer** [comment]
@morvael see https://github.com/netty/netty-tcnative/pull/478 for switching to use https

**Comment by morvael** [comment]
From what I see ftp download was retained in build-openssl-windows profile.

**Comment by morvael** [comment]
Download and build on build-openssl-linux profile was successful.

**Comment by normanmaurer** [comment]
@morvael changed windows as well

**Comment by morvael** [comment]
Looks good although I haven't tested it, but it's now similar to other profiles, so it should work.

**Comment by normanmaurer** [comment]
I think this is fixed now
