### ISSUE TITLE
Using netty-tcnative with openssl-fips. How can I verify that its running with fips enabled?

### ISSUE THREAD

**Issue by Andrew-Lev** [netty/netty-tcnative#481]
I am running grpc-netty-1.18 with netty-tcnative 2.0.20 on CentOS Linux release 7.6.1810. This is all in a docker. I need to verify that its running in FIPS mode.

I've gone and built the dynamic netty-tcnative with OpenSSL 1.0.2-fips, and I do see it reporting that it using the expected version in the logs.

    DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: OpenSSL 1.0.2k-fips

For reference these are the jars being used:
grpc-netty-1.18.0.jar
netty-tcnative-2.0.20.Final-linux-x86_64.jar

I see APR logs stating that fips mode was successfully entered.

    [WrapperSimpleAppMain] INFO org.apache.catalina.core.AprLifecycleListener - Successfully entered FIPS mode

Everything seems to work as intended and I dont see any errors, but I also dont see any way to get info on whether grpc is running with FIPS mode

On load I see log output about a bunch of cipher suite mappings, default cipher suites, and supported protocols. I know some of the loaded cipher suites are not fips compliant, but Im not sure if that log output would be different with fips enabled or not.

I've tried passing io.netty.internal.tcnative.SSL.fipsModeSet(1) but I dont see any difference in the log output.

Is there some conclusive way determine whether I've got things running in a fips compliant mode?

carl-mastrangelo from grpc suggested that io.netty.internal.tcnative.SSL.fipsModeSet could return the value from OpenSSL

[Original Ticket](https://github.com/grpc/grpc-java/issues/6035)

**Comment by normanmaurer** [comment]
@Andrew-Lev yeah we could make it return the value... Would this help ?

**Comment by normanmaurer** [comment]
@Andrew-Lev actually if `SSL.fipsModeSet(1)` did not throw it was successful to enable FIPS. So I don't think we need to change anything.

**Comment by normanmaurer** [comment]
Closing as I think what we have is good enough... @Andrew-Lev Please re-open if you disagree .
