### ISSUE TITLE
Using server alias name in client code for grpc

### ISSUE THREAD

**Issue by ankit0706** [netty/netty-tcnative#486]
Hi all, I am using gRPC for my client/server. This is about using the server's hsotname at client side code.  At server side I used the following code connecting to the service

public static NettyChannelBuilder.forAddress(String host, int port)

Earlier we used the actual hostname and it worked but now we are aked to use alias.
the alias name when put in the same code does not work and I get the error 
No name matching <alias> found....

How to use the alias name in grpc client code to connect.

**Comment by normanmaurer** [comment]
@ankit0706 you should ask on the GRPC issue tracker / mailing list.
