### ISSUE TITLE
Build error netty-tcnative-parent-2.0.17.Final

### ISSUE THREAD

**Issue by jiameixie** [netty/netty-tcnative#500]
The branch I used is netty-tcnative-parent-2.0.17.Final. When running 'mvn clean install', the following error occured.  How to solve this? If removing CFLAGS,CFLAGS ,LDFLAGS, it could build successfully.

INFO] executing: /bin/sh -c ./configure --disable-ccache --prefix=/home/xjm/netty-tcnative/boringssl-static/target/native-build/target --with-ssl=no --with-apr=/home/xjm/netty-tcnative/boringssl-static/target/apr --with-static-libs 'CFLAGS=-O3 -Werror -fno-omit-frame-pointer -fvisibility=hidden -Wunused-variable' 'CPPFLAGS=-DHAVE_OPENSSL -I/home/xjm/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/include' 'LDFLAGS=-L/home/xjm/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build/ssl -L/home/xjm/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build/crypto -L/home/xjm/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build/decrepit -ldecrepit -lssl -lcrypto'
[INFO] configure: WARNING: unrecognized options: --disable-ccache
[INFO] checking build system type... x86_64-pc-linux-gnu
[INFO] checking host system type... x86_64-pc-linux-gnu
[INFO] checking target system type... x86_64-pc-linux-gnu
[INFO] ./configure: line 2299: -O3: command not found
[INFO] ./configure: line 2300: -O3: command not found
[INFO] checking for gcc... gcc
[INFO] checking whether the C compiler works... no
[INFO] configure: error: in `/home/xjm/netty-tcnative/boringssl-static/target/native-build':
[INFO] configure: error: C compiler cannot create executables

**Comment by jiameixie** [comment]
See the config.log,  it had an error during link and can't find libdecrepit.a in boringssl-static/target/boringssl-chromium-stable/build/decrepit.

**Comment by Chenhaoqing** [comment]
HI @jiameixie ，can you share the solution to this issue?
