### ISSUE TITLE
Build support for s390x 

### ISSUE THREAD

**Issue by Nayana-ibm** [netty/netty-tcnative#501]
We could build netty-tcnative on s390x platform. Would like to add "[How to build on s390x](https://github.com/linux-on-ibm-z/docs/wiki/Building-netty-tcnative)"  link  on Wiki page here : https://netty.io/wiki/forked-tomcat-native.html#wiki-h2-7

Could you please let us know what is the best way to do it? Should we raise PR on 
https://github.com/netty/netty.github.com/blob/master/wiki/forked-tomcat-native.html  ?

Or I can also see "Edit" option here https://github.com/netty/netty/wiki/Forked-Tomcat-Native. Can we edit here?

**Comment by normanmaurer** [comment]
@Nayana-ibm just edit the wiki... Thanks a lot!
