### ISSUE TITLE
Build support for s390x - cont #501

### ISSUE THREAD

**Issue by Nayana-ibm** [netty/netty-tcnative#506]
As suggested in https://github.com/netty/netty-tcnative/issues/501, I have updated wiki for s390x support here  https://github.com/netty/netty/wiki/Forked-Tomcat-Native ( see : **Building on Linux (s390x)** section) 

However it's not reflecting on main page https://netty.io/wiki/forked-tomcat-native.html#wiki-h3-14

Also `Table of contents `not showing option to build on Linux (s390x)

**Comment by normanmaurer** [comment]
@Nayana-ibm thanks a lot... I just redeployed the site and now its reflected :)
