### ISSUE TITLE
Error building BoringSSL in a ubi based docker container.

### ISSUE THREAD

**Issue by rashmi-ibm** [netty/netty-tcnative#507]
System Info:-
Linux 56357fb4c265 3.10.0-1062.el7.ppc64le #1 SMP Thu Jul 18 20:29:07 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

Info:-
main:
     [echo] Building BoringSSL
    [mkdir] Created dir: /test/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build
     [exec] -- The C compiler identification is GNU 8.3.1
     [exec] -- Check for working C compiler: /usr/bin/cc
     [exec] -- Check for working C compiler: /usr/bin/cc -- works
     [exec] -- Detecting C compiler ABI info
     [exec] -- Detecting C compiler ABI info - done
     [exec] -- Detecting C compile features
     [exec] -- Detecting C compile features - done
     [exec] -- The CXX compiler identification is GNU 8.3.1
     [exec] -- Check for working CXX compiler: /usr/bin/c++
     [exec] -- Check for working CXX compiler: /usr/bin/c++ -- works
     [exec] -- Detecting CXX compiler ABI info
     [exec] -- Detecting CXX compiler ABI info - done
     [exec] -- Detecting CXX compile features
     [exec] -- Detecting CXX compile features - done
     [exec] libunwind not found. Disabling unwind tests.
     [exec] -- Found Perl: /usr/bin/perl (found version "5.26.3")
     [exec] -- Checking for module 'libunwind-generic'
     [exec] --   Package 'libunwind-generic', required by 'virtual:world', not found
     [exec] -- The ASM compiler identification is GNU
     [exec] -- Found assembler: /usr/bin/cc
     [exec] -- Configuring done
     [exec] -- Generating done
     [exec] -- Build files have been written to: /test/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build
     [exec] [1/405] Generating ghashp8-ppc.S
     [exec] [2/405] Generating aesp8-ppc.S

Error:-
 [exec] [276/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o
     [exec] FAILED: crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o
     [exec] /usr/bin/c++  -DBORINGSSL_IMPLEMENTATION -I../third_party/googletest/include -I../crypto/../include -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wall -ggdb -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wimplicit-fallthrough -Wmissing-declarations -std=c++11 -fno-exceptions -fno-rtti -Wshadow -O3 -fno-omit-frame-pointer -Wno-error=maybe-uninitialized -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -fPIE -MD -MT crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o -MF crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o.d -o crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o -c ../crypto/cipher_extra/aead_test.cc
     [exec] ../crypto/cipher_extra/aead_test.cc: In member function 'virtual void PerAEADTest_UnalignedInput_Test::TestBody()':
     [exec] ../crypto/cipher_extra/aead_test.cc:543:54: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH + 1];
     [exec]                                                       ^
     [exec] ../crypto/cipher_extra/aead_test.cc:544:58: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t nonce[EVP_AEAD_MAX_NONCE_LENGTH + 1];
     [exec]                                                           ^
     [exec] ../crypto/cipher_extra/aead_test.cc:545:39: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t plaintext[32 + 1];
     [exec]                                        ^
     [exec] ../crypto/cipher_extra/aead_test.cc:546:32: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t ad[32 + 1];
     [exec]                                 ^
     [exec] ../crypto/cipher_extra/aead_test.cc:564:75: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t ciphertext[sizeof(plaintext) + EVP_AEAD_MAX_OVERHEAD];
     [exec]                                                                            ^
     [exec] ../crypto/cipher_extra/aead_test.cc:572:45: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t out[sizeof(ciphertext)];
     [exec]                                              ^
     [exec] ../crypto/cipher_extra/aead_test.cc: In member function 'virtual void PerAEADTest_Overflow_Test::TestBody()':
     [exec] ../crypto/cipher_extra/aead_test.cc:586:50: error: requested alignment 64 is larger than 16 [-Werror=attributes]
     [exec]    alignas(64) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH];
     [exec]                                                   ^
     [exec] cc1plus: all warnings being treated as errors
     [exec] [277/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/hkdf/hkdf_test.cc.o
     [exec] [278/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pem/pem_test.cc.o
 [exec] [277/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/hkdf/hkdf_test.cc.o
     [exec] [278/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pem/pem_test.cc.o
     [exec] [279/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/hmac_extra/hmac_test.cc.o
     [exec] [280/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/obj/obj_test.cc.o
     [exec] [281/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/evp/evp_extra_test.cc.o
     [exec] [282/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/hrss/hrss_test.cc.o
     [exec] [283/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/lhash/lhash_test.cc.o
     [exec] [284/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/bio/bio_test.cc.o
     [exec] [285/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/fipsmodule/aes/aes_test.cc.o
     [exec] [286/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/poly1305/poly1305_test.cc.o
     [exec] [287/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/evp/evp_test.cc.o
     [exec] [288/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pkcs8/pkcs8_test.cc.o
     [exec] [289/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/refcount_test.cc.o
     [exec] [290/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/rand_extra/rand_test.cc.o
     [exec] [291/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/fipsmodule/ecdsa/ecdsa_test.cc.o
     [exec] [292/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pool/pool_test.cc.o
     [exec] [293/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pkcs7/pkcs7_test.cc.o
     [exec] [294/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/pkcs8/pkcs12_test.cc.o
     [exec] [295/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/bytestring/bytestring_test.cc.o
     [exec] [296/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/fipsmodule/ec/ec_test.cc.o
     [exec] [297/405] Building CXX object crypto/CMakeFiles/crypto_test.dir/fipsmodule/bn/bn_test.cc.o
     [exec] ninja: build stopped: subcommand failed.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty/TomcatNative [Parent] 2.0.28.Final-SNAPSHOT:
[INFO]
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [  2.977 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. SUCCESS [ 19.436 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. SUCCESS [03:48 min]
[INFO] Netty/TomcatNative [BoringSSL - Static] ............ FAILURE [01:21 min]
[INFO] Netty/TomcatNative [LibreSSL - Static] ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:32 min
[INFO] Finished at: 2019-11-12T10:56:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-boringssl) on project netty-tcnative-boringssl-static: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec resolveexecutable="true" failonerror="true" dir="/test/netty-tcnative/boringssl-static/target/boringssl-chromium-stable/build" executable="ninja"/>... @ 50:164 in /test/netty-tcnative/boringssl-static/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-tcnative-boringssl-static
bash-4.4#

**Comment by normanmaurer** [comment]
@rashmi-ibm please provide steps to reproduce... and also please verify with BoringSSL devs that it is supported at all.

**Comment by rashmi-ibm** [comment]
@normanmaurer Below are the detailed steps that i followed.

1. Created a docker container using ubi8 image 
eg. docker run --name test_container -it registry.access.redhat.com/ubi8:latest  /bin/bash

2. Install necessary libraries
yum update -y 
yum -y install gcc-c++.ppc64le wget git openssl-devel.ppc64le cmake.ppc64le cmake3.ppc64le

yum -y install java-11-openjdk-devel

yum -y install ninja-build-1.7.2-2.el7.ppc64le golang autoconf automake libtool make tar glibc-devel libaio-devel openssl-devel apr-devel lksctp-tools apr-devel apr-util-devel

3. Installed maven
bash-4.2#  wget https://www-eu.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz


bash-4.2# tar xzf apache-maven-3.6.2-bin.tar.gz
bash-4.2# ln -s apache-maven-3.6.2 /maven
bash-4.2# export M2_HOME=/maven
bash-4.2# export PATH=${M2_HOME}/bin:${PATH}

bash-4.2# export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.5.10-0.el7_7.ppc64le
bash-4.2# mvn --version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /maven
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.5.10-0.el7_7.ppc64le
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.27.2.el7.ppc64le", arch: "ppc64le", family: "unix"
bash-4.2#

4. Build ninja
git clone https://github.com/ninja-build/ninja.git
cd ninja && ./configure.py --bootstrap
export PATH=$PATH:/ninja/

5. Build netty-tcnative
git clone https://github.com/netty/netty-tcnative

cd netty-tcnative

if grep 'http://archive.apache.org' pom.xml
then
    sed -i 's/http:\/\/archive.apache.org/https:\/\/archive.apache.org/g' pom.xml
fi

if grep 'executable=\"cmake\"' boringssl-static/pom.xml
then
    sed -i 's/executable="cmake"/executable="cmake3"/g' boringssl-static/pom.xml
fi

if grep 'executable=\"cmake\"' libressl-static/pom.xml
then
    sed -i 's/executable="cmake"/executable="cmake3"/g' libressl-static/pom.xml
fi

sed -i 's/executable="cmake"/executable="cmake3"/g' boringssl-static/pom.xml
sed -i 's/executable="cmake"/executable="cmake3"/g' libressl-static/pom.xml


mvn clean install

**Comment by zethexx** [comment]
Hi, I see that you are building for ppc64le. I had the same problems while compiling boringssl for aarch64 and came across this issue via an internet search.

I recommend that you try [this patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/boringssl/0004-fix-alignment-for-ppc64le.patch?expand=1) from openSUSE. There was a [similar patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/boringssl/0001-crypto-Fix-aead_test-build-on-aarch64.patch?expand=1&rev=2e687298f449f413e53f4cb6dfdf8da7) which solved alignment for my architecture (aarch64). I believe it will solve your issues.

**Comment by normanmaurer** [comment]
@zethexx @rashmi-ibm you should try to get this accepted upstream for BoringSSL as we dont want to apply patches ourselves. /cc @davidben

**Comment by rashmi-ibm** [comment]
sure thanks @zethexx .
