### ISSUE TITLE
tcn_ssl_ctxt_t->cb_data null checks and tcn_password_callback

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#51]
It is common practice whenever `tcn_ssl_ctxt_t->cb_data` is used to check for `NULL`, and if `NULL` to then use a temporary variable which is set to `tcn_password_callback`.  It seems like `tcn_ssl_ctxt_t->cb_data` should be set in `sslcontext.c`'s `make` method by the `SSL_CTX_set_default_passwd_cb_userdata` method.  Are these `NULL` checks and temporary variables necessary?

**Comment by normanmaurer** [comment]
Actually this was fixed in the master branch. Closing this now
