### ISSUE TITLE
netty-tcnative platform specific jar not available for ppc64le

### ISSUE THREAD

**Issue by rashmi-ibm** [netty/netty-tcnative#510]
The mvn repository doesn't have the ppc64le platform specific jar listed for netty-tcnative.
Using the netty-tcnative-<version>.Final.jar  gives errors.
Can the power specific jar be published?

**Comment by rashmi-ibm** [comment]
Can I help to share the power specific jar for netty-tcnative and then it can be available on the mvn repo link https://repo1.maven.org/maven2/io/netty/netty-tcnative/

**Comment by normanmaurer** [comment]
@rashmi-ibm no... we will need to make this part of our release process.

**Comment by rashmi-ibm** [comment]
@normanmaurer any timeline by when this can be achieved as part of the release process.

**Comment by normanmaurer** [comment]
No... sorry.

**Comment by rashmi-ibm** [comment]
@normanmaurer I could help testing the power specific jar on travis or jenkins CI if available. As when I built the netty-tcnative jar on linux_ppc64le architecture I dint have to do any code changes and it worked smoothly.

**Comment by normanmaurer** [comment]
We don't plan to add support for this. That said if we could make it work via GitHub action we can reconsider. PRs welcome
