### ISSUE TITLE
sslcontext.c load_pem_key method looping

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#52]
The load_pem_key method in sslcontext.c has a loop to call `PEM_read_bio_PrivateKey` 3 times (or until success).  Why is this loop necessary, and why 3 iterations?  We should at least clarify this situation with comments.

**Comment by Scottmitch** [comment]
@normanmaurer - FYI. Lets update this to link to mention new code in the future.

**Comment by normanmaurer** [comment]
Let me fix this

**Comment by normanmaurer** [comment]
Just noticed I forgot to close this one.
