### ISSUE TITLE
Crash (Symbol not found: ____chkstk_darwin) under some versions of macOS

### ISSUE THREAD

**Issue by jchambers** [netty/netty-tcnative#523]
After updating to the latest version of ~netty-tcnative~ netty-tcnative-boringssl-static, our Travis CI builds for macOS started reporting crashes. I've narrowed the problem down to ~netty-tcnative~ netty-tcnative-boringssl-static 2.0.27 (2.0.26 is fine, and the version of Netty itself doesn't seem to matter).

I've created a minimal reproduction case here: https://github.com/jchambers/netty-tcnative-travis-test. The problem seems to happen when the client and server attempt a TLS handshake. I'll continue to narrow the problem space.

Here are the details of the Travis instance experiencing the crash:

```
$ java -Xmx32m -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

$ javac -J-Xmx32m -version
javac 1.8.0_112

$ uname -a
Darwin Traviss-Mac-463.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

Travis [reports the following](https://travis-ci.org/jchambers/netty-tcnative-travis-test/jobs/649105936) when things go south:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/libnetty_tcnative_osx_x86_648800677716316437175.dylib
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/libnetty_tcnative_osx_x86_648800677716316437175.dylib
  Expected in: /usr/lib/libSystem.B.dylib
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/libnetty_tcnative_osx_x86_648800677716316437175.dylib
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/libnetty_tcnative_osx_x86_648800677716316437175.dylib
  Expected in: /usr/lib/libSystem.B.dylib
/bin/sh: line 1:  1443 Abort trap: 6           /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/bin/java -jar /Users/travis/build/jchambers/netty-tcnative-travis-test/target/surefire/surefirebooter6882775787343813136.jar /Users/travis/build/jchambers/netty-tcnative-travis-test/target/surefire/surefire8113115051640716633tmp /Users/travis/build/jchambers/netty-tcnative-travis-test/target/surefire/surefire_08398107402907887457tmp
```

**Comment by normanmaurer** [comment]
I wonder if it is the same as 

https://github.com/netty/netty-tcnative/issues/509

Can you try 2.0.28.Final ?

**Comment by jchambers** [comment]
> Can you try 2.0.28.Final ?

The problem persists with 2.0.28.Final.

**Comment by jchambers** [comment]
I've narrowed this down a little further; the problem seems to be in the server SSL context:

| Client SSL provider | Server SSL provider | Crashes? |
|---------------------|---------------------|----------|
| `OPENSSL`           | `OPENSSL`           | Yes      |
| `JDK`               | `OPENSSL`           | Yes      |
| `OPENSSL`           | `JDK`               | No       |
| `JDK`               | `JDK`               | No       |

**Comment by jchambers** [comment]
I also expanded the Travis build matrix to cover [every version of Xcode they support](https://docs.travis-ci.com/user/reference/osx/). [The results](https://travis-ci.org/jchambers/netty-tcnative-travis-test/builds/649202660) suggest this is a problem with either Xcode 10.1 (but not 10.2!) and older or macOS 10.13 and older.

**Comment by normanmaurer** [comment]
@jchambers so just so I understand it right... you are building netty-tcnative yourself on travis and then try to use it ?

**Comment by normanmaurer** [comment]
If this is the case it could are a compiler / Xcode bug and so similar to what I have linked https://github.com/netty/netty-tcnative/issues/509. This was also caused by a compiler bug :/

**Comment by jchambers** [comment]
> so just so I understand it right... you are building netty-tcnative yourself on travis and then try to use it ?

No—sorry. I'm using the pre-built netty-tcnative-boringssl-static from Maven Central. The [test case](https://github.com/jchambers/netty-tcnative-travis-test) I mentioned earlier brings in netty-tcnative-boringssl-static as a dependency, then has a bare-bones Netty TLS [client](https://github.com/jchambers/netty-tcnative-travis-test/blob/master/src/main/java/com/eatthepath/netty/Client.java) connect to a bare-bones Netty TLS [server](https://github.com/jchambers/netty-tcnative-travis-test/blob/master/src/main/java/com/eatthepath/netty/Server.java). The crash happens under macOS 10.13 and older using the Netty/netty-tcnative artifacts from Maven Central.

Some clarifications on points that I realize may have led to confusion earlier:

1. We discovered this problem when updating Pushy to the latest version of Netty and netty-tcnative (see https://github.com/relayrides/pushy/pull/738). We were surprised to see a straightforward version bump causing reliable crashes in our tests.
2. Travis is involved in this case because (a) that's where we discovered the problem and (b) I don't have a great way to test with a wide range of macOS versions otherwise.
3. The mention of Xcode versions earlier is likely a red herring; that's how Travis identifies its build environments (which makes sense for a CI system), but I expect the important detail is actually the version of macOS to which the various versions of Xcode are bound.

**Comment by normanmaurer** [comment]
@jchambers sorry but I am still confused... When you first reported it you said you are using netty-tcnative (not netty-tcnative-boringssl-static). So can you clarify which one it is ? 

I will try to debug this further but can say that I never saw a crash before with netty-tcnative-boringssl-static 2.0.28.Final on macOS. That said I dont think I ever tested the new releases with 10.13. From my understanding it only happens on macOS 10.13 and earlier. Correct ?

**Comment by normanmaurer** [comment]
@jchambers I may have any idea what's going on.... Working on a PR now. Could you somehow test this one once Its ready ?

**Comment by jchambers** [comment]
> When you first reported it you said you are using netty-tcnative (not netty-tcnative-boringssl-static).

Sorry—I was imprecise earlier. It is, indeed, netty-tcnative-boringssl-static.

> From my understanding it only happens on macOS 10.13 and earlier. Correct ?

To the best of my knowledge, that's correct.

> Could you somehow test this one once Its ready ?

I'll do my best. I think that means I'll need to find a way to get Travis to build netty-tcnative-boringssl-static locally, which may take some iteration. Happy to give it a shot, though!

**Comment by normanmaurer** [comment]
@jchambers ok perfect... I hope to have a PR later today (already working on it)

**Comment by normanmaurer** [comment]
@jchambers PTAL https://github.com/netty/netty-tcnative/pull/527

**Comment by gemmellr** [comment]
I am also seeing a test crash on Travis with OSX (10.13, xcode 9.2, JDK 8+112) after updating to netty-tcnative-boringssl-static 2.0.28 (from 2.0.26, which worked ok). I haven't investigated as much as Jon, but it appeared to crash at the first test that attempts to connect with client certs required (the server in that case isnt using Netty, just the client).

Updating the job to use the earliest Travis image with OSX 10.14 (xcode10.2 image, with Xcode 10.2.1 and jdk 13.0.1+9 [despite doc saying it is 12+33]) gets the tests passing again with 2.0.28.

**Comment by normanmaurer** [comment]
@jchambers @gemmellr 2.0.29.Final was released and fixed the problem 🎉

**Comment by gemmellr** [comment]
Thanks Norman, just updated :)

**Comment by jchambers** [comment]
🤘 

Thank you!

**Comment by normanmaurer** [comment]
@gemmellr @jchambers no problem... thanks a lot for all the help debugging the problem :)
