### ISSUE TITLE
Unable to load the library 'io_grpc_netty_shaded_netty_tcnative_windows_x86_64', trying other loading mechanism.

### ISSUE THREAD

**Issue by raviprakashmishra** [netty/netty-tcnative#529]
I am using io.grpc:grpc-netty-shaded:1.13.1 in my java application and on start up it gives debug level errors before finally extracting and loading the 'io_grpc_netty_shaded_netty_tcnative_windows_x86_64' from temp folder in windows.

Though loading is eventually successful but it's irritating to see so many stack trace logging at the debug level as well. And every time application comes up a dll is extracted to temp folder increasing the temp folder size unnecessarily.

What is the correct java.library.path to look for the 'io_grpc_netty_shaded_netty_tcnative_windows_x86_64' so that it succeeds i n first attempt.

**Comment by normanmaurer** [comment]
I think we fixed this in netty. Closing
