### ISSUE TITLE
Black screen when connecting to Ubuntu agent's screen.

### ISSUE THREAD

**Issue by ThatDomio** [netty/netty-tcnative#538]
When I try to connect to the agent's screen, it's completely black, but I can move the cursor. It was working fine when I had the computer connected to a monitor before it booted up so maybe it didn't detect a monitor and that is somehow causing the problem.
I hope this is the right place to post this as there seems to be no DWService forum. This is my first time using Ubuntu, DWService, and Github so please be understanding.

**Comment by normanmaurer** [comment]
It’s not ... this is for netty-tcnative

**Comment by chrisvest** [comment]
This is not relevant to netty-tcnative at all.
