### ISSUE TITLE
1.1.33.Fork4+: Unable to load openssl on OS X (Homebrew installed openssl)

### ISSUE THREAD

**Issue by bobwenx** [netty/netty-tcnative#54]
```java
java.lang.UnsatisfiedLinkError: /private/var/folders/5f/jc_d179x0qlbhm0kzxlssyl00000gn/T/libnetty-tcnative4749163000461898953.dylib: dlopen(/private/var/folders/5f/jc_d179x0qlbhm0kzxlssyl00000gn/T/libnetty-tcnative4749163000461898953.dylib, 1): Library not loaded: /usr/local/lib/libssl.1.0.0.dylib
  Referenced from: /private/var/folders/5f/jc_d179x0qlbhm0kzxlssyl00000gn/T/libnetty-tcnative4749163000461898953.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822) ~[na:1.8.0_45]
	at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_45]
	at java.lang.System.load(System.java:1086) ~[na:1.8.0_45]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) ~[netty-all-4.1.0.Beta6-20150726.163256-175.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:58) ~[netty-all-4.1.0.Beta6-20150726.163256-175.jar:4.1.0.Beta6-SNAPSHOT]
```

When using `1.1.33.Fork3` with netty `4.1.0.Beta6-SNAPSHOT` on OS X. there is no exception thrown.

openssl version: `1.0.2d_1` (installed by homebrew)
openssl path: `/usr/local/opt/openssl/lib`

**Comment by normanmaurer** [comment]
Which openssl version?

**Comment by bobwenx** [comment]
OS X Default:
```
/usr/bin/openssl version
OpenSSL 0.9.8zf 19 Mar 2015
```

Homebrew installed OpenSSL:
```
/usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by bobwenx** [comment]
if i switch to `1.1.33.Fork3`, there is no problems to load `/usr/local/opt/openssl/lib/libssl`

**Comment by doom369** [comment]
Same here, but on Ubuntu.
I was using netty 4.0.28 with OpenSSL  and netty-tcnative-1.1.32.Fork1. I builded netty-tcnative from sources and all was working fine. Now I switched to 4.0.30 and netty-tcnative-1.1.33.Fork4, repeated all steps and getting :

```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative15237136205374948.so: libssl.so.10: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```

**Comment by normanmaurer** [comment]
@doom369 that is strange... did you follow this?:

http://netty.io/wiki/forked-tomcat-native.html#wiki-h4-4

**Comment by doom369** [comment]
@normanmaurer I didn't build and install OpenSSL if you mean that, I just builded tcnative from sources.

**Comment by Scottmitch** [comment]
@doom369 - So you did follow the instructions linked by @normanmaurer, and still had an issue? If so can you describe at which point in the instructions you encountered the issue?

**Comment by doom369** [comment]
@Scottmitch here is steps I did on my VM with Ubuntu with netty 4.0.28 :

```
sudo apt-get install git
sudo apt-get install autoconf automake libtool make tar libapr1-dev libssl-dev
git clone https://github.com/netty/netty-tcnative.git
cd netty-tcnative
git checkout netty-tcnative-1.1.32.Fork1
mvn clean install
```
Everything was working fine. 

Recently I saw new netty version release and switched to 4.0.30 and switched dependencies in my POM to 1.1.33.Fork4 for tcnative and repeated steps above with only 1 change :
```
git checkout netty-tcnative-1.1.33.Fork4
```

After that I started getting above exceptions after running my jar. I could make you builds if that helps. My project is open-sourced.

**Comment by bobwenx** [comment]
After upgrade `netty-tcnative` to `1.1.33.fork5`. i am able to load `OpenSSL` again!

`23:50:57.260 [main] DEBUG io.netty.handler.ssl.OpenSslContext[71] - Default cipher suite (OpenSSL): [ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA, ECDHE-RSA-AES256-SHA, AES128-GCM-SHA256, AES128-SHA, AES256-SHA, DES-CBC3-SHA]
`

**Comment by normanmaurer** [comment]
@doom369 what about you ?

**Comment by normanmaurer** [comment]
I think we can close this now

**Comment by doom369** [comment]
@normanmaurer sorry, was a bit busy. Tried latest 4.0.32.Final and 1.1.33.Fork8 - works like a charm. Thank you!
