### ISSUE TITLE
Clarify licensing of bundled, statically-linked boringssl

### ISSUE THREAD

**Issue by patricklucas** [netty/netty-tcnative#543]
We are building a Java application using gRPC, and our dependency `io.grpc:grpc-netty` depends on the artifact `netty-tcnative-boringssl-static` from this project.

From my understanding, boringssl when compiled includes code licensed under the [OpenSSL, MIT, and ISC licenses](https://boringssl.googlesource.com/boringssl/+/refs/heads/master/LICENSE). However, while the OpenSSL and MIT licenses have requirements for downstream users to propagate their license information when distributed, neither this repo[1] nor the published `netty-tcnative-boringssl-static` artifacts[2] appear to include a NOTICE file that fulfills this requirement.

Could you clarify the licensing situation here? If you think the status quo is fine, it would be helpful to have it written down in case someone else has the same question, and if some action is required it would be good to resolve it as soon as possible.

Thanks,
Patrick

[1][NOTICE.txt](https://github.com/netty/netty-tcnative/blob/master/NOTICE.txt) does not mention boringssl
[2][2.0.30.Final.jar](https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.30.Final/netty-tcnative-boringssl-static-2.0.30.Final.jar) on Maven Central

**Comment by normanmaurer** [comment]
@patricklucas I think you are right and we should include something in the NOTICE.txt file... sorry that it took so long :/ Are you able to provide a PR ? If not I will do it some time this week.

**Comment by patricklucas** [comment]
Thanks for the response @normanmaurer. Unfortunately I don't think I'm qualified to make the necessary changes—I really don't know exactly what is required per the upstream licenses.

I do think it's likely that something needs to be both added to the NOTICE file as well as packaged in the distributed jar. Perhaps it's enough to just forward the NOTICE file in the jar?

**Comment by normanmaurer** [comment]
From my understanding it would be good enough to just adjust the NOTICE file in the repos.

**Comment by normanmaurer** [comment]
@patricklucas See https://github.com/netty/netty-tcnative/pull/559

**Comment by patricklucas** [comment]
In the linked LICENSE file, the OpenSSL license claims:

> Redistributions in binary form must reproduce the above copyright
> notice, this list of conditions and the following disclaimer in
> the documentation and/or other materials provided with the
> distribution.

which makes me think that this needs to be included _somewhere_ alongside the distribution itself.

A somewhat related example could be `flink-shaded-netty`[1], which bundles a binary distribution of Netty while including the following files under `META-INF`:

`META-INF/DEPENDENCIES`:

```
// ------------------------------------------------------------------
// Transitive dependencies of this project determined from the
// maven pom organized by organization.
// ------------------------------------------------------------------

flink-shaded-netty-4


From: 'The Netty Project' (https://netty.io/)
  - Netty/All-in-One (https://netty.io/netty-all/) io.netty:netty-all:jar:4.1.39.Final
    License: Apache License, Version 2.0  (http://www.apache.org/licenses/LICENSE-2.0)
```

`META-INF/NOTICE`:

```
// ------------------------------------------------------------------
// NOTICE file corresponding to the section 4d of The Apache License,
// Version 2.0, in this case for Apache Flink-shaded
// ------------------------------------------------------------------

Apache Flink-shaded
Copyright 2006-2020 The Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).

flink-shaded-netty
Copyright 2014-2018 The Apache Software Foundation

This project includes software developed at
The Apache Software Foundation (http://www.apache.org/).

This project bundles the following dependencies under the Apache Software License 2.0 (http://www.apache.org/licenses/LICENSE-2.0.txt)

- io.netty:netty-all:4.1.39.Final
```

[1][4.1.39.Final-11.0.jar on Maven Central](https://repo1.maven.org/maven2/org/apache/flink/flink-shaded-netty/4.1.39.Final-11.0/flink-shaded-netty-4.1.39.Final-11.0.jar)

**Comment by normanmaurer** [comment]
Let me just add the NOTICE to the META-INF as well and call it a day in #559

**Comment by patricklucas** [comment]
Sounds good, I think that should cover our bases. Thanks.
