### ISSUE TITLE
Incorrect classifier "aarch_64" for aarch64 builds in pom files

### ISSUE THREAD

**Issue by geoffreyblake** [netty/netty-tcnative#546]
Saw this in the netty code and it was fixed by @normanmaurer, looks like it is here as well and will probably prevent the next release from containing aarch64 binaries.

https://github.com/netty/netty-tcnative/blob/698b5aed770e9dccb06022ce0d64b20684daefd3/boringssl-static/pom.xml#L714

**Comment by normanmaurer** [comment]
@geoffreyblake PR's welcome

**Comment by geoffreyblake** [comment]
Created https://github.com/netty/netty-tcnative/pull/547 to fix the typo.

**Comment by johnou** [comment]
We can close this issue.
