### ISSUE TITLE
Need netty-tcnative aarch64 package on maven

### ISSUE THREAD

**Issue by wangxiyuan** [netty/netty-tcnative#552]
We supported cross compile about aarch64 for netty-tcnative in 2.0.31. But there is no aarch64 jar file on maven. 

https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.31.Final/

I built it locally with the docker file on master branch. It works. The jar is named `netty-tcnative-2.0.32.Final-SNAPSHOT-linux-aarch64.jar`. Does community forget it? Or I missed something about release things? Do I need a new PR for it?

Thanks.

**Comment by johnou** [comment]
@wangxiyuan https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.31.Final/

**Comment by johnou** [comment]
but yeah looks like the the netty-tcnative artifact is missing..

**Comment by wangxiyuan** [comment]
yeah, netty-tcnative-boringssl-static looks good.  While `netty-tcnative` which is from `openssl-dynamic`  is missing.

**Comment by normanmaurer** [comment]
@wangxiyuan I thought we only need the boringssl based one and so I only releases this one. If this is not the case I can also include the  openssl-dynamic artefact the next time.

**Comment by wangxiyuan** [comment]
@normanmaurer Thanks for your quick reply.  

For my case, I want to upgrade Apache Flink to support aarch64 which shaded netty-tcnative. 
https://github.com/apache/flink-shaded/blob/master/flink-shaded-netty-tcnative-dynamic/pom.xml#L95

I'm not sure if others want it or not. Can we leave this issue open for a while to get more feedback?

**Comment by Storm-Born** [comment]
I have the similar problem like you. when I run my jar on a x86_64 machine, it works ok. but when running the jar on a arm64 machine.  exception happened and seems like missing library tc-native_arrch64 balabalabala. I use the artifact

<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.30.Final</version>
        </dependency>

in my pom.xml
is there any solution?

**Comment by johnou** [comment]
@Storm-Born deploy the correct tc-native arch artefact to the arm64 machine.

**Comment by Storm-Born** [comment]
> @Storm-Born deploy the correct tc-native arch artefact to the arm64 machine.

sorry, can you give me the correct maven artifact.

I use this one found from the examples.

            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.30.Final</version>

**Comment by martin-g** [comment]
You need 2.0.31.Final, not .30

**Comment by odidev** [comment]
I am also trying to use netty-tcnative for product-microgateway .
My pom.xml file for netty look like this 
```
<groupId>io.netty</groupId>
<artifactId>netty-tcnative-boringssl-static</artifactId>
<version>2.0.31.Final</version>
```
I am getting the following error:

>  java.lang.UnsatisfiedLinkError message=failed to load the required native library cause=error java.lang.IllegalArgumentException message=Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64, netty_tcnative_linux_aarch_64_fedora, netty_tcnative_aarch_64, netty_tcnative]

please suggest if I am doing anything wrong here

**Comment by martin-g** [comment]
@odidev you need to add `<classifier>linux-aarch64</classifier>` to the `<dependency>`

**Comment by odidev** [comment]
Hi All,

Aarch64 jar for openssl-dynamic  is also needed for Lettuc package, which is currently not present in maven repo.
Request you to please release openssl-dynamic artifact for aarch64 in maven repo.

**Comment by wangxiyuan** [comment]
https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.32.Final/ Good to know that it supports arm64 from 2.0.32. But I assume it's only for fedora? Is there any blocker for common aarch64 release? Or I missed something?

**Comment by martin-g** [comment]
The `-fedora` part to the classifier comes from https://github.com/netty/netty-tcnative/commit/9cd9f45bd4941581705ace76c7713b0c1b84f640#diff-78422174cea1efe42654d2038ce1a00557e3c308610804999e06eba6fbf9f35cR129

The comment above this line says: 
```
 <!-- Adjust the classifier used for different OS distributions which provide differently-built openSSL libraries -->
```
and this makes me think that the `linux-aarch64` jar at https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.32.Final/ might have something Fedora specific.

**Comment by geoffreyblake** [comment]
There seems to a slight mis-naming in the .so for Arm64 and it can't find the so.   I've had some users tell me they've been extracting the released jar from maven and renaming `libnetty_tcnative_linux_aarch64.so` to `libnetty_tcnative_linux_aarch_64.so`, place it in the LDPATH and it ends up working.  

I'm having trouble getting the build to cross-compile currently, but I think the below diff will generate .so's with the proper name if someone could test or send me the instructions for how to cross compile.  Of course, if its possible to build natively on Arm, that would be better.

```
diff --git a/boringssl-static/pom.xml b/boringssl-static/pom.xml
index ed21bbe..9b708f4 100644
--- a/boringssl-static/pom.xml
+++ b/boringssl-static/pom.xml
@@ -378,7 +378,7 @@
         <msvcSslLibs>ssl.lib;crypto.lib;decrepit.lib</msvcSslLibs>
         <nativeJarFile>${project.build.directory}/${project.build.finalName}-${os.detected.name}-aarch64.jar</nativeJarFile>
         <jniClassifier>${os.detected.name}-aarch64</jniClassifier>
-        <jniArch>aarch64</jniArch>
+        <jniArch>aarch_64</jniArch>
       </properties>

       <build>
@@ -869,7 +869,7 @@
                     <Bundle-NativeCode>
                       META-INF/native/libnetty_tcnative_osx_${uberArch}.jnilib;osname=macos;osname=macosx;processor=${uberArch},
                       META-INF/native/libnetty_tcnative_linux_${uberArch}.so;osname=linux;processor=${uberArch},
-                      META-INF/native/libnetty_tcnative_linux_aarch64.so;osname=linux;processor=aarch64,
+                      META-INF/native/libnetty_tcnative_linux_aarch_64.so;osname=linux;processor=aarch64,
                       META-INF/native/netty_tcnative_windows_${uberArch}.dll;osname=win32;processor=${uberArch}
                     </Bundle-NativeCode>
                   </instructions>
```

**Comment by martin-g** [comment]
@geoffreyblake This partially reverts https://github.com/netty/netty-tcnative/commit/dec66306a4b35b2ed9787c57d2433ec1de0d0694#diff-9f1aa030fe8568dc7f081010d6f14b6d2c26ea2170502365e8f1ebe3f3e58607
Also see https://github.com/netty/netty-tcnative/issues/571

**Comment by geoffreyblake** [comment]
I don't seem to be able to build netty-tcnative anymore with the docker cross-compile flow.  It fails when trying to build boring-ssl.  

```
     [exec] FAILED: crypto_test_data.cc
     [exec] cd /code/boringssl-static/target/boringssl-chromium-stable && /usr/bin/go run util/embed_test_data.go -file-list /code/boringssl-static/target/boringssl-chromium-stable/build/embed_test_data_args.txt > /code/boringssl-static/target/boringssl-chromium-stable/build/crypto_test_data.cc
     [exec] go: golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9 requires
     [exec]     golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3 requires
     [exec]     golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/f72f7a6f267d2fe79b1e174efab21a591b07c84ef53364f65b8281fda7000b49: exit status 128:
     [exec]     fatal: git fetch-pack: expected shallow list
     [exec] [27/429] Building CXX object CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o
     [exec] [28/429] Building C object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o
     [exec] ninja: build stopped: subcommand failed.
```

Will make this another issue.

**Comment by sebpop** [comment]
I think the build issue has been fixed by these commits: https://github.com/netty/netty-tcnative/pull/591 and https://github.com/netty/netty/pull/10845

Can somebody verify that this bug is fixed and close?

**Comment by martin-g** [comment]
2.0.36.Final provides https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.36.Final/netty-tcnative-2.0.36.Final-linux-aarch_64-fedora.jar, i.e. `aarch_64` - the new uniform name! This is good!

One thing that still bothers me is the `-fedora` part in the classifier. Is it really needed there ? Is the binary Fefora specific ?!
I use it on Ubuntu and it works fine. I think it could be dropped.

**Comment by sebpop** [comment]
Looking at #591, the jar name is created from this template:
```
<nativeJarFile>${project.build.directory}/${project.build.finalName}-${os.detected.name}-aarch_64.jar</nativeJarFile>
```
and because the image was created from a docker container with centos-7 (to have an old enough glibc compatible with all newer Linux distros):
```
docker-compose -f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-build
```
it detects the os name as fedora.

I think it is fine to keep `-fedora` in the jar file name.

**Comment by normanmaurer** [comment]
I think this was fixed

**Comment by martin-g** [comment]
@normanmaurer What still bothers me is that the linux-aarch64 artifact still has `-fedora` in its name: https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.41.Final/netty-tcnative-2.0.41.Final-linux-aarch_64-fedora.jar
This makes it hard to use with `os-maven-plugin`. I have to do extra gymnastics in my pom.xml.
Instead of just using `<classifier>${os.detected.classifier}</classifier>` I have to add an extra Maven profile for `aarch64` to specify the extra `-fedora` thingy.
