### ISSUE TITLE
PPC64LE official release

### ISSUE THREAD

**Issue by kandarpapsl** [netty/netty-tcnative#554]
While building the vert.x for PPC64LE architecture, I found tests related to SSL were failed due to missing of 'netty-tcnative.so' file.
To fix this, I have to build the netty and netty-tcnative on my own. netty-tcnative build and all tests passed without any code changes on PPC64LE architecture.

Is it possible to provide netty-tcnative support/release for PPC64LE ?

If setup is the constraint, then we are ready to provide the PPC64LE infrastructure for build and release.

**Comment by normanmaurer** [comment]
we don't have any machines that support this architecture for now... If you can sponsor such we may be able to include it tho.

**Comment by seth-priya** [comment]
@normanmaurer thanks for your response on this! ppc64le resources can be requested as per your requirements from here https://osuosl.org/services/powerdev/request_powerci/ ( @gerrith3 , FYI for approvals)

**Comment by morvael** [comment]
I once managed to build netty on virtual PPC64LE using qemu on an AMD64 host, though it was of course terribly, horribly slow. Building on real machine is definitely faster.

**Comment by normanmaurer** [comment]
We would need to b able to build via GitHub action. Close this for now
