### ISSUE TITLE
libnetty_tcnative.so loading failes when implementations for different archs are present in classpath

### ISSUE THREAD

**Issue by undefz** [netty/netty-tcnative#555]
Test case:
Have two implementations of tcnative in classpath: linux-x86_64 and linux-aarch64.

Expected behaviour:
Library for current platform is loaded.

Actual result:
Library for current platform may fail to load because library in both jars is named libnetty_tcnative.so.
Suggested fix is to name them with os and archs specifiers (netty_tcnative_linux_aarch64).

**Comment by normanmaurer** [comment]
sounds like a good idea as we do the same anyway when creating the uber jar. Will have a look

**Comment by normanmaurer** [comment]
@undefz PTAL https://github.com/netty/netty-tcnative/pull/557
