### ISSUE TITLE
Allow configuring supported_groups extension

### ISSUE THREAD

**Issue by idelpivnitskiy** [netty/netty-tcnative#567]
When TLSv1.3 is enabled, the client sends:
```
"supported_groups (10)": {
  "versions": [x25519, secp256r1, secp384r1]
}
```
Java server prior JDK13 that uses JSSE does not support x25519 [1, 2]. As a result, the server responds with `HelloRetryRequest` selecting secp256r1. It introduces an additional round-trip for the handshake.

JSSE client by default sends:
```
"supported_groups (10)": {
  "versions": [secp256r1, secp384r1, secp521r1, ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
}
```
JDK has `jdk.tls.namedGroups` system property that allows configuring `supported_groups` [3]. Will be nice if tcnative will also have the ability to configure `supported_groups` extension [4]. We can preserve the same system property or introduce another way if JDK default will override OPENSSL default (we should verify that if `jdk.tls.namedGroups` is not set manually, openssl should use `x25519, secp256r1, secp384r1`).

Tested with JDK11.

1.  https://bugs.openjdk.java.net/browse/JDK-8217709
2. https://bugs.openjdk.java.net/browse/JDK-8171279
3. https://docs.oracle.com/en/java/javase/12/security/java-secure-socket-extension-jsse-reference-guide.html#GUID-A41282C3-19A3-400A-A40F-86F4DA22ABA9
4. https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#Elliptic-curve-Diffie-Hellman

**Comment by ramtech123** [comment]
Hi team,

Is there any alternative approach/workaround to restrict the supported_groups while using `SslProvider.OPENSSL`?
Refer my stackoverflow query at https://stackoverflow.com/questions/68779649/netty-tcnative-with-openssl-and-supported-groups-elliptic-curves

**Comment by ramtech123** [comment]
Hi @normanmaurer @trustin ,

Any thoughts/guidance on the above? Thanks in advance.

**Comment by kushalagrawal** [comment]
Hi @normanmaurer, I see that in [https://github.com/netty/netty-tcnative/blob/main/openssl-dynamic/src/main/c/sslcontext.c#L377](https://github.com/netty/netty-tcnative/blob/main/openssl-dynamic/src/main/c/sslcontext.c#L377) , Elliptic curve is being set to 256 for openssl version < 1.1.0 but there is no documentation about how to update the elliptic curve to other than 256. Something like If we need to set some property while Initializing.

`#if defined(HAVE_ECC) && (OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER))
        /* Set default (nistp256) elliptic curve for ephemeral ECDH keys */
        EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
        SSL_CTX_set_tmp_ecdh(c->ctx, ecdh);
        EC_KEY_free(ecdh);
#endif`

**Comment by kushalagrawal** [comment]
Hi @normanmaurer, any thoughts on this please?

**Comment by normanmaurer** [comment]
Yep... Looking into exposing `SSL_CTX_set1_curves`

**Comment by normanmaurer** [comment]
https://github.com/netty/netty-tcnative/pull/661
