### ISSUE TITLE
FileNotFoundException:META-INF/native/libnetty_tcnative_linux_aarch_64.so

### ISSUE THREAD

**Issue by bhtdz-zhou** [netty/netty-tcnative#576]
Hello， I tried to run a java application on  kylin 10 , arm64 and I get the error:
```
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64, netty_tcnative_linux_aarch_64_fedora, netty_tcnative_aarch_64, netty_tcnative]
| 	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
| 	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:590)
| 	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
| 	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:167)
| 	at org.hyperledger.fabric.sdk.Endpoint.getSslContextBuilder(Endpoint.java:294)
| 	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:254)
| 	... 150 common frames omitted
| 	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_aarch_64
| 		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
| 		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
| 		... 155 common frames omitted
| 	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_aarch_64.so
| 		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
| 		... 156 common frames omitted
| 		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64 in java.library.path
```
my pom.xml:
```
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.34.Final</version>
            <os.detected.classifier>linux-aarch64</os.detected.classifier>
 </dependency>
```
un zip netty-tcnative-boringssl-static-2.0.34.Final.jar 
![image](https://user-images.githubusercontent.com/29765417/95728989-c8f0d000-0cae-11eb-9388-c2d72b069a9f.png)
Any help to solve it?
Thanks in advance.

**Comment by hedehai** [comment]
@bhtdz-zhou It’s caused by file name mismatch. 
The log says it need file netty_tcnative_linux_aarch_64.so.
You can rename the file in netty-tcnative-boringssl-static-2.0.34.Final.jar!\META-INF\native\ libnetty_tcnative_linux_**aarch64.so** to libnetty_tcnative_linux_**aarch_64.so**. There is a underline before 64.

**Comment by lzwill** [comment]
@hedehai Hello, I got this error as well.
Does `renaming` is the only way to solve this problem in 2.0.34.Final version? And is this a bug?

**Comment by bhtdz-zhou** [comment]
> Hello， I tried to run a java application on kylin 10 , arm64 and I get the error:
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64, netty_tcnative_linux_aarch_64_fedora, netty_tcnative_aarch_64, netty_tcnative]
> | 	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
> | 	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:590)
> | 	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
> | 	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:167)
> | 	at org.hyperledger.fabric.sdk.Endpoint.getSslContextBuilder(Endpoint.java:294)
> | 	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:254)
> | 	... 150 common frames omitted
> | 	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_aarch_64
> | 		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
> | 		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
> | 		... 155 common frames omitted
> | 	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_aarch_64.so
> | 		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
> | 		... 156 common frames omitted
> | 		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64 in java.library.path
> ```
> 
> my pom.xml:
> 
> ```
> <dependency>
>             <groupId>io.netty</groupId>
>             <artifactId>netty-tcnative-boringssl-static</artifactId>
>             <version>2.0.34.Final</version>
>             <os.detected.classifier>linux-aarch64</os.detected.classifier>
>  </dependency>
> ```
> 
> un zip netty-tcnative-boringssl-static-2.0.34.Final.jar
> ![image](https://user-images.githubusercontent.com/29765417/95728989-c8f0d000-0cae-11eb-9388-c2d72b069a9f.png)
> Any help to solve it?
> Thanks in advance.

Thank you very much, update to 2.0.35，solve it!

**Comment by bhtdz-zhou** [comment]
> @bhtdz-zhou It’s caused by file name mismatch.
> The log says it need file netty_tcnative_linux_aarch_64.so.
> You can rename the file in netty-tcnative-boringssl-static-2.0.34.Final.jar!\META-INF\native\ libnetty_tcnative_linux_**aarch64.so** to libnetty_tcnative_linux_**aarch_64.so**. There is a underline before 64.

Thank you very much, update to 2.0.35，solve it!

**Comment by bhtdz-zhou** [comment]
update to 2.0.35，solve it!
