### ISSUE TITLE
OpenSSL version detection broken 

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#58]
Calling `OpenSsl.version()` seems to result in the version that it was compiled against. I tried building openssl and setting `LD_LIBRARY_PATH`, but it kept returning the same version (1.1.33.Fork6 seems to be built against 1.0.1e). The logic for `OpenSsl.isAlpnSupported()` is based on version, so if it's broken, ALPN support is broken as well.

It seems that tc_native is using a macro to get the value: https://github.com/netty/netty-tcnative/blob/be811aeb61eb989724be54f1cb7d9a9969302e27/src/main/c/ssl.c#L273.  I tried switching to using methods:

```c
// From my local ssl.c...
TCN_IMPLEMENT_CALL(jint, SSL, version)(TCN_STDARGS)
{
    UNREFERENCED_STDARGS;
    fprintf(stderr, "NM: in new code");
    return (jint) SSLeay();
}

TCN_IMPLEMENT_CALL(jstring, SSL, versionString)(TCN_STDARGS)
{
    UNREFERENCED(o);
    fprintf(stderr, "NM: in new code");
    return AJP_TO_JSTRING(SSLeay_version(SSLEAY_VERSION));
}
```
However I still see the same problem.  I had considered that the method may have been inlined, but it appears that the definition is in a c file (https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/crypto/cversion.c#L104), so that should work.

Any ideas?

@Scottmitch @normanmaurer

**Comment by normanmaurer** [comment]
@nmittler no ideas yet but will look into it.

**Comment by nmittler** [comment]
@normanmaurer I wrote a simple c program and it looks like the change works after all.

```c
#include <stdio.h>
#include <openssl/crypto.h>

int main()
{
  printf("%ld, %s\n", OPENSSL_VERSION_NUMBER, OPENSSL_VERSION_TEXT);
  printf("%ld, %s\n", SSLeay(), SSLeay_version(SSLEAY_VERSION));
}
```
When built against 1.0.2d but run against 1.0.1p, generates the following:

```
268443727, OpenSSL 1.0.2d 9 Jul 2015
268439823, OpenSSL 1.0.1p 9 Jul 2015
```

So I think we should probably fix this in netty-tcnative and then backport the change (if it still applies) to tcnative.  WDYT?

**Comment by normanmaurer** [comment]
@nmittler looks good... Should I take care or you will submit a PR ?

**Comment by nmittler** [comment]
I'll submit a PR shortly

**Comment by nmittler** [comment]
@normanmaurer @Scottmitch @ejona86 I've verified locally that Netty's `OpenSsl.isAlpnSupported()` now correctly indicates ALPN support in the runtime version of OpenSSL!

**Comment by Scottmitch** [comment]
Good work @nmittler and thanks for the patch!
