### ISSUE TITLE
Native SSL provider not available; will use JDK SSL provider.

### ISSUE THREAD

**Issue by huiqingduan** [netty/netty-tcnative#589]
When creating apnsclient, you will be prompted to solve this problem. Tha

nk you；

**Comment by huiqingduan** [comment]
`<dependency>
            <groupId>com.eatthepath</groupId>
            <artifactId>pushy</artifactId>
            <version>0.14.2</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.34.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <version>2.0.34.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>4.1.52.Final</version>
        </dependency>`

**Comment by hyperxpro** [comment]
Can you explain a little better?

**Comment by normanmaurer** [comment]
Will close as there are not enough informations
