### ISSUE TITLE
Mac m1 support (osx-aarch_64 classifier)

### ISSUE THREAD

**Issue by mortenlocka** [netty/netty-tcnative#596]
Hi,

Using the new Intellij beta for osx ARM. The maven-os-plugin resolves to osx-aarch_64.

Any chance that you will support this classifier in the near future?

Thanks!

(Everything works fine via rosetta.  Maven/the current intellij release. Resolves to osx-x86_64 as expected)

**Comment by normanmaurer** [comment]
@mortenlocka you should open an issue in the maven plugin project:

https://github.com/trustin/os-maven-plugin

/cc @trustin
