### ISSUE TITLE
Consider adding support for certificate compression (TLSv1.3)

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-tcnative#614]
https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#Certificate-compression

**Comment by CamW** [comment]
I am interested in working on this. Is it something you would like to add support for?

If so, it seems to me that dynamically linking and loading native compression libraries might be a good approach. To avoid the bloat of statically linking and the call to java for compression.
Any thoughts on that?

**Comment by normanmaurer** [comment]
@CamW I think it would be better to do the compression in a java callback to miminize trouble :)
