### ISSUE TITLE
BoringSSL does not support des_read_pw_string

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#63]
Currently, sslutils.c has the [following code](https://github.com/netty/netty-tcnative/blob/1.1.33/src/main/c/sslutils.c#L135):

```c
#ifdef WIN32
        rv = WIN32_SSL_password_prompt(data);
#elif !defined(OPENSSL_IS_BORINGSSL)
        EVP_read_pw_string(data->password, SSL_MAX_PASSWORD_LEN,
                           data->prompt, 0);
#else
        des_read_pw_string(data->password, SSL_MAX_PASSWORD_LEN,
                           data->prompt, 0);
#endif
``` 

This would have `des_read_pw_string` called in the BoringSSL case, which does not exist.  I suspect that this builds for some developers because the include may be getting pulled in from openssl.  Not entirely sure.

**Comment by Scottmitch** [comment]
+1. The `#else` condition should "fail" some how. Return a "failure" status or throw an exception because it is not supported for boringssl.
