### ISSUE TITLE
UnsatisfiedLinkError': io.netty.internal.tcnative.NativeStaticallyReferencedJniMethods.sslSessCacheClient

### ISSUE THREAD

**Issue by Rainlone** [netty/netty-tcnative#634]
use netty-tcnative-boringssl-static-2.0.31.Final.jar:

Event: 50.160 Thread 0x0000fffd9707e800 Exception <a 'java/lang/UnsatisfiedLinkError': io.netty.internal.tcnative.NativeStaticallyReferencedJniMethods.sslSessCacheClient()I> (0x0000000489bf8c70) thrown at [/usr1/jenkins/workspace/JDK8u-Euler2.8-Aarch64-build/open_source/openjdk/cd

Stack: [0x0000fffd173e1000,0x0000fffd175e1000],  sp=0x0000fffd175ddf30,  free space=2035k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000fffe3003cf80
j  io.netty.internal.tcnative.Library.initialize(Ljava/lang/String;Ljava/lang/String;)Z+31
j  io.netty.handler.ssl.OpenSsl.initializeTcNative(Ljava/lang/String;)Z+3
j  io.netty.handler.ssl.OpenSsl.<clinit>()V+225
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6bfc7c]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xe54
V  [libjvm.so+0x661344]  InstanceKlass::call_class_initializer_impl(instanceKlassHandle, Thread*)+0xac
V  [libjvm.so+0x661808]  InstanceKlass::initialize_impl(instanceKlassHandle, Thread*)+0x418
V  [libjvm.so+0x661adc]  InstanceKlass::initialize(Thread*)+0x74
V  [libjvm.so+0x7f36a8]  LinkResolver::resolve_static_call(CallInfo&, KlassHandle&, Symbol*, Symbol*, KlassHandle, bool, bool, Thread*)+0x3b8
V  [libjvm.so+0x7f5460]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle, int, Thread*)+0x420
V  [libjvm.so+0x7fc83c]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle, int, Bytecodes::Code, Thread*)+0x1d4
V  [libjvm.so+0x6ae3a0]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x450
j  io.vertx.core.net.OpenSSLEngineOptions.isAlpnAvailable()Z+0
j  io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(Lio/vertx/core/net/TCPSSLOptions;)Lio/vertx/core/net/SSLEngineOptions;+33
j  io.vertx.core.net.impl.SSLHelper.<init>(Lio/vertx/core/http/HttpClientOptions;Lio/vertx/core/net/KeyCertOptions;Lio/vertx/core/net/TrustOptions;)V+34
j  io.vertx.core.http.impl.HttpClientImpl.<init>(Lio/vertx/core/impl/VertxInternal;Lio/vertx/core/http/HttpClientOptions;)V+177
j  io.vertx.core.impl.VertxImpl.createHttpClient(Lio/vertx/core/http/HttpClientOptions;)Lio/vertx/core/http/HttpClient;+6
j

**Comment by Rainlone** [comment]
@normanmaurer

**Comment by normanmaurer** [comment]
This seems like you may have multiple netty-tcnative versions on the classpath or use a wrong version

**Comment by Rainlone** [comment]
> This seems like you may have multiple netty-tcnative versions on the classpath or use a wrong version

Hi,Thanks @normanmaurer.It's really the case

**Comment by normanmaurer** [comment]
I think this means we can close this
