### ISSUE TITLE
Consider adding support for OQS-OpenSSL

### ISSUE THREAD

**Issue by mrshneaky** [netty/netty-tcnative#638]
NIST is currently considering new Post Quantum Cryptography standards.

It would be great to support the use of https://github.com/open-quantum-safe/openssl
At present consuming a a dilithium certificate or any PQC algorithm is not supported.

**Comment by normanmaurer** [comment]
It's not something we are currently looking for. That said you may be able to fork netty-tcnative and do it yourself.
