### ISSUE TITLE
Failed to load any of the given libraries: [netty_tcnative_osx_aarch_64, netty_tcnative_aarch_64, netty_tcnative]

### ISSUE THREAD

**Issue by Honeylemonade** [netty/netty-tcnative#648]
Recently, I work with my M1 MacBook. When i use netty , i found the Error「Failed to load any of the given libraries: [netty_tcnative_osx_aarch_64, netty_tcnative_aarch_64, netty_tcnative] .
![image](https://user-images.githubusercontent.com/38828449/120294347-af150380-c2f8-11eb-8e33-2470a3baf561.png)

the log seems told me to use the right version for netty_tcnative, but when I search it in maven central repository,there's no correct version for my m1 Mac.

then, i try to compile on my own computer, but still compile failed. 
so ,is there anyone have succeed? And when is the official publish the netty_tcnative_osx_aarch_64.jar

**Comment by gacktomo** [comment]
I added 'io.netty:netty-tcnative-boringssl-static:2.0.25.Final' and it worked.

**Comment by normanmaurer** [comment]
This was fixed in  2.0.42.Final

**Comment by Flyyellow** [comment]
I got the same problem.

**Comment by zhangjiyh** [comment]
I got the same problem.

**Comment by Flyyellow** [comment]
I have fixed this problem, i used these dependencies in my project, like:
`
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.47.Final</version>
        </dependency>
        
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>1.45.0</version>
        </dependency>
`

**Comment by Flyyellow** [comment]
I have fixed this problem, i used these dependencies in my project, like:
`
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.47.Final</version>
        </dependency>
        
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>1.45.0</version>
        </dependency>
`

**Comment by Flyyellow** [comment]
I have fixed this problem, i used these dependencies in my project, like:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/44288531/165453015-8216255d-a56b-4cd4-aacc-00a8ac600026.png">
