### ISSUE TITLE
Methods do not exist in BoringSSL

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#65]
PKCS12_verify_mac (sslcontext.c)
CONF_modules_unload (ssl.c)

**Comment by nmittler** [comment]
@Scottmitch For [CONF_modules_unload](https://github.com/netty/netty-tcnative/blob/1.1.33/src/main/c/ssl.c#L310), it looks like it should simply not be called for BoringSSL. It's intended to cleanup after calling [OPENSSL_load_builtin_modules](https://github.com/netty/netty-tcnative/blob/1.1.33/src/main/c/ssl.c#L691), which is not called for BoringSSL.

**Comment by Scottmitch** [comment]
+1. was then starting to look into PKCS12_verify_mac (p12_mult.c in openssl)

**Comment by nmittler** [comment]
Cool ... I'm pinging Adam internally to see what his thoughts are.

**Comment by nmittler** [comment]
Ok, submitted the fix for CONF_modules_unload ... now just need to fix PKCS12_verify_mac

**Comment by Scottmitch** [comment]
@nmittler - Is this 1 remaining method going to be supported by boringssl?

**Comment by nmittler** [comment]
This method has been added to BoringSSL: https://code.google.com/p/chromium/issues/detail?id=536939

Closing this issue.

**Comment by Scottmitch** [comment]
thanks @nmittler !
