### ISSUE TITLE
tcnative > 2.0.35 Fails to start in osgi

### ISSUE THREAD

**Issue by karthickm512** [netty/netty-tcnative#657]
netty-tcnative bundles above 2.0.35 version fail to start in Osgi environment citing 'osgi r3 bundle not supported'.

The reason is, the Manifest of tcnative does not have any import/export declaration while tcnative version 2.0.35 and less have import/export defined.

Please add this info so that latest versions can be used,

**Comment by normanmaurer** [comment]
Do you want to do a PR?

**Comment by karthickm512** [comment]
sorry whats a PR? I am a consumer of tcnative osgified jar

**Comment by NiteshKant** [comment]
PR is an acronym for Pull Request. In other words, can you make the changes you are requesting here? We are happy to review the changes for you.

**Comment by karthickm512** [comment]
Sorry I have no coding knowledge, so it would be better if I don't code :) And any Karaf users should be facing this issue for months now.

==Following is what is found in Manifest of 2.0.35.Final==
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.8.2
Created-By: Apache Maven Bundle Plugin
Implementation-Title: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Description: A Mavenized fork of Tomcat Native which incorporat
 es various patches. This artifact is dynamically linked    to OpenSSL
  and Apache APR.
Automatic-Module-Name: io.netty.tcnative.openssl.dynamic
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0
Bundle-SymbolicName: io.netty.tcnative
Implementation-Version: 2.0.35.Final
Archiver-Version: Plexus Archiver
Built-By: root
Bnd-LastModified: 1607414176986
Bundle-ManifestVersion: 2
Implementation-Vendor-Id: io.netty
Bundle-DocURL: http://netty.io/
Bundle-Vendor: The Netty Project
**Import-Package**: org.eclipse.jetty.alpn;version="[1,2)";resolution:=opt
 ional,org.eclipse.jetty.npn;version="[1,2)";resolution:=optional,sun.
 nio.ch;resolution:=optional
Tool: Bnd-2.1.0.20130426-122213
Implementation-Vendor: The Netty Project
**Export-Package**: io.netty.internal.tcnative;version="2.0.35.Final"
Bundle-Name: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Version: 2.0.35.Final
Bundle-NativeCode: META-INF/native/libnetty_tcnative_linux_x86_64.so;o
 sname=linux;processor=x86_64
Build-Jdk: 1.8.0_265

==While the following is what is found in 2.0.41.Final Manifest==
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.11
Created-By: Apache Maven 3.6.3
Automatic-Module-Name: io.netty.tcnative.openssl.dynamic
Archiver-Version: Plexus Archiver
Built-By: root
Build-Jdk: 1.8.0_292

**Comment by karthickm512** [comment]
Hi, any updates on this one?

**Comment by croister** [comment]
I have the same issue and have located the commit that introduces the fault.

The commit [https://github.com/netty/netty-tcnative/commit/ef6dd68503eaefdad800a7b905a1ad21a7e1408f](https://github.com/netty/netty-tcnative/commit/ef6dd68503eaefdad800a7b905a1ad21a7e1408f) changes the parent of the "netty-tcnative-parent" pom from "netty-parent" to "oss-parent".

"netty-parent" already has "oss-parent" as its parent so this just cuts out the step in between.
A side effect of this is that the settings and plugins configured in "netty-parent" are not used any more.
One of them is the generation of the OSGi entries in the manifest.

I can create a PR but which way should I go.
Changing back to "netty-parent" as the parent or moving over settings from "netty-parent"?
There might be more things that needs to be moved over and my main focus in fixing the OSGi issue so changing back might be safer.

**Comment by normanmaurer** [comment]
Move settings over

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty-tcnative/pull/664

**Comment by karthickm512** [comment]
Any timelines by which this 2.0.44 version will be available for use?

**Comment by normanmaurer** [comment]
I think tomorrow
