### ISSUE TITLE
Consider releasing OpenSSL-Static on Maven Central

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty-tcnative#660]
Currently, OpenSSL-Static is not released on Maven Central and we have to compile it manually and distribute the native library to our application manually.

Now you might say that we have `BoringSSL-Static` but there are few limitations in that. The biggest reason I choose `OpenSSL-Static` over `BoringSSL-Static` is due to the lack of support to configure the TLSv1.3 ciphers suite. BoringSSL does not support that.
Many of my clients asked for the `TLS_AES_256_GCM_SHA384` cipher only but I was unable to deliver this on `BoringSSL-Static`.

I hope the Netty community will think about this feature request. :)

**Comment by normanmaurer** [comment]
Honestly I don't want to do this... We don't want to be responsible for the security updates of OpenSSL. I think we even consider dropping everything except BoringSSL in the future.

**Comment by hyperxpro** [comment]
> We don't want to be responsible for the security updates of OpenSSL.

But this also applies to BoringSSL, right?

**Comment by normanmaurer** [comment]
> > We don't want to be responsible for the security updates of OpenSSL.
> 
> But this also applies to BoringSSL, right?

Kind of... First of BoringSSL has quite some better "track-record" in terms of security problems and also we have people from Google that help us ensure we do the right thing here.

**Comment by normanmaurer** [comment]
Closing this now
