### ISSUE TITLE
2.0.42 all included jar misses the native lib for osx_x86_64

### ISSUE THREAD

**Issue by slandelle** [netty/netty-tcnative#663]
<img width="311" alt="Screenshot 2021-09-13 at 17 55 30" src="https://user-images.githubusercontent.com/849197/133116739-9c624418-6082-426c-b12a-8e048884d3b1.png">

**Comment by normanmaurer** [comment]
looking...

**Comment by normanmaurer** [comment]
Fixed in 2.0.43.Final

**Comment by slandelle** [comment]
Thanks!
