### ISSUE TITLE
Which version of Tomcat Native does netty-tcnative use?

### ISSUE THREAD

**Issue by Fury-Fox** [netty/netty-tcnative#677]
Which version of Tomcat Native does netty-tcnative use?

**Comment by normanmaurer** [comment]
@Fury-Fox none... it was forked a long time ago.

**Comment by Fury-Fox** [comment]
Is it feasible to upgrade to the latest version of Tomcat Native?

**Comment by normanmaurer** [comment]
Not easily... Please let me know what is missing that make you thing we need to upgrade.

**Comment by Fury-Fox** [comment]
https://github.com/netty/netty-tcnative/issues/630#issuecomment-805767248

**Comment by normanmaurer** [comment]
@Fury-Fox please point me to a specific commit / code that is missing and I will see what I can do.

**Comment by Fury-Fox** [comment]
The problem I encountered is the same as this issue. The compilation passed, but the operation reported error：Suppressed: java.lang.UnsatisfiedLinkError:  (0509-022 Cannot load module  . 0509-026 System error: Cannot run a file that does not have a valid format.)
https://github.com/netty/netty-tcnative/issues/630#issue-839614607

**Comment by normanmaurer** [comment]
Sure but why do you think that upgrading to latest tcnative will fix this ?

**Comment by Fury-Fox** [comment]
Tomcat native supports AIX. I have no other way.

**Comment by normanmaurer** [comment]
Sorry but we have a lot of custom code and AIX is not on our roadmap. If you want to provide a PR to fix this I am happy to review but thats the most I can offer atm.

**Comment by Fury-Fox** [comment]
I thought it could be directly used on AIX after compiling. It turned out that I was wrong.

**Comment by Fury-Fox** [comment]
I think I found the reason for the UnsatisfiedLinkError. 
Build and Test on AIX7.1, IBM JDK 8.

The IBM JVM links in this way when it loads native libraries (for example, System.load(), System.loadLibrary(), Runtime.getRuntime().load(), Runtime.getRuntime().loadLibrary()).
But native libraries is not an "ar" format archive library, it is  a single object file.
