### ISSUE TITLE
Build on AIX 7.1,IBM JDK8

### ISSUE THREAD

**Issue by Fury-Fox** [netty/netty-tcnative#678]
2021-11-08 16:28:09：XLC C/C++v13, coredump: Type = Segmentation error.  

I will use Xlc C/C++v12.1 again.

**Comment by Fury-Fox** [comment]
2021-11-09 16:17:12 ： Xlc C v12 ，error again.

![b1d6a2c2912e0d95f4dfc251c407d4f](https://user-images.githubusercontent.com/25580391/140887464-cdb63db4-8130-42a0-9e74-bd56e47d36c4.jpg)
![3e639c78a50c530dc7932018b4b85e2](https://user-images.githubusercontent.com/25580391/140887496-42a0f9af-f0b1-4c5e-9971-45152e227193.jpg)

What's the next I can do?

**Comment by normanmaurer** [comment]
I have no access to AIX and no knowledge of the platform... Sorry you are on your own sadly

**Comment by Fury-Fox** [comment]
first check openssl error.

**Comment by Fury-Fox** [comment]
buid openssl : must export OPENSSL_ppccap=1
