### ISSUE TITLE
When use_tasks is true, Netty seemingly can supply a freed ByteBuf to SslHandler::decode

### ISSUE THREAD

**Issue by ljnelson** [netty/netty-tcnative#680]
I am not sure whether it is more appropriate to file the bug here or in the main Netty repository.  I'll file it here because I think any fix will have to be done in the C code.

Both grpc-java and Helidon (disclaimer: I work on it, but not in the area affected) tried to upgrade Netty past 4.1.63.Final with no success.  The root cause of both projects' tests' failures seems to be related to the conditional blocks in `sslcontext.c` that perform different behaviors depending on whether `use_tasks` is true or not.  I haven't gone deeper than that.

grpc-java issue: https://github.com/grpc/grpc-java/issues/8605#issuecomment-973051137

Helidon issue: https://github.com/oracle/helidon/pull/3423#issuecomment-973048099

In both issues, I can cause the failing tests in question to succeed by setting the Netty Java system property `io.netty.handler.ssl.openssl.useTasks` to `false`.  This System property was introduced by https://github.com/netty/netty/pull/11242 in version 4.1.64.Final.

The presenting issue seems to be that this results in a `ByteBuf` being supplied to `SslHandler::decode` whose `refCnt()` method returns `0`, so `SslHandler` [tries to read something from it and gets an `IllegalReferenceCountException`](https://stackoverflow.com/questions/70012606/what-does-it-mean-when-a-buffers-refcnt-is-0-when-it-is-received-by-the-first).

I can't speak for the grpc-java project, but in Helidon we noticed this problem [only when doing mutual authentication](https://github.com/oracle/helidon/blob/c412083ee18699483393a15bb459e9430541e941/grpc/server/src/test/java/io/helidon/grpc/server/SslIT.java#L208-L225).  I _believe_ those are the circumstances under which the grpc-java test fails as well, since the failure outputs `io.grpc.netty.NettyClientTransportTest > tlsNegotiationServerExecutorShouldSucceed FAILED`.

In Helidon's case, and maybe in grpc-java as well?, we're using OpenSSL and so I wonder if this is also related to https://github.com/netty/netty/issues/11489.

**Comment by normanmaurer** [comment]
Thanks I will have a look.

**Comment by normanmaurer** [comment]
@ljnelson I have found the root-cause and fixed it (its a bug in netty itself). Currently working on a unit test, so stay tuned.

**Comment by ljnelson** [comment]
Is there a rough idea of when 4.1.71.Final (containing this fix) will be released? Thanks for your work.

**Comment by normanmaurer** [comment]
@ljnelson yes... this week
