### ISSUE TITLE
tcnative 2.0.46 breaks netty dependency resolution

### ISSUE THREAD

**Issue by karthickm512** [netty/netty-tcnative#683]
We try to step up from tcnative 2.0.44.Final to 2.0.46 Final but it fails to start other netty bundles in Karaf container. Reason being that 2.0.46.Final manifest lacks export packages, which leads to other netty (like netty handler, codec etc) fail to start. Please fix it so that latest update of netty 2.1.72 related to log4j CVE could be deployed

Following is seen in 2.0.44.Final manifest which is missing in 2.0.46.Final

Manifest-Version: 1.0
Implementation-Title: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Description: A Mavenized fork of Tomcat Native which incorporat
es various patches. This artifact is dynamically linked to OpenSSL
and Apache APR.
Automatic-Module-Name: io.netty.internal.tcnative
Bundle-SymbolicName: io.netty.tcnative
Implementation-Version: 2.0.46.Final
Built-By: norman
Bnd-LastModified: 1637143333958
Bundle-ManifestVersion: 2
Implementation-Vendor-Id: io.netty
Tool: Bnd-5.1.1.202006162103
Bundle-Name: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Version: 2.0.46.Final
Build-Jdk-Spec: 1.8
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_252
Implementation-URL: https://github.com/netty/netty-tcnative/netty-tcna
tive/

**Comment by karthickm512** [comment]
@normanmaurer Any views on this?

**Comment by normanmaurer** [comment]
@karthickm512 can you provide a PR to fix this ?

**Comment by karthickm512** [comment]
I believe there are dependent netty projects which needs focus that I cannot guarantee. So I would better refrain from commits

**Comment by croister** [comment]
I believe the issue is caused by the move of classes to the extra module.
Even though I import the new bundle openssl is not working.
The solution is probably to revert aeb8f92079dc5f8958beb64fdfe56ec6d01fd04e "Move classes to extra modules (#674)".

**Comment by karthickm512** [comment]
@normanmaurer Any possibility to speed up the patch from netty itself?

**Comment by normanmaurer** [comment]
I will need to look into it but let me say I am far from being an OSGI expert. Also I can't promise I will have time this week

**Comment by normanmaurer** [comment]
@karthickm512 hmm the export package is provided by netty-tcnative-classes. Do you load this one as well ?

**Comment by normanmaurer** [comment]
@croister

**Comment by croister** [comment]
Yes, I loaded the netty-tcnative-classes bundle as well.
The bundles get resolved but openssl is not working.
My suspicion is that the java classes needs to be in the same bundle as the native implementation.
But that is only a guess.

**Comment by croister** [comment]
We need this fixed as soon as possible.
Either a fixed tcnative or stepping down the requirement in Netty to allow us using the 2.0.45 version with the latest Netty version.

**Comment by normanmaurer** [comment]
@croister we live PRs ... that said reverting the commit that split the hard is not an option

**Comment by normanmaurer** [comment]
Seems like something like this should fix it: https://github.com/netty/netty/pull/12018
