### ISSUE TITLE
Compatibility check for io.netty (4.1.72.Final) with netty-tcnative(2.0.44.Final)

### ISSUE THREAD

**Issue by ravihackworks** [netty/netty-tcnative#685]
As per maven link - https://mvnrepository.com/artifact/io.netty/netty-handler/4.1.72.Final.
2.0.46 version is recommended version for netty-tcnative.
 
![image](https://user-images.githubusercontent.com/45195641/146500722-125a4afe-450c-4597-8efd-397788f0a2cb.png)

can we use version 2.0.44 for netty-tcnative or does it have any issue ? 
![image](https://user-images.githubusercontent.com/45195641/146500902-d7e94afe-5de1-482e-a613-bbda01ddc777.png)

We are using below dependencies 
![image](https://user-images.githubusercontent.com/45195641/146501185-4d1bc718-ab98-4203-8994-441d70866d9a.png)

**Comment by normanmaurer** [comment]
@ravihackworks I think it should work... but why ?

**Comment by ravihackworks** [comment]
As per recommendation, we should use 2.0.46.Final but this is faulty. Refer - https://github.com/netty/netty-tcnative/issues/683
Hence want to use 2.0.44. 

Not sure, is that ok to use or not ok ?

**Comment by ravihackworks** [comment]
Early feedback will help us in taking decision.

**Comment by normanmaurer** [comment]
I think it should work

**Comment by ParrySMS** [comment]
netty 4.1.72.Final is works with netty-tcnative-classes 2.0.46.Final.


```
 <properties>
    <netty.version>4.1.72.Final</netty.version>
  </properties>

```

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-classes</artifactId>
      <version>2.0.46.Final</version>
    </dependency>
```
