### ISSUE TITLE
Problem compiling 2.0.46

### ISSUE THREAD

**Issue by morvael** [netty/netty-tcnative#686]
Is this a temporary thing related to problems with 2.0.46 or should I start looking for a fix? And I have no idea what that can be.

![netty](https://user-images.githubusercontent.com/1133953/146937544-b241e017-dbf5-4083-91cd-06a896e64bae.png)

I need to compile netty myself to get the ppc64le epoll native library. I must say every version of Netty this year brings compilation problems...

**Comment by normanmaurer** [comment]
Let me check

**Comment by normanmaurer** [comment]
@morvael I just opened https://github.com/netty/netty-tcnative/pull/687 to fix this in the future. That said you can workaround it by using `./mvn clean package-DskipJapicmp=true`.

**Comment by morvael** [comment]
Thanks!
