### ISSUE TITLE
Analyze warnings

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#69]
A recent discovery (https://github.com/netty/netty-tcnative/pull/68#discussion-diff-40719398) has brought up a passing an invalid pointer type is flagged as a warning and still compiles. It turned out this pointer was not used in the method, but if it was undefined results would have followed. We should analyze warnings, and consider turning some (all?) warning into errors to ensure code quality.

**Comment by Scottmitch** [comment]
@normanmaurer @nmittler - FYI

**Comment by Scottmitch** [comment]
Another instance of incompatible pointer type being used was found in the same PR https://github.com/netty/netty-tcnative/pull/68#discussion_r40722627. This method is used.

**Comment by normanmaurer** [comment]
@Scottmitch let me take care...

**Comment by normanmaurer** [comment]
Fixed by 9b06af6863bcb8c7eaf123ef7ee6134743c26690
