### ISSUE TITLE
license check fails

### ISSUE THREAD

**Issue by cforce** [netty/netty-tcnative#692]
INFO] 
[INFO] --- license-maven-plugin:2.0.0:aggregate-add-third-party (check) 
[INFO] Detected 38 license(s).
[WARNING] There is 1 dependency with no license :
[WARNING]  - io.netty--netty-tcnative-classes--2.0.46.Final
 - io.netty--netty-tcnative-classes--2.0.46.Final

**Comment by normanmaurer** [comment]
Will have a look

**Comment by normanmaurer** [comment]
Actually this was fixed by https://github.com/netty/netty-tcnative/pull/682
