### ISSUE TITLE
Automatic-Module-Name is not set correctly in MANIFEST.MF

### ISSUE THREAD

**Issue by jonkjenn** [netty/netty-tcnative#708]
Examples 
https://github.com/netty/netty-tcnative/blob/main/boringssl-static/pom.xml#L41
https://github.com/netty/netty-tcnative/blob/main/openssl-classes/pom.xml#L46

Actual value in both jars
`Automatic-Module-Name: io.netty.internal.tcnative`

Since boringssl-static includes openssl-classes this seems to prevent using this package while running on module path.
```
java.lang.module.FindException: Two versions of module io.netty.internal.tcnative found in / (netty-tcnative-classes-2.0.46.Final.jar and netty-tcnative-boringssl-static-2.0.46.Final.jar)
```

**Comment by normanmaurer** [comment]
Good catch... Let me fix this

**Comment by normanmaurer** [comment]
@jonkjenn PTAL https://github.com/netty/netty-tcnative/pull/709

**Comment by tinolazreg** [comment]
Do you have an ETA on when this fix will be deployed?
