### ISSUE TITLE
Mac M1 artifact was not found on maven central

### ISSUE THREAD

**Issue by sokomishalov** [netty/netty-tcnative#711]
Despite [providing support for mac m1 chip](https://github.com/netty/netty-tcnative/pull/662) there are no separate artifacts for `osx-aarch_64` classifier [on maven central](https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.50.Final/).

**Comment by normanmaurer** [comment]
@sokomishalov we only support `osx-aarch_64` for our static compiled version against BoringSSL:

https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.51.Final/

**Comment by sokomishalov** [comment]
Got it, thanks! @normanmaurer
