### ISSUE TITLE
error: bundle to io.netty.tcnative-boringssl-static

### ISSUE THREAD

**Issue by hchy234** [netty/netty-tcnative#712]
![IMG_20220316_152058](https://user-images.githubusercontent.com/90098365/158538139-33ec4688-d9ad-4a80-af0e-f4fead5e9c90.jpg)
![1647415671384](https://user-images.githubusercontent.com/90098365/158538253-3c52697e-1523-4b46-a6e2-b5398a0b60f5.jpg)

**Comment by normanmaurer** [comment]
Please upgrade to the latest version...

**Comment by cherryWangqaz** [comment]
> ![IMG_20220316_152058](https://user-images.githubusercontent.com/90098365/158538139-33ec4688-d9ad-4a80-af0e-f4fead5e9c90.jpg) ![1647415671384](https://user-images.githubusercontent.com/90098365/158538253-3c52697e-1523-4b46-a6e2-b5398a0b60f5.jpg)

**Comment by cherryWangqaz** [comment]
> ![IMG_20220316_152058](https://user-images.githubusercontent.com/90098365/158538139-33ec4688-d9ad-4a80-af0e-f4fead5e9c90.jpg) ![1647415671384](https://user-images.githubusercontent.com/90098365/158538253-3c52697e-1523-4b46-a6e2-b5398a0b60f5.jpg)
do you fix the issue by upgrading to the latest version ? it seems that we have the same problem.  do you run the software on the aarch_64?@hchy234

**Comment by gspadotto** [comment]
Try changing the manifest file as described in the last sentence [here](https://github.com/netty/netty/issues/12494#issuecomment-1162892766).
