### ISSUE TITLE
Running on aarch_64, missing requirement [io.netty.tcnative-boringssl-static] osgi.native

### ISSUE THREAD

**Issue by cherryWangqaz** [netty/netty-tcnative#723]
I try to run onos on aarch_64, but an error in the pic happened.
I  changed io.netty.tcnative-boringssl-static version to support aarch_64, like to 2.0.36 ,but not working....
Is anyone can help me ,pleaseeeeeee!
![1651139206(1)](https://user-images.githubusercontent.com/104562296/165725948-11e19ade-1562-421f-b272-1ff8f66dced5.jpg)

**Comment by cherryWangqaz** [comment]
![1651140865(1)](https://user-images.githubusercontent.com/104562296/165732019-d1206af8-1980-4683-9031-aaebe76d90b5.jpg)

**Comment by cherryWangqaz** [comment]
> ![1651140865(1)](https://user-images.githubusercontent.com/104562296/165732019-d1206af8-1980-4683-9031-aaebe76d90b5.jpg)

According to issue#712  I tried change netty-tcnative-boringssl-static to 2.0.51.Final  but did not fix .....TAT.....

**Comment by gspadotto** [comment]
Try changing the manifest file as described in the last sentence [here](https://github.com/netty/netty/issues/12494#issuecomment-1162892766).

**Comment by cherryWangqaz** [comment]
> Try changing the manifest file as described in the last sentence [here](https://github.com/netty/netty/issues/12494#issuecomment-1162892766).
 I found packet compiled on aarch64 by others, and it did work~ anyway ,thank u.
