### ISSUE TITLE
Invalid Automatic-Module-Name.

### ISSUE THREAD

**Issue by vab2048** [netty/netty-tcnative#724]
The `MANIFEST.MF` file within the `netty-tcnative-boringssl-static-2.0.51.Final.jar` file contains the following line:

`Automatic-Module-Name: io.netty.tcnative.openssl.osx-x86_64`

The '-' is not allowed in module names and so this module name is invalid. See https://sormuras.github.io/blog/2018-11-16-invalid-automatic-module-names.html. 

I checked it with the output of the `jar` command:

```
jar --describe-module --file .\netty-tcnative-boringssl-static-2.0.51.Final.jar
Unable to derive module descriptor for: .\netty-tcnative-boringssl-static-2.0.51.Final.jar
Automatic-Module-Name: io.netty.tcnative.openssl.osx-x86_64: 
Invalid module name: 'osx-x86_64' is not a Java identifier
```

This is causing some issues with Java projects which use the module system. IntelliJ complains about netty-tcnative-boringssl-static:

```
cannot determine module name for C:\Users\v\.gradle\caches\modules-2\files-2.1\io.netty\netty-tcnative-boringssl-static\2.0.51.Final\68fa15327d52b8150bc8d4f6217da815630bd711\netty-tcnative-boringssl-static-2.0.51.Final.jar
```

Can you please fix the automatic module name so that it is valid.

**Comment by normanmaurer** [comment]
Working on it.

**Comment by normanmaurer** [comment]
@vab2048 check https://github.com/netty/netty-tcnative/pull/725

**Comment by vab2048** [comment]
Wonderful. Thanks @normanmaurer
