### ISSUE TITLE
Rafael Ramseier 

### ISSUE THREAD

**Issue by RafaelRamseier** [netty/netty-tcnative#752]
Tippen Sie auf ein Element, um es in das Textfeld einzufügen.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder zu löschen.
![Uploading IMG_20221009_000125_9.jpg…]()

**Comment by hyperxpro** [comment]
????????????????????????????????????????????????????????????????????????
