### ISSUE TITLE
How is openssl 1.1.1 EOL going to affect boringssl / netty-tcnative-boringssl-static?

### ISSUE THREAD

**Issue by spensonshih** [netty/netty-tcnative#791]
My project relies on netty-tcnative-boringssl-static for memory efficiency. From what I can tell, boringssl was forked from openssl 1.1.1, which is soon reaching end of life. I'd like to know how this might affect boringssl, and transitively netty-tcnative-boringssl-static. Can I expect boringssl / netty-tcnative-boringssl-static to continue with security patches after eol of openssl 1.1.1?

**Comment by slandelle** [comment]
BoringSSL is actively maintained at Google and is the TLS component of Google Chrome. You can now consider them as totally different projects with different code bases.
