### ISSUE TITLE
Segfault thrown using boringssl-static > 2.0.56.Final on azul/zulu-openjdk-alpine:17-jre

### ISSUE THREAD

**Issue by johnk-scalable** [netty/netty-tcnative#798]
netty-tcnative-boringssl-static lib is throwing a segfault when being run in minimal docker image with just spring boot and netty-handler:
```
io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.61.Final:compile
```

Using an older version does not result in segfault:
```
io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.56.Final:compile
```

Minimal repo to reproduce is here:
https://github.com/johnk-scalable/boringssl-issue

**Comment by normanmaurer** [comment]
I will need to have a look... I wonder if this might be related to how to static compile against libc++

**Comment by valodzka** [comment]
Unsure is it same issue or different, but after ugprade netty-tcnative-boringssl-static 2.0.59 => 2.0.61 I see related to boringssl SIGSEGV-s https://gist.github.com/valodzka/9b058063112b9093fcbba4cd0655e6b1

They are not too frequent, but also not rare. Also azul, also openjdk 17, but not alpine.
