### ISSUE TITLE
CentOS 6 / Amazon Linux openSSL trouble with pre-packaged netty-tcnative

### ISSUE THREAD

**Issue by flozano** [netty/netty-tcnative#80]
Seems related to https://github.com/netty/netty-tcnative/issues/46 / https://github.com/netty/netty-tcnative/issues/44... anyhow, we're getting:

```
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative3858998603798039886.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_20]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929) ~[na:1.8.0_20]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814) ~[na:1.8.0_20]
        at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_20]
        at java.lang.System.load(System.java:1083) ~[na:1.8.0_20]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) ~[netty-common-4.1.0.Beta8.jar:4.1.0.Beta8]
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:58) ~[netty-handler-4.1.0.Beta8.jar:4.1.0.Beta8]
        ... 54 common frames omitted
```

with 1.1.33 Fork 9 and 1.1.33 Fork 10. 

It seems fork 6 used to work well.

**Comment by wsh** [comment]
I'm seeing the same thing. :(

```
failed to load the required native library: java.lang.UnsatisfiedLinkError
java.lang.UnsatisfiedLinkError: failed to load the required native library at 
io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:154) at 
io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:142) at 
io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:134) at 
io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:275) at 
io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:743) at 
io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:319)
Caused by:
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative2195859585022570847.so:
libapr1.so.0: cannot open shared object file: No such file or directory at 
java.lang.ClassLoader$NativeLibrary.load(Native Method) at 
java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937) at 
java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822) at 
java.lang.Runtime.load0(Runtime.java:809) at java.lang.System.load(System.java:1086) at 
io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) at 
io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:58)
```
This is happening in AWS Lambda, Amazon Linux 2015.03.

**Comment by normanmaurer** [comment]
@wsh @flozano how did you specify the dependency ? what jar is pulled in ?

**Comment by normanmaurer** [comment]
And sorry I missed this one :(

**Comment by wsh** [comment]
Don't be sorry! Thanks for your hard work!!
'io.netty:netty-tcnative:1.1.33.Fork10-linux-x86_64-fedora' (https://repo1.maven.org/maven2/io/netty/netty-tcnative/1.1.33.Fork10/netty-tcnative-1.1.33.Fork10-linux-x86_64-fedora.jar)

**Comment by normanmaurer** [comment]
@wsh I think you need to do:

`yum install apr` . libapr1.so.0 seems to be missing.

**Comment by wsh** [comment]
Ah, okay. I was hoping that doing a build on Amazon Linux would fix things.

@normanmaurer my problem is that this is AWS Lambda. I don't have control over OS packages. Is there any way that you know of to package APR in a JAR? :package:

**Comment by normanmaurer** [comment]
I guess it would be possible with static linking but for this you will need to hack the build.

**Comment by wsh** [comment]
I'll look into that. :smile: Thanks for the advice!

**Comment by normanmaurer** [comment]
@flozano so now back to you... can you tell me what jar you use ?

**Comment by flozano** [comment]
I *also* missed this github notification. I was using the wrong one, the generic linux non-fedora. Using the fedora one fixes it, so no problem... anyway I had to build my own openssl for ALPN, so I'm back to generic linux tcnative.

**Comment by normanmaurer** [comment]
Seems like this can be closed. You can also use "netty-tcnative-boringssl-static" if you not want to worry about all of this

**Comment by flozano** [comment]
Yes, boringssl is much more convenient and works well in centos 6. Thanks!
