### ISSUE TITLE
dose tcnative support  AES256-SHA256

### ISSUE THREAD

**Issue by xiandafu** [netty/netty-tcnative#804]
$openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
$openssl ciphers  -V 'ALL'  |  grep 0x3D
0x00,0x3D - AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256

The variable suieEnables does not contain the ciphers "AES256-SHA256"

```
SSLContext.setCipherSuite(sslCtx, "ALL", false);
final long ssl = SSL.newSSL(sslCtx, true);
String[] ciphers = SSL.getCiphers(ssl);

```

Can someone give me some tips? Thank you very much

**Comment by normanmaurer** [comment]
It should support whatever is supported by the underlying openssl version or boringssl version (whatever you use).
