### ISSUE TITLE
Request for published builds of netty-tcnative-openssl-static on Maven central

### ISSUE THREAD

**Issue by hasnain-db** [netty/netty-tcnative#812]
Hi, would it be possible to get this variant also published on Maven central in addition to the boringssl variant? It would simplify our deployment process a lot to be able to reference published artifacts instead of building and hosting our own.

Happy to put in the work to improve the build scripts to make this happen if some pointers can be provided.

Thank you!

**Comment by normanmaurer** [comment]
We dont want to do this as we dont have anyone that guarantees "fast" handling of CVEs etc for it. Generally speaking I think  we might even consider only support BoringSSL in the future.
