### ISSUE TITLE
Android 上无法进行使用

### ISSUE THREAD

**Issue by Heart-Beats** [netty/netty-tcnative#834]
您好，我需要在安卓应用内开启服务接口，使用了 [AndroidServer](https://github.com/fengzhizi715/AndroidServer#androidserver)  这个库，它是基于 Netty 进行封装开发的，当我在此库上开启 TLS 能力时，它是通过如下方法创建 SslContext:
![image](https://github.com/netty/netty-tcnative/assets/33248551/300dc323-cba0-4f08-8d79-f32f90e9795f)
然后报如下错误：
![image](https://github.com/netty/netty-tcnative/assets/33248551/e0f12f70-c5b1-4ba9-b0f6-44368fd44625)

断点调试发现是这儿报的异常:
![image](https://github.com/netty/netty-tcnative/assets/33248551/d362ac7e-2eda-4004-a835-0af062cf28e1)

我随后便添加了 netty-tcnative 的依赖，运行时报错如下：
![image](https://github.com/netty/netty-tcnative/assets/33248551/e068137f-748f-454c-9694-2d317d481b52)

可以看到 NativeLibraryLoader 是没有针对安卓进行兼容， 这块可以支持一下吗？

**Comment by 4kingRAS** [comment]
安卓的架构是 arm64 ， 很明显不支持啊

**Comment by Heart-Beats** [comment]
> 安卓的架构是 arm64 ， 很明显不支持啊

这个我知道呀，但是 c 是支持跨平台的，只要接入 NDK 进行编译，是可以编译出安卓平台可以使用的动态库的
