### ISSUE TITLE
Statically link APR when building BoringSSL profile

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#85]
@Scottmitch I'm assigning to you for now, since you mentioned you'd take a look.

**Comment by Scottmitch** [comment]
@nmittler - Thanks for the reminder ... let me pull myself out of the slacker hole that I dug last week.

**Comment by normanmaurer** [comment]
LOL 👌

**Comment by nmittler** [comment]
LOL ... awesome, thanks @Scottmitch!

**Comment by nmittler** [comment]
Closed via #89

**Comment by Scottmitch** [comment]
thanks @nmittler !
