### ISSUE TITLE
Feasibility of creating a javax.net.ssl.SSLContext that would use netty-tcnatives as its engine

### ISSUE THREAD

**Issue by felipeek** [netty/netty-tcnative#887]
Hello!

We are currently considering changing the TLS engine of our Java project to netty-tcnatives. However, our project has a lot of dependencies (internal and external), and all of them rely on JSSE (i.e. they usually obtain a `javax.net.ssl.SSLContext` to serve or connect to TLS peers).

I was poking around netty to see if it provided an implementation of `javax.net.ssl.SSLContext` (similar to what [wildfly-openssl](https://github.com/wildfly-security/wildfly-openssl) does) and from my research it does not (at least when the backend is openssl). However, I noticed that `io.netty.handler.ssl.SslContext` implements `newEngine` and `sessionContext`, which return `SSLEngine` and `SSLSessionContext`, respectively, which are standard JSSE classes. This makes it theoretically almost compatible with `SSLContextSpi`, but not quite, as I did not find the concept of `SSLSocket` in netty, which would be required for a direct integration.

Anyway, I was wondering if it would be theoretically feasible to integrate netty-tcnative with JSSE `javax.net.ssl.SSLContext`, in which case I could spend more time and dive deeper into this. Or if this would be a bad idea. I assume there was a reason of why this was not done, so I wanted to ask for the developers here. :)

Thank you very much! Appreciate on advance!

**Comment by normanmaurer** [comment]
This is really out of scope here.. I think your best bet might be ACCP: https://github.com/corretto/amazon-corretto-crypto-provider
