### ISSUE TITLE
Compiling statically linked boring profile requires fPIC to be set in environment

### ISSUE THREAD

**Issue by louiscryan** [netty/netty-tcnative#95]
Not a bug deal but I had to do

export CFLAGS=-fPIC

to get the profile to work correctly

**Comment by normanmaurer** [comment]
Strange... Works here without.

**Comment by louiscryan** [comment]
Do you see fPIC in the gcc command line when api is built? I wasn't, might
be worth diffing the configure logs. Ill put mine up tomorrow

**Comment by normanmaurer** [comment]
@louiscryan will check... Also just adding it to the CFLAGS in the pom.xml should work and not harm. WDYT ?

**Comment by normanmaurer** [comment]
@louiscryan ok have the same problem on linux... I will fix it

**Comment by nmittler** [comment]
Awesome, thanks @louiscryan!

@normanmaurer shall I send a PR?

**Comment by normanmaurer** [comment]
I'm on it

**Comment by nmittler** [comment]
:beers:

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty-tcnative/pull/98
