### ISSUE TITLE
Boring SSL library has disabled stackguard

### ISSUE THREAD

**Issue by louiscryan** [netty/netty-tcnative#99]
Get the following warning when VM (Oracle 7 64 bit) starts

Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/libnetty-tcnative9180597608360647425.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

**Comment by normanmaurer** [comment]
@louiscryan so it still works but produce the warning ?

**Comment by louiscryan** [comment]
Yup. Works just fine, just get the warning logs. Clearly not a high
priority bug.

Not sure if it varies over VMs either. Can try that out.
